### ISSUE TITLE
[Menu]: weird menu behavior on mobile (touch)

### ISSUE THREAD

**Issue by jiblett1000** [chakra-ui/ark#1001]
### Description

While using the Menu component in an array of card items, I noticed a weird behavior. 

If clicking a menu trigger and then immediately clicking another trigger (without clicking off), they would all stay activated. In particular they stay activated when using `@click.stop` on the menu trigger. (but only in chrome). When not using `@click.stop` they still stay open briefly, but then all close without any further action. This only seems to happen when working in "responsive design mode" however. So, I'm guessing it is related to some different handling of touch events vs click events maybe?

### Link to Reproduction

https://stackblitz.com/edit/nuxt-starter-p9zbud?file=app.vue,components%2FCustomMenu.vue

### Steps to reproduce

1. In the top right of stackblitz, click "Open in New Tab".
2. Open developer tools and enable "responsive design mode" or some mobile dev mode.
3. Click on a trigger.
4. Click on another trigger.
5. Witness odd behavior

### Ark UI Version

0.4

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

Latest Chrome and Firefox

**Comment by Shyrro** [comment]
Hey @jiblett1000 

Thanks for reporting this. This doesn't seem like a Vue only issue, i was able to reproduce that in other frameworks as well. 

This is probably coming from Zag so i'm moving the issue elsewhere.

**Comment by Shyrro** [comment]
Closed in favor of this : https://github.com/chakra-ui/zag/issues/659
