### ISSUE TITLE
[Website]: Slider showcase not interactive 

### ISSUE THREAD

**Issue by jeferson-sb** [chakra-ui/ark#1010]
### Description

When I try to drag or click inside of the Slider example of showcase that is below the hero of the website it doesn't do anything.
See the video below:

https://github.com/chakra-ui/ark/assets/30840709/88086f7b-e5b3-4bb0-ad43-43b0da05d5c0

### Link to Reproduction

https://ark-ui.com/

### Steps to reproduce

1. Go to https://ark-ui.com/
2. Scroll below the hero section
3. Click on the Slider tab
4. Try to drag or click in one of the labels

### Ark UI Version

1.0.0

### Framework

- [X] React
- [X] Solid
- [X] Vue

### Browser

Chrome 113

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. Happy to report that this issue has been solved.
