### ISSUE TITLE
Warning: "Critical dependency: require function is used in a way in which dependencies cannot be statically extracted"

### ISSUE THREAD

**Issue by jonathanwilke** [chakra-ui/ark#1032]
### Description

Hey there,

I am lately getting this warning in my console when I use the Ark-UI components (in this specific case the Menu).

<img width="894" alt="Bildschirmfoto 2023-06-02 um 08 12 34" src="https://github.com/chakra-ui/ark/assets/1453455/a90ca834-49b9-4d24-b8cf-9e6e1a3e6d99">

### Link to Reproduction

Dont have a link

### Steps to reproduce

It's just running my local dev server with Next.js.

### Ark UI Version

0.5.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. I'm happy to tell that this bug will be fixed with the next release.
