### ISSUE TITLE
Add table component

### ISSUE THREAD

**Issue by MarcelGeo** [chakra-ui/ark#1039]
### Description

Is it possible to add table component to library with standard table (or data list) functionality:

- header
- rows
- selection
- pagination
- data fetching
- loading
...

It could be very usefull. Thanks :) 

### Proposed Solution or API

```
<Table items="someArray" columns="someColumns" />
```

**Comment by cschroeter** [comment]
Thank your for taking your time to create this issue. I've created a feature request for a table in our official roadmap https://ark-ui.canny.io/feature-requests/p/table-react
