### ISSUE TITLE
Document `Combobox`

### ISSUE THREAD

**Issue by asterikx** [chakra-ui/ark#1049]
### Description

The docs of the [Combobox component](https://ark-ui.com/docs/react/components/combobox/props) seems to be incomplete, as it currently does not contain a showcase and the usage is marked as "TBD".
I am wondering how the Combobox is used and if it is ready to be used.

### Proposed Solution or API

Adding showcase and usage description of the Combobox component to the docs.

**Comment by tzarger** [comment]
Any update here or ETA?

**Comment by cschroeter** [comment]
Not the highest priority but you can checkout a code example here: https://github.com/chakra-ui/ark/blob/main/packages/react/src/combobox/combobox.stories.tsx

and checkout the component using storybook `pnpm react storybook`

**Comment by cschroeter** [comment]
For a visuell preview checkout https://park-ui.com/docs/components/combobox

**Comment by cschroeter** [comment]
I've added a bit of documentation and will continue to improve as we go.
https://ark-ui.com/docs/components/combobox
