### ISSUE TITLE
[vue] [carousel]  CarouselNextSlideTrigger and  CarouselPrevSlideTrigger are not exported/bundled correctly

### ISSUE THREAD

**Issue by renatodeleao** [chakra-ui/ark#1051]
### Description

When I try to render the [default example of the documentation](https://ark-ui.com/docs/vue/components/carousel/usage) site on my app, I expected to get a full Carousel correctly rendered, I got "bundle strings" as the output of `CarouselNextSlideTrigger` and  `CarouselPrevSlideTrigger` 

```js
() => createVNode(ark.button, mergedProps.value, { default: () => { var _a; return [(_a = slots.default) == null ? void 0 : _a.call(slots)]; } })() => createVNode(ark.button, mergedProps.value, { default: () => { var _a; return [(_a = slots.default) == null ? void 0 : _a.call(slots)]; } })
```

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-lvhwbc?file=src%2Fcomponents%2FAppCarousel.vue

### Steps to reproduce

Just open the demo.

### Ark UI Version

0.5.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

Any

### Additional Information

Hey 👋 

Was trying this component and got this on my project. At first, iIthough was related to my bundling system (webpack), but can also reproduce it on the latest `vite` + `vue` as per the demo above.

**EDIT:** Looking at the code, https://github.com/chakra-ui/ark/blob/91d84508beea9ae8aefe2f6141520b87245a65f3/packages/vue/src/carousel/carousel-next-slide-trigger.tsx#L13-L16

Shouldn't this be?

```js
return () => (
    <ark.button {...mergedProps.value}>{slots.default?.()}</ark.button> 
)
```

**Comment by Shyrro** [comment]
Hey @renatodeleao 

Thanks for your issue.

Yes i think you're right about the change, would you be able to open a PR? 

Thanks !

**Comment by renatodeleao** [comment]
Absolutely @Shyrro. Here it is https://github.com/chakra-ui/ark/pull/1060
