### ISSUE TITLE
[Vue] Input tags are not exported properly

### ISSUE THREAD

**Issue by hilaliMoncef** [chakra-ui/ark#1078]
### Description

Hello guys,

First of all thanks for the hard work, what a great project !

I noticed (using Nuxt 3.5 & Vue 3.3 on the latest package version 0.5.0) that the Tags Input component is not exported as seen in the following.

```
export { createAnatomy } from '@zag-js/anatomy';
export * from './accordion';
export * from './carousel';
export * from './checkbox';
export * from './color-picker';
export * from './combobox';
export * from './dialog';
export * from './editable';
export * from './environment';
export * from './hover-card';
export * from './menu';
export * from './number-input';
export * from './pagination';
export * from './pin-input';
export * from './popover';
export * from './pressable';
export * from './radio-group';
export * from './range-slider';
export * from './rating-group';
export * from './select';
export * from './slider';
export * from './splitter';
export * from './tabs';
export * from './toast';
export * from './tooltip';
export { useId } from './utils';
```

### Link to Reproduction

https://codesandbox.io/p/sandbox/gifted-dream-cyff7q

### Steps to reproduce

Simply install latest nuxt 3 & Ark UI.
Try to create a new component using the basic usage example given in the docs.

You will get this TS error : "Module '"@ark-ui/vue"' has no exported member 'TagsInput'."

### Ark UI Version

0.5.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. Issue is resolved in `@ark-ui/vue@0.5.1`
