### ISSUE TITLE
feat: add support for standalone imports

### ISSUE THREAD

**Issue by BarrieLAJ** [chakra-ui/ark#1092]
### Description

We are trying to use `@ark-ui/react` as headless UI to implement a design system component library for internal use. Which we want to use in a NextJs 13(app router) Application.

But when we import any of the components from the main path `@ark-ui/react` it brings in all the other components which we do not need and then breaks when used in a server component.

For example when we do the following....
![Screenshot 2023-06-23 at 3 45 47 PM](https://github.com/chakra-ui/ark/assets/41100890/c139c186-f505-45b3-98cb-26e9c2b332e1)

It brings up the following error....
![Screenshot 2023-06-23 at 3 45 47 PM](https://github.com/chakra-ui/ark/assets/41100890/ee818c3e-2132-4d7e-8569-a354900daf02)

We believe there is no tree-shaking capability that prevents the other packages from being imported and that is causing it to import the `use-color-picker` file even though there is no dependence from all the files.

### Proposed Solution or API

we would like to be able to do
`import {Select} from "@ark-ui/react/Select"`
`import {Switch} from "@ark-ui/react/Switch"`

Or tree-shaking solution which will prevent importing all the files

**Comment by cschroeter** [comment]
Thanks for taking time to report this issue. Regarding the error I guess you added the wrong screenshot.

`@ark-ui/react` in fact supports three-shaking. You can verify this by adding e.g. the `<Switch />` component from your example - build your app and then add another component for example the `<Tabs />` and build your app again. You will notice a ~5-8kb increase per component added.

 But if you really want to enforce a explicit import you can always fall back to `@ark-ui/react/dist/switch`

**Comment by BarrieLAJ** [comment]
Oh sorry @cschroeter Totally missed that.
This is the updated error
![Screenshot 2023-06-23 at 3 49 28 PM](https://github.com/chakra-ui/ark/assets/41100890/9ebf71b7-d0c7-4d20-9b97-49ab218feaab)

And for the for importing from `@ark-ui/react/dist/switch` still doesn’t work when importing from `@ark-ui/react/dist/switch`

But what we really want to know is if Ark components can be used as server components?

Here is code sandbox to the recreation of the error

[Switch Component](https://codesandbox.io/p/sandbox/trusting-meadow-ymq597?file=%2Fsrc%2Fcomponents%2FSwitch.tsx%3A15%2C1)

**Comment by cschroeter** [comment]
I think the error that `nextjs` throws its a false positive. I assume their check is a bit to simple. Any how, the workaround I suggested actually does not work right now. But I could make it work. For reference this are the required changes:

`vite.config.ts`
```jsx
 lib: {
      entry: ['src/index.ts', 'src/switch/index.ts'] // and all the other components
  }
```

`package.json`
```json
    "exports": {
      ".": {
        "types": "./dist/index.d.ts",
        "import": "./dist/index.mjs",
        "require": "./dist/index.cjs"
      },
      "switch": {
        "types": "./dist/switch/index.d.ts",
        "import": "./dist/switch/index.mjs",
        "require": "./dist/switch/index.cjs"
      },
      "./package.json": "./package.json"
    }
```

Later in your codebase:

```tsx
import {
  Switch,
  SwitchControl,
  SwitchInput,
  SwitchLabel,
  SwitchThumb,
} from "@ark-ui/react/switch"
```

**Comment by cschroeter** [comment]
So I have a `beta` version up that supports this standalone imports. But since we are using `createContext` most of the components can not be used as React Server Components.

**Comment by BarrieLAJ** [comment]
Great 🙌🏽. Will check it out. Which beta number?
Yes, I went through the react package in the code and saw that Context is used.

**Comment by cschroeter** [comment]
`@ark-ui/reat@0.7.1` has support for path imports. For more infos checkout our [changelog](https://ark-ui.com/docs/react/overview/changelog)

On a personal note I don't believe that RSC are any good for now. For more insights I recommend reading [Is React Having An Angular.js Moment?](https://marmelab.com/blog/2023/06/05/react-angularjs-moment.html)
