### ISSUE TITLE
 Menu positioning doesn't work with SSR

### ISSUE THREAD

**Issue by mezg0** [chakra-ui/ark#1104]
### Description

When you try to use the ´Menu´ component on first render after SSR the menu will not be positioned correctly. 

### Link to Reproduction

https://codesandbox.io/p/sandbox/old-dream-j74yl5?file=%2FREADME.md

### Steps to reproduce

1. Click on `Open menu`
2. Observe that the menu opens in the top left of the screen

### Ark UI Version

0.5.1

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Additional Information

Expected
![image](https://github.com/chakra-ui/ark/assets/52045763/3bb292e4-e39c-4916-a299-9a0a8252cf8d)

Reality
![image](https://github.com/chakra-ui/ark/assets/52045763/1722068f-af2d-4f54-b146-162494830e71)

**Comment by cschroeter** [comment]
Thanks for reporting this issue. We will have a look at this issue shortly

**Comment by mezg0** [comment]
For anyone else that is dealing with this my current solution is to force the component to mount again on first render:

```vue
<script setup>
const key = ref("ssr");
onMounted(() => {
  key.value = "csr";
});
</script>

<template>
  <Menu key={key}>
  ...
  </Menu>
</template>
```

**Comment by mezg0** [comment]
This looks to be an issue will all things that require positioning (`Popover`,`Menu` etc)

**Comment by segunadebayo** [comment]
We fixed this within Zag.js a few months back. I’ve added a Nuxt sandbox there to test these scenarios.

Kindly upgrade to the latest version and check this again. If issue persists, please open an issue in the zag repo.
