### ISSUE TITLE
[Vue] Tabs `value` is not working as intended

### ISSUE THREAD

**Issue by hanneskuettner** [chakra-ui/ark#1110]
### Description

When I use the `value` prop that is documented [for the `TabsProps` here](https://ark-ui.com/docs/vue/components/tabs/props), I don't get the desired effect of programmatically changing the tab. 
In fact it looks like the `value` prop is not even defined on the `Tabs` component as you can see that it is actually treated as an attribute (inspect the tabs element an see it showing up there, or open the Vue devtools).

### Link to Reproduction

https://codesandbox.io/s/sleepy-cache-9gxlx6?file=/src/App.vue

### Steps to reproduce

1. Go to the example and expect the 'solid' tab to be the first one selected (it is not)
3. Change the value of the select box and expected the selected tab to change
4. Observe that the tab does not change at all

### Ark UI Version

0.5.1

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

**Comment by hanneskuettner** [comment]
The desired effect has also been mentioned [here](https://github.com/chakra-ui/ark/issues/915#issuecomment-1539179248), as to be documented.

**Comment by cschroeter** [comment]
Thanks for taking your time to report the issue. The `Tabs` component has been revised. Please check the [tab stories](https://github.com/chakra-ui/ark/blob/main/packages/vue/src/tabs/tabs.story.vue) for guidance.

This change will be part of the next release.
