### ISSUE TITLE
`ColorPickerProps` isn't accurate

### ISSUE THREAD

**Issue by sumicet** [chakra-ui/ark#1116]
### Description

When I use `ColorPicker`, I expect to get prop suggestions for `value`, `onChange`, etc, but I only get `children` and `key`.

Looks like it's an issue with the `ColorPickerProps` type which ends up looking like this:
```
type ColorPickerProps = {
    [x: string]: UseColorPickerProps;
    [x: number]: UseColorPickerProps;
    [x: symbol]: UseColorPickerProps;
    children?: ReactNode | ((props: ColorPickerContext) => ReactNode);
}
```

### Link to Reproduction

https://codesandbox.io/p/sandbox/eager-mahavira-zypj6n?file=%2Fsrc%2FApp.tsx%3A9%2C8-9%2C19

### Steps to reproduce

-

### Ark UI Version

0.7.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue Christina. Happy to say that we already have a fix available. https://github.com/chakra-ui/ark/pull/1057

Waiting for a new release of zag-js

**Comment by cschroeter** [comment]
@sumicet Please try `@ark-ui/react v0.7.2`
