### ISSUE TITLE
The date picker component cannot be reselected after the date is cleared.

### ISSUE THREAD

**Issue by duxphp** [chakra-ui/ark#1124]
### Description

date picker If you select a date directly and then clear the settings, you cannot set the date again.

### Link to Reproduction

https://codesandbox.io/p/sandbox/nice-dubinsky-hx3g2c

### Steps to reproduce

1、Use directly according to the example，add params "inline={true}"
2、After clicking on any date setting
3、Click the clear button
4、Click any date again

### Ark UI Version

0.7.2

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by anthonyespirat** [comment]
same issue with Select component, can't re-select the same value after reset/clear
