### ISSUE TITLE
Default props for toasts

### ISSUE THREAD

**Issue by jonathanwilke** [chakra-ui/ark#1135]
### Description

Hey friends, 

you are doing an amazing job with this library, so thank you very much first of all!

I yesterday tried to find out if there is a way to set default props for my toasts. Specifically for the placement it would be amazing to have, so I don't always have to pass that value manually.

### Proposed Solution or API

I remember there is a prop in the ToastProvider for ChakraUI where you can set default values. Would be nice to have something similar here too!

**Comment by cschroeter** [comment]
Default Toast options will be available with the next release: https://ark-ui.com/docs/react/components/toast#default-options
