### ISSUE TITLE
Expose ark factory function

### ISSUE THREAD

**Issue by arekrgw** [chakra-ui/ark#1152]
### Description

Would be awesome if we could import the ark factory function. We could use the asChild pattern with any element eg. div, wrapper elements

### Proposed Solution or API

Export ark factory function to be available for the developers.

**Comment by cschroeter** [comment]
Thanks for creating this issue. There is no objection on my end.

**Comment by cschroeter** [comment]
Done 4b07ff28ae786364ce1bc16bd33a7232684f208d

**Comment by charmbyte** [comment]
Is it possible to expose the ark factory function in Solid as well?
