### ISSUE TITLE
Add Styling guide for Panda CSS

### ISSUE THREAD

**Issue by segunadebayo** [chakra-ui/ark#1154]
### Description

It'll be great to extend the styling guide to include Panda CSS.
https://ark-ui.com/docs/react/overview/styling

### Proposed Solution or API

--

**Comment by cschroeter** [comment]
@DmacMcgreg we somewhat did that. Checkout park-ui.com

**Comment by DmacMcgreg** [comment]
Fantastic @cschroeter 
It's looking great so far!
You guys are doing fantastic work here

**Comment by segunadebayo** [comment]
I've set up an initial version of the content here [cc43500](https://github.com/chakra-ui/ark/commit/cc43500d2193460c2bcefad767719a5eb725adc9).

We'll improve it as we go to address more frameworks.
