### ISSUE TITLE
feat: add support for animation

### ISSUE THREAD

**Issue by DmacMcgreg** [chakra-ui/ark#1155]
### Description

It seems the dialog is quite limited right now.
First of all, how can it be animated? Since it just removes the entire element from the DOM without any delay.
Second, how would we close it with a function, like with Chakra?
There should be a function prop that can be called, otherwise the modal will close only when clicking the close button, which is not realistic.

### Proposed Solution or API
({ isOpen, close }) =>
...

<Button onClick={() =>{
await doSomeStuff....
close()
}) />

**Comment by DmacMcgreg** [comment]
For anyone wondering:

@keyframes slide-down {
  0% {
    opacity: 0;
    transform: translateY(-10px);
  }
  100% {
    opacity: 1;
    transform: translateY(0);
  }
}

.slide-down[data-part="content"] {
  border-radius: 5px;
}

.slide-down[data-part="content"],
.slide-down[data-reach-menu-items] {
  animation: slide-down 0.2s ease;
}

**Comment by cschroeter** [comment]
Thanks you for reporting this feature request. In fact we are just on the hunt to finalize the component API for animating and lazy mounting components. That's what we have at the moment:


```tsx
<Dialog>
  <DialogTrigger className={triggerClass()}>open</DialogTrigger>
  <Portal>
    <DialogPresence>
      <DialogOverlay  />
    </DialogPresence>
    <DialogPresence lazyMount={true|false}  unmountOnExit={true|false} onExitComplete={() => {}}>
      <DialogContent>
        <DialogTitle>Title</DialogTitle>
        <DialogDescription>
          Description
        </DialogDescription>
      </DialogContent>
    </DialogPresence>
  </Portal>
</Dialog>
```

This kind of component type (`DialogPresence`)  will be available for all disclosure type components like `Popover`, `Tabs` etc.

Type definition for reference:

```tsx
type PresenceProps = {
  /**
   * @default false
   */
  unmountOnExit: boolean

  /**
   * @default false
   */
  lazyMount: boolean // or  deferMount: boolean
}

**Comment by DmacMcgreg** [comment]
Fantastic @cschroeter  
Of course something like this would be on your mind already.
Kudos for getting panda and ark out there, I understand it was a bit of a race against the clock!

Looking forward to the wave of innovation that is about to happen with these two libraries!!

**Comment by cschroeter** [comment]
@DmacMcgreg https://ark-ui.com/docs/react/components/dialog checkout this animated example. We are going to roll out more examples in the next days.
