### ISSUE TITLE
Ark-UI doesn't play well with form libraries like React-Hook-Form

### ISSUE THREAD

**Issue by tzarger** [chakra-ui/ark#1159]
### Description

It seems things like Select only have a `defaultValue` and that requires to be in the shape of an `Option`... when you only need to value, it does not well play well when you use a library like react-hook-form and zod validation. Are you going to provide any examples like that?

### Proposed Solution or API

Have it expose a `value` property that is the value, not an Option.

**Comment by cschroeter** [comment]
You have two options to choose from:

**Use a hidden select**

```tsx
<Select>
  {({ selectedOption, hiddenSelectProps }) => (
    <>
      <select {...hiddenSelectProps} {...register("category")}>
        {selectData.map((option) => (
          <option key={option.key} value={option.key}>
            {option.label}
          </option>
        ))}
      </select>
      {/* <SelectTrigger ... etc. */}
    </>
  )}
</Select>
```

**Use the <Control />**
```tsx
const { control } = useForm();

return (
  <Controller
    name="Category"
    control={control}
    render={({ field }) => (
      <Select onChange={(e) => field.onChange(e?.value)}>
        {({ selectedOption }) => <>{/* <SelectTrigger ... etc. */}</>}
      </Select>
    )}
  />
);

**Comment by jgillich** [comment]
Is this example outdated? `onChange` is never called for me, and passing a function as children results in a confusing type error :thinking: 
![Screenshot from 2023-10-31 19-00-20](https://github.com/chakra-ui/ark/assets/347965/4cb95fff-65bd-4c0b-bbbe-8a1f1e8bc0e6)

**Comment by antiheronathan** [comment]
Was able to get it to work following the second pattern, although I found `onValueChange` to be what I needed instead of `onChange`

**Comment by QWu4xYV** [comment]
Was able to get it to work following the second pattern, although I found `onValueChange` to be what I needed instead of `onChange`

**Comment by cschroeter** [comment]
@QWu4xYV 

Thanks for pointing that out. I will update the docs to showcase how to integrate Ark UI components with popular form libraries.
