### ISSUE TITLE
proxyState is undefined

### ISSUE THREAD

**Issue by cschroeter** [chakra-ui/ark#1185]
### Discussed in https://github.com/chakra-ui/ark/discussions/1184

<div type='discussions-op-text'>

<sup>Originally posted by **zlever01** July 14, 2023</sup>
In Nextjs, when installing the ark-ui package I get this error: 

```
- error node_modules/@zag-js/react/node_modules/@zag-js/store/dist/proxy.mjs (234:0) @ snapshot
- error TypeError: proxyState is not iterable

```

When uninstalling ark-ui the error goes away. Any ideas on whats going on? </div>

**Comment by kgelpes** [comment]
Having the same issue. I believe it's because pandacss is requiring ark 0.7.2 and I have installed ark 0.9.0

**Comment by hmiller020414** [comment]
@kgelpes Did downgrading to ark 0.7.2 resolve your problem? I am facing the same issue now
