### ISSUE TITLE
asChild + Dynamic doesn't propagate props correctly

### ISSUE THREAD

**Issue by ceopaludetto** [chakra-ui/ark#1187]
### Description

When I create a custom component using asChild + Dynamic, only `children` prop is propagated to the `component` used in Dynamic, the other props are ignored.

### Link to Reproduction

https://codesandbox.io/p/sandbox/distracted-goodall-2g8kj7?file=%2Fsrc%2Froutes%2Findex.tsx%3A9%2C11

### Steps to reproduce

1. Create a custom component which encapsulates a Primitive(with asChild) with Dynamic, example:
```tsx
type ButtonProps<T extends ValidComponent> = DynamicProps<T>;

function Button<T extends ValidComponent>(props: ButtonProps<T>) {
  const [local, rest] = splitProps(props, ["children", "component"]);

  return (
    <Pressable asChild {...rest}>
      <Dynamic component={local.component ?? "button"}>
        {local.children}
      </Dynamic>
    </Pressable>
  );
}
```
2. Try to use the custom component with the `component` prop, example:
```tsx
import { A } from "solid-start"

<Button component={A} href="/">Index</Button>
```
3. Only the children prop is propagated to `A`, href is ignored and solid-start throws.

### Ark UI Version

0.8.1

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

### Browser

Arc 0.112.0 (40064) (Chromium Engine: 114.0.5735.198)

### Additional Information

I think the problem only occurs in SSR scenarios, I'm using solid-start

**Comment by cschroeter** [comment]
Thanks for creating this issue. I don't think this is possible to achieve and out of scope for now.
