### ISSUE TITLE
feat:Svelte package

### ISSUE THREAD

**Issue by Not-Jayden** [chakra-ui/ark#1190]
### Description

I'd love to be able to use Ark components in Svelte. Is there any interest in this being added to the project at this stage? I'd be happy to work on this in my free time if so.

### Proposed Solution or API

Essentially just implement the components as they are already specced in Svelte. Would use sveltekit and svelte2tsx for for creating the library with typescript support, similar to the structure of the [flowbite-svelte](https://github.com/themesberg/flowbite-svelte) library.

I would appreciate guidance on how I should go about contributing this change to the repo if it is desired as I suspect it might be a bit messy to begin with. I'd also be happy to just split it out into a separate ark-svelte repo to reduce the burden on maintainers, and it can be considered to be merged into this library at a later time in a more polished state.

**Comment by segunadebayo** [comment]
Hi @Not-Jayden,

We don't have plans to support Svelte for now. You can create a separate ark-svelte repo and share it here.

All components in Ark are based on the state machines in [zag.js](https://zagjs.com/). You need to figure out how to use zag.js in your Svelte library first.

Thanks for understanding.
