### ISSUE TITLE
`v-slot` in `ToastPlacements` and `ToastGroup` component not typed correctly

### ISSUE THREAD

**Issue by rifandani** [chakra-ui/ark#1193]
### Description

When I trying to get the slot props from `ToastPlacements` & `ToastGroup` component, I expected the props to be typed correctly, but instead I got the `any` type

### Link to Reproduction

https://github.com/rifandani/vue-arkui-repro

### Steps to reproduce

1. Open `AppToastProvider.vue` in `src/app/AppToastProvider.vue`
2. Hover over `placements` & `toasts` variable from `v-slot`

### Ark UI Version

0.8.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

Google Chrome Version 114.0.5735.199 (Official Build) (64-bit)

**Comment by Shyrro** [comment]
Thanks @rifandani for this, i will try to look into this asap.

**Comment by saideepesh000** [comment]
Hey @Shyrro @Omikorin. Can I pick this up?

**Comment by Omikorin** [comment]
Hi, yes! Any help would be appreciated.

**Comment by saideepesh000** [comment]
hey @Omikorin . I don't see `ToastPlacements `or `ToastGroup`  components in the codebase. I'm in the main branch. Any help would be appreciated

**Comment by Omikorin** [comment]
Ah, sorry. @saideepesh000 `Toast` component was revised and simplified (check [here](https://github.com/chakra-ui/ark/commit/800468c1540a104e1e70213535d6f324255086f8)). It is not released yet.

**Comment by saideepesh000** [comment]
Ohhk. Let me know how I can help. Want to contribute to this project.

**Comment by Omikorin** [comment]
> Ohhk. Let me know how I can help. Want to contribute to this project.

More detailed tests and help with the Vue part of components would be great. I messaged back to you on LinkedIn.

@rifandani a big update for Vue components is coming, so I'll lock this issue now. Please follow the updates.
