### ISSUE TITLE
[React] [Pressable] onClick in Jest environment doesn't work

### ISSUE THREAD

**Issue by mayteio** [chakra-ui/ark#1206]
### Description

When I pass an `onClick` prop to the `Pressable` component, I'd expect jest to be able to test this behaviour. Instead, it doesn't seem to forward the props as expected.

Passing `onPress` doesn't work either. I assume most people would use this as a `Button` and `onClick` should be supported.

Given component:
```tsx
import { forwardRef, PropsWithChildren } from "react";

import { Pressable } from "@ark-ui/react";

export const Button = forwardRef<
  HTMLButtonElement,
  PropsWithChildren<{ onClick: any }>
>(function Button(props, ref) {
  return <Pressable ref={ref} {...props} />;
});
```

and test:

```tsx
import userEvent from "@testing-library/user-event";
import { render, screen } from "@testing-library/react";
import { Button } from "./button";

describe("Button", () => {
  it("Should handle onClick as expected", async () => {
    const fn = jest.fn();
    render(<Button onPress={fn}>Click me</Button>);
    await userEvent.click(screen.getByText(/click me/i));
    expect(fn).toHaveBeenCalled();
  });
});
```

I get the following error:

```
 FAIL  src/button.test.tsx
  Button
    ✕ Should handle onClick as expected (99 ms)

  ● Button › Should handle onClick as expected

    expect(jest.fn()).toHaveBeenCalled()

    Expected number of calls: >= 1
    Received number of calls:    0

       8 |     render(<Button onPress={fn}>Click me</Button>);
       9 |     await userEvent.click(screen.getByText(/click me/i));
```

Same issue happens if I use `onPress`, changing the `Pressable` to `button` in `button.tsx` passes the test.

### Link to Reproduction

https://codesandbox.io/p/sandbox/vigilant-bush-x3xfzs?welcome=true

### Steps to reproduce

1. Open terminal
2. Run `npm test`
3. See failing test
4. Change `Pressable` to `button` html element in button.tsx
5. Re-run test, see pass

### Ark UI Version

0.8.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
Thank you for taking the time to create this issue. We have also stumbled across this problem.
As you can tell from the [docs](https://ark-ui.com/docs/react/components/pressable) the `Pressable` component just works fine. I'm not sure what event isn't dispatched in `JSDOM` or `happy-dom` that causes this issue.

However since the component works as expected in the browser I'm going to close the issue.
