### ISSUE TITLE
Unexpected MenuItem visibility when setting display: flex on MenuContent

### ISSUE THREAD

**Issue by dwzkit** [chakra-ui/ark#1213]
### Description

Hello Ark UI team,

I am using your headless UI library and I have encountered an issue regarding the visibility of MenuItems when changing the display style of MenuContent.

Here's my original working code:
```
<template>
  <Menu>
    <MenuTrigger>
      <button>Open menu</button>
    </MenuTrigger>
    <Teleport to="body">
      <MenuPositioner>
        <MenuContent>
          <MenuItem id="edit">Edit</MenuItem>
          <MenuItem id="delete">Delete</MenuItem>
          <MenuItem id="export">Export</MenuItem>
          <MenuItem id="duplicate">Duplicate</MenuItem>
        </MenuContent>
      </MenuPositioner>
    </Teleport>
  </Menu>
</template>
```
And the related CSS:
```
[data-scope='menu'][data-part='content'] {
  margin: 0;
  width: 160px;
  background-color: white;
  border-radius: 0.25rem;
  padding: 0.25rem;
  border: 1px solid lightgray;
  list-style-type: none;
}

```
With the above setup, the menu behaves as expected: the MenuItems are hidden until the Open menu button is clicked.

However, when I add display: flex; to the MenuContent style:
```
[data-scope='menu'][data-part='content'] {
  ...
  display: flex;
  ...
}
```
The MenuItems are always visible, regardless of whether the Open menu button has been clicked or not. I wanted to use display: flex to create a column layout for my MenuItems, but I am unsure why this affects the visibility of the MenuItems. I didn't find any related information in the documentation.

Could you kindly explain why this is happening, and suggest any potential solutions if I would like to keep the column layout?

Thank you for your assistance.

### Link to Reproduction

none

### Steps to reproduce

Here's my original working code:
```
<template>
  <Menu>
    <MenuTrigger>
      <button>Open menu</button>
    </MenuTrigger>
    <Teleport to="body">
      <MenuPositioner>
        <MenuContent>
          <MenuItem id="edit">Edit</MenuItem>
          <MenuItem id="delete">Delete</MenuItem>
          <MenuItem id="export">Export</MenuItem>
          <MenuItem id="duplicate">Duplicate</MenuItem>
        </MenuContent>
      </MenuPositioner>
    </Teleport>
  </Menu>
</template>
```
And the related CSS:
```
[data-scope='menu'][data-part='content'] {
  margin: 0;
  width: 160px;
  background-color: white;
  border-radius: 0.25rem;
  padding: 0.25rem;
  border: 1px solid lightgray;
  list-style-type: none;
}

```
With the above setup, the menu behaves as expected: the MenuItems are hidden until the Open menu button is clicked.

However, when I add display: flex; to the MenuContent style:
```
[data-scope='menu'][data-part='content'] {
  ...
  display: flex;
  ...
}
```
The MenuItems are always visible, regardless of whether the Open menu button has been clicked or not. I wanted to use display: flex to create a column layout for my MenuItems, but I am unsure why this affects the visibility of the MenuItems. I didn't find any related information in the documentation.

### Ark UI Version

0.5.3(vue@3.3.4)

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

**Comment by cschroeter** [comment]
@dwzkit Thanks for taking your time to create this issue.

The `MenuPositioner` as the name indicates is responsible for positioning the content of the menu.
The `MenuContent` holds the - well - content of the menu. If the menu is closed the content is hidden -> `display: none`
If you now force `display: flex` on the menu content - things will fall apart as you described in your issue.

Solultions:
a) Wrap your content:

```tsx
<MenuPositioner>
  <MenuContent>
    <div style={{display:"flex"}}> ...</div>
  </MenuContent>
</MenuPositoner>
```

b) Use CSS:
```tsx
<MenuPositioner>
  <MenuContent>
     ...
  </MenuContent>
</MenuPositoner>
```

```css
[data-scope='menu'][data-part='content']:not([hidden]) {
  display: flex;
}
```

Hope that helps.
