### ISSUE TITLE
[React][DatePicker] onChange handler is never called

### ISSUE THREAD

**Issue by vince-roy** [chakra-ui/ark#1225]
### Description

The DatePicker's `onChange` never seems to get called in React. For example, when opening the date picker and selecting a date, the `onFocusChange` event fires but not the `onChange` event.

Dependencies:
```
{
  "name": "next-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@ark-ui/react": "^0.9.0",
    "next": "^13.2.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
}
```

### Link to Reproduction

https://stackblitz.com/edit/stackblitz-starters-yg5p2d?file=pages%2Findex.js

### Steps to reproduce

1. Click the calendar icon 
2. Select a date
3. Notice that the focus change event is triggered, but not the general change event 
![image](https://github.com/chakra-ui/ark/assets/1381023/602446b7-d49f-4ed4-b4dd-7e49ddddfe08)

### Ark UI Version

0.9.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Firefox 115.0.2 and Safari 16.5.2

**Comment by segunadebayo** [comment]
This has been fixed in zag.js and will be part of the next release.

If issue persists after upgrading, we’ll reopen.

**Comment by vince-roy** [comment]
Thank you @segunadebayo
