### ISSUE TITLE
[React][Select] inconsistent select closing on blur/click outside with `lazyMount`/`unmountOnExit` options

### ISSUE THREAD

**Issue by pawelblaszczyk5** [chakra-ui/ark#1229]
### Description

Hello 👋
I've tried to update my components with lately added `lazyMount` and `unmountOnExit` options. I've spotted a few scenarios in `Select` component when closing behavior on blur/click outside isn't consistent.

1st scenario: with `unmountOnExit` and `lazyMount` option it isn't always closed while navigating with keyboard out of it
2nd scenario: with `unmountOnExit` and `lazyMount` option, it isn't closed on click outside with mouse

Both of these behaviors also occur without `unmountOnExit` option, but only on the first open/close cycle of each select instance. Removing the `lazyMount` option fix the behavior. It seems to be related to the existence of `SelectContent` inside of DOM.

### Link to Reproduction

https://codesandbox.io/p/sandbox/vigorous-tu-vvg6qh?file=%2Fsrc%2FApp.tsx%3A21%2C30

### Steps to reproduce

1st scenario:
1. Go to the reproduction URL
2. Focus and open select with keyboard
3. Use shift+tab to focus to the trigger
4. Now you can use tab to focus the next button in demo, the focus is trapped between the trigger and the next focusable element after the trigger. To close the select you need to click the trigger.

2nd scenario:
1. Go to the reproduction URL
2. Open select with mouse
3. Click outside
4. Observe select not being close, you can remove the `unmountOnExit` prop and observe correct behavior 

This also occurs on first cycle of open/close without `unmountOnExit` but with `lazyMount` option. You can remove the `unmountOnExit` option and refresh the sandbox to observe it.

### Ark UI Version

0.9.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Safari 17 and Chromium 115

### Additional Information

Btw. any plans for adding these options to `Menu` component?

**Comment by cschroeter** [comment]
Thanks for taking time to report this issue. Will have a look shortly.

**Comment by cschroeter** [comment]
Will be fixed with the next release: https://github.com/chakra-ui/zag/commit/eca3fb6b05f6701db677026658b4cbf2e14e9e33

**Comment by pawelblaszczyk5** [comment]
@cschroeter It still seems to occur after the latest update which seems to have linked zag changes - updated code sandbox https://codesandbox.io/p/sandbox/wonderful-herschel-jssy5r?file=%2Fsrc%2FApp.tsx%3A9%2C24
