### ISSUE TITLE
tooltip cannot be opened on mobile

### ISSUE THREAD

**Issue by lednhatkhanh** [chakra-ui/ark#1254]
### Description

Tooltip cannot be opened on mobile

### Link to Reproduction

https://ark-ui.com/docs/react/components/tooltip

### Steps to reproduce

1. Go to tooltip page on mobile
2. Cannot open it

### Ark UI Version

latest

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome latest

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. I guess there is no hover in mobile - but you can use a controlled approach like document here: https://ark-ui.com/docs/react/components/tooltip#controlled-tooltip

**Comment by oxygrimmkiv** [comment]
in mobile browser hover works if you tap the trigger, and closes if you tap other trigger on other tooltip, so it is the issue, it has to work as it works without frameworks
