### ISSUE TITLE
[React][Checkbox] The defaultChecked property is not working

### ISSUE THREAD

**Issue by fseglard** [chakra-ui/ark#1259]
### Description

When I provide the `defaultChecked` property on the `Checkbox` component, I expect the checkbox to be checked but that's not currently the case.

### Link to Reproduction

https://codesandbox.io/p/sandbox/xenodochial-firefly-w9k64y

### Steps to reproduce

1. Set the `defaultChecked` to `true` on the `Checkbox` component.
2. See that the checkbox is not checked.

### Ark UI Version

0.10.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome 115

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. Expect a fix for this tomorrow.

**Comment by fseglard** [comment]
Thanks @cschroeter! You're awesome 🔥

**Comment by cschroeter** [comment]
Fixed with https://github.com/chakra-ui/ark/commit/cc284523ad519734bb8f65f159166476b52a833e
