### ISSUE TITLE
Redesign `Select` and `Combobox` API

### ISSUE THREAD

**Issue by fseglard** [chakra-ui/ark#1269]
### Description

Hi there!

When using the `Select` component, the current API for defining the default selected value is:

- `defaultValue` => uncontrolled select
- `selectedOption` => controlled select

Both props have the same type `Option` which is an object taking a label and a value.

It does not make sense, as a consumer of the component, to re-specify the label of the selected value, IMHO.

### Proposed Solution or API

I think it would be better if we can have the same API of a native React select:

- `defaultValue` => uncontrolled select
- `value` => controlled select

With both these props accepting a `string` only corresponding to the current selected value. An example:

```tsx
<Select defaultValue="react">
  {({ selectedOption }) => (
    <>
      <SelectLabel>Framework</SelectLabel>
      <SelectTrigger>{selectedOption?.label ?? 'Select option'}</SelectTrigger>
      <Portal>
        <SelectPositioner>
          <SelectContent>
            <SelectOption value="react" label="React" /> // This option will be default selected
            <SelectOption value="solid" label="Solid" />
            <SelectOption value="vue" label="Vue" />
          </SelectContent>
        </SelectPositioner>
      </Portal>
    </>
  )}
</Select>
```

What do you think ?

**Comment by cschroeter** [comment]
Agree.

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue.

We've refined the API a bit to make it even more flexible.

```tsx
type SelectProps<T> = {
    items: T extends Iterable
    onChange: (item: T) => void
}

type SelectItemProps<T> = {
    key: keyof T | string
}
```

so you can just pass a string as you had in mind but also any other entity that make sense for you

**Comment by fseglard** [comment]
I think we have the same problematic on the `Combobox` component.

**Comment by gtonussi** [comment]
I also had a rough time using a validation schema for a Select component because the selectedOption on thus the value from onChange would always be a type Option instead of string.

**Comment by cschroeter** [comment]
This will be adressed in https://github.com/chakra-ui/zag/pull/826

**Comment by segunadebayo** [comment]
This is now completed and a new version of Ark will be rolled out pretty soon
