### ISSUE TITLE
[React][Slot] Slot component support

### ISSUE THREAD

**Issue by Flower-F** [chakra-ui/ark#1274]
### Description

Will ark-ui support Slot component in the future? I think it is important for users to make their own design system. Just like the [Radix UI](https://www.radix-ui.com/primitives/docs/utilities/slot#slot).

### Proposed Solution or API

```jsx
import { Slot } from '@ark-ui/react';

function Button({ asChild, ...props }) {
  const Comp = asChild ? Slot : 'button';
  return <Comp {...props} />;
}
```

**Comment by cschroeter** [comment]
Hey @Flower-F thanks for taking your time to create this issue.

Wouldn't be the ark factory fn perfect for that subscribed usecase? With the next release (~Monday) you can do the following:

```tsx
import { ark } from '@ark-ui/react'

export type ButtonProps = ComponentPropsWithoutRef<typeof ark.button>

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  (props, ref) => <ark.button {...props} ref={ref} />,
)

Button.displayName = 'Button'
```

For example in [Park UI](https://park-ui.com) (using Pandas' `styled`) I can now do something

```tsx
<Button size={{ base: 'xl', md: '2xl' }} asChild>
    <NextLink href="/docs">Get Started</NextLink>
</Button>
```

Which outputs:
```html
<a href="/" className="button button--variant_primary button--size_xl md:button--size_2xl">Get Started</a>
```

Let me know if that works for you.

**Comment by Flower-F** [comment]
> 

Oh my god. That's so cool! Thank you for your answers!
