### ISSUE TITLE
[React][Menu] The MenuItem component has wrong types

### ISSUE THREAD

**Issue by fseglard** [chakra-ui/ark#1283]
### Description

The `MenuItem` component renders a `div` ([source](https://github.com/chakra-ui/ark/blob/main/packages/react/src/menu/menu-item.tsx#L22)) with the a forwarded ref as `HTMLDivElement` ([source](https://github.com/chakra-ui/ark/blob/main/packages/react/src/menu/menu-item.tsx#L13)), but the props are defined to be extended from a `button` ([source](https://github.com/chakra-ui/ark/blob/main/packages/react/src/menu/menu-item.tsx#L11)) which trigger some TypeScript errors and optionnaly can lead to some `button` specific props being forwarded to the `div` element.

I don't know if the node element is intended to be a `div` or a `button`.

### Link to Reproduction

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnA3nAsigdgVwEkYUQAFKCMAZzgF84AzSkOAcgAEBDKAawFp8wAPRQUXAMYw2AbgBQoSLAzY8+ekxbtufQSLGTp8xdHhJUKgMIRwEXHhgUq1AOrAYACwj4YAJRSMADRwAKIANqQOACrIaAzMNuwGUrIKtsr+hsGYjNAA7jwAJv6MGgmsbMlGcnLmaJb41DA2OATEpE40ADxRcCgAHiS4hbThkbgwMahdXLiIAHzzcAC8cADyIO5d1rb2E52u7l4+JT3zwWzAhWxLAGQYcnBPcFcAXKptJOSUNADal9cALryOjyOQSOxND5EL4AOQgMBc0F4wFwAHMVkx8kVTgAJKJYAAyABFgAA3MYgBzBBpNFpqdrfZxdNiFck3eYACk56AkHmAYUKYlwwQAdOKwD9qHRgrkoAUoIUUMUAgBKFZLdCPZ5iGD4KC4OCc7XPZ5dVr4UWMjDi0WS5x0ea8-mC4V0LrCC1Wr5LYTCOBTFAAZQkUGAYHgKCglCgcA8UZQAEITXBVSC0zUIbgoRbGUi+KiMas5QqVYwuviiaSKREqRMaY1miBc18DiyAEY+Zq4Dnc50CoV4MUSqUyrHyorKkrq5aalO6-WG42m03mtTe0g2kcOp18gduj1exm+-0AQTCYTgaIgEEKydNGboaaAA

### Steps to reproduce

The issue is reproductible when you want to wrap the `MenuItem` component from Ark and use `forwardRef` from React. See the TypeScript playground provided for more informations.

### Ark UI Version

0.13.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome 115

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. Fixed with 11c45db49c6283001dca8eb3ba6606b15d479662
