### ISSUE TITLE
Range Slider track is gone

### ISSUE THREAD

**Issue by juliomuhlbauer** [chakra-ui/ark#1286]
### Description

When I go to the website and test in my project, the slider doesn´t appear.
I am using Park UI to style.

### Link to Reproduction

https://ark-ui.com/docs/react/components/range-slider

### Steps to reproduce

Go to site or test local with Park UI.

### Ark UI Version

0.13.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. There was an update for the range slider component. Please copy the new snippet.

https://park-ui.com/docs/overview/changelog
