### ISSUE TITLE
[Dialog] [React] Backdrop not showing

### ISSUE THREAD

**Issue by my-lalex** [chakra-ui/ark#1317]
### Description

When displaying a dialog with backdrop, a `aria-hidden` attribute set to `true` is added to the DOM element
When hiding the dialog, this attribute is removed, but the `hidden` attribute is set...

### Link to Reproduction

https://codesandbox.io/s/mystifying-kowalevski-s3fpmv?file=/src/App.tsx

### Steps to reproduce

Toggle the dialog visibility

<img width="242" alt="image" src="https://github.com/chakra-ui/ark/assets/67102921/54eeb9d9-9fa7-4615-9f9e-f4ee60faf091">

### Ark UI Version

0.13.1

### Framework

- [ ] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
Thanks for reporting this issue. In your code example you set `background: srgb(0, 0, 0, 0.5);`
To my knowledge `srgb` is an unknown value for background. If set to `rgb` it just works as expected.

**Comment by my-lalex** [comment]
My bad 😅
I often use color-mix in CSS, so I used the wrong keyword...
