### ISSUE TITLE
DatePicker onChange not being triggered on change

### ISSUE THREAD

**Issue by gtonussi** [chakra-ui/ark#1328]
### Description

I am trying to implement the DatePicker, but it seems that the Date picked is not triggering the value change.

If I add a state to the "value" prop and then a function to the "onChange" prop that will only set the state according to the value, and then create a useEffect that will console that state each time it changes, I expect it to console a value when I select one using the Calendar.

Instead nothing happens.

I tried the same simple implementation on a pure html input, and a Select component from the lib, and both acts as expected.

The Datepicker component is acting as it never triggers the value change.

In another application of mine, more complex than example repo, I am using React Hook Form to manage a form that should receive a value from the Datepicker. Every time I submit the form, the value from Datepicker is undefined, even though I chose one on Calendar.

### Link to Reproduction

https://github.com/gtonussi/ark-test/blob/main/src/app/page.tsx

### Steps to reproduce

1. Clone repo
2. Install all packages (npm install)
3. Run the repo (npm run dev)
4. Pick any date and search the console for the value
5. No value will be consoled

### Ark UI Version

0.13.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome 93

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. A fix will be in `0.15.0`
