### ISSUE TITLE
[Vue][ColorPicker] Component cannot be controlled

### ISSUE THREAD

**Issue by renatodeleao** [chakra-ui/ark#1348]
### Description

When I'm using the controlled version of `ColorPicker` (`v-model`) I expect that external changes to the `modelValue` to update the picker component parts accordingly with the new color value.

What's happening currently is that the component is not reacting to `modelValue` changes from outside.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-1sszcg?file=src%2FApp.vue

### Steps to reproduce

1. In the demo click the button with the label _"This should change color to green"_
1. Notice that none of the parts of the `ColorPicker` component reacts to this `modelValue` change and the color value highlight by the "parts" remains the old value (blue-ish) within the component.

### Ark UI Version

0.7.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

Irrelevant.

### Additional Information

1. The reproduction demo is copy pasted as is [from the documentation example](https://ark-ui.com/docs/vue/components/color-picker/usage), omitting some of the parts for brevity only.

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. Will be fixed within the next release.

https://github.com/chakra-ui/ark/assets/1846056/b2f0fb5a-177d-4bdc-af98-c6f84649206e
