### ISSUE TITLE
[Vue][Pagination] Cannot read properties of undefined (reading 'pages')

### ISSUE THREAD

**Issue by Melchyore** [chakra-ui/ark#1355]
### Description

Hello,

I'm trying to use the same code as from the example page of the Pagination component, however, I'm getting the following error:

`Cannot read properties of undefined (reading 'pages')`

Could somebody help me, please?

Thank you!

### Link to Reproduction

https://codesandbox.io/s/cool-dan-l2xzks

### Steps to reproduce

Go to the reproduction link and you'll see the error after loading.

### Ark UI Version

0.7.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

All browsers

### Additional Information

The same error happens in v 0.6.0

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. I just revised the pagination component.
Something like this should work. If not I will file a new release.

```vue
      <Pagination v-slot="{ pages }" :count="5000" :page-size="10" :sibling-count="2">
        <PaginationList>
          <PaginationPrevPageTrigger>Previous Page</PaginationPrevPageTrigger>
          <template v-for="(page, index) in pages">
            <PaginationPageTrigger v-if="page.type === 'page'" :key="page" :value="page.value">
              {{ page.value }}
            </PaginationPageTrigger>
            <PaginationEllipsis v-else :key="index" :index="index"> &#8230; </PaginationEllipsis>
          </template>
          <PaginationListItem>
            <PaginationNextPageTrigger>Next Page</PaginationNextPageTrigger>
          </PaginationListItem>
        </PaginationList>
      </Pagination>
 ```

**Comment by Melchyore** [comment]
Hey @cschroeter!

Thank you, it works like a charm! Unfortunately, I couldn't find anything about this on the docs when I was stuck, so I think it would be helpful for future references. 😁

**Comment by cschroeter** [comment]
For the 1.0 release the website will be updated to show more examples. Happy that it works for you.
