### ISSUE TITLE
Build error "'solid-js/web' does not provide an export named 'memo'"

### ISSUE THREAD

**Issue by alexvuka1** [chakra-ui/ark#1363]
### Description

The build was working on @ark-ui/solid version 0.9.0, but upgrading broke it.

![image](https://github.com/chakra-ui/ark/assets/23139322/f5487c72-064a-4882-9c5d-5bb9960b7e4f)

### Link to Reproduction

https://stackblitz.com/edit/github-sebcjd?file=src%2FBasicNumberInput.tsx

### Steps to reproduce

1. Go to the stackblitz
2. Check the console output

### Ark UI Version

0.10.1

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

**Comment by charmbyte** [comment]
I am also getting this error. Rolling back to 0.9 in my dependencies fixed the issue for now.

**Comment by charmbyte** [comment]
@alexvuka1 Were you able to figure this out?

**Comment by gtumedei** [comment]
This is possibly related to #1045, as the error is very similar and the [fix](https://github.com/chakra-ui/ark/issues/1045#issuecomment-1622114278) for that issue seems to have been reverted in 0.10 (in commit 877e0c4b1ef6488bcb221d1490193d0fdf1b1b40). Are there any implications in adding back `solid({ solid: { generate: 'ssr', hydratable: true } })` in `vite.config.mts`?

**Comment by ryoid** [comment]
> This is possibly related to #1045, as the error is very similar and the [fix](https://github.com/chakra-ui/ark/issues/1045#issuecomment-1622114278) for that issue seems to have been reverted in 0.10 (in commit [877e0c4](https://github.com/chakra-ui/ark/commit/877e0c4b1ef6488bcb221d1490193d0fdf1b1b40)). Are there any implications in adding back `solid({ solid: { generate: 'ssr', hydratable: true } })` in `vite.config.mts`?

Can confirm manually building and exporting the lib with the generate ssr config resolved the issue for me, not sure what's the implications. If there are some issues with the ssr build on browser, maybe 2 builds with [conditional exports](https://github.com/solidjs/solid/blob/063db14c4e69f411ac2c09f5044e2d262fa667b9/packages/solid/package.json#L127C6-L161) could help.

**Comment by cschroeter** [comment]
Setting `generate: 'ssr'` breaks Storybook.

A simple story like 
```
export const Foo = () => {
  return <h1>hello</h1>
}
```



will not render any output. I can try to  use `solid({ ssr: true })`
or if you have any example project in solid that works for ssr happy to adapt our build config

**Comment by cschroeter** [comment]
After spending 1-2h on that topic I somewhat understand the issue. I'm happy to add conditional export like `node` to our entrypoints. 

```json
"./carousel": {
  "types": "./carousel/index.d.ts",
  "node": "./dist/server/index.server.mjs",
  "import": "./carousel/index.mjs",
  "require": "./carousel/index.cjs"
},
```

But apparently that is not enough since [Solid Start](https://github.com/solidjs/solid-start) apparently also requires an additional `solid` export like explained in a community library here:

https://github.com/solidjs-community/tsup-preset-solid#usage-gotchas 

Since this is not documented on their official website or the SolidStart project, we will wait until we add support for this. Thanks for your understanding.

**Comment by jgillich** [comment]
As a newcomer to Solid and Ark, I'm a little confused here. Are you saying this is a problem that needs to be addressed in SolidStart? Or would it be possible to provide a separate build for SolidStart users? Thanks!

**Comment by apatrida** [comment]
@cschroeter some notes here from the Solid-Start team on this issue.
https://discord.com/channels/722131463138705510/910635844119982080/1166193851686469642

**Comment by cschroeter** [comment]
@alexvuka1 @apatrida  @jgillich @ryoid @charmbyte 

Please try `@ark-ui/solid v1.0.0-beta.2`

**Comment by jgillich** [comment]
Thank you very much, the issue appears to be resolved, but I'm running into an issue with SegmentGroup. This worked fine before (master from yesterday built with generate: ssr)

I have just the SegmentGroup sample code in a SolidStart route:

```
import { SegmentGroup } from "@ark-ui/solid";
import { Index } from "solid-js";

export default () => {
  const frameworks = ["React", "Solid", "Vue"];
  return (
    <>
      <SegmentGroup.Root>
        <SegmentGroup.Indicator />
        <Index each={frameworks}>
          {(framework) => (
            <SegmentGroup.Item value={framework()}>
              <SegmentGroup.ItemText>{framework()}</SegmentGroup.ItemText>
              <SegmentGroup.ItemControl />
            </SegmentGroup.Item>
          )}
        </Index>
      </SegmentGroup.Root>
    </>
  );
};
```
The inital page loads fine, but when you change anything and trigger a live reload, you get:

![Screenshot from 2023-10-24 18-09-11](https://github.com/chakra-ui/ark/assets/347965/886bfb0c-5844-4722-99bc-b50d9544e9bc)

In my route with some other stuff, the initial load works too, but the error pops up after a second or two without changing anything, so I'm guessing it's not actually a problem with live reload but rather any state update..

**Comment by cschroeter** [comment]
@jgillich 
Not sure. I tried this snippet in a freshly created solid-start app without any issues. Please verify your setup and open a new issue if the problem persist and provide an example app to follow along.



https://github.com/chakra-ui/ark/assets/1846056/ed82081d-5a9a-42de-a973-6abb87891651

**Comment by jgillich** [comment]
Ah I'm sorry, cause was ParkUI pulling in a different version of ark anatomy and zagjs and node somehow loading the wrong version in the wrong place :shrug:. Fix was simple:

```
npm i @ark-ui/anatomy@v1.0.0-beta.1
```
