### ISSUE TITLE
[Vue] [ColorPicker] `asChild` prop cannot be used in ColorPickerChannelInput

### ISSUE THREAD

**Issue by renatodeleao** [chakra-ui/ark#1370]
### Description

When using `asChild` prop in `ColorPickerChannelInput` to provide a custom input from my design system, an error is thrown even if I pass slot content that matches the required criteria:
>  - Provide a single child element so that we can forward the props onto that element.
> - Ensure the first child is an actual element instead of a raw text node or comment node.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-tizb6j?file=src%2FApp.vue

### Steps to reproduce

The demo will throw an error on the initial render, no further steps are required

### Ark UI Version

0.7.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser
N/A

### Additional Information

- It also throws an error when using a raw HTML `<input type="text">` instead of a custom component
<img width="1976" alt="Screenshot 2023-09-04 at 15 26 46" src="https://github.com/chakra-ui/ark/assets/5116633/6988efff-31cc-425a-a6e9-a1a9f6c71914">

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. Will be fixed within the next release.
