### ISSUE TITLE
SolidJS factory function still not working

### ISSUE THREAD

**Issue by charmbyte** [chakra-ui/ark#1382]
### Description

I wasn't sure if I should have replied to the previously closed issue or create a new one. Regardless, it seems that the `ark` factory function for SolidJS is still not correctly being exported.

### Proposed Solution or API

`export * from './factory'` in `index.ts`

**Comment by cschroeter** [comment]
Good catch. Resolved with [3e6a0ba](https://github.com/chakra-ui/ark/commit/3e6a0bab55964e5c2b6d610ab754f877b114e5fe)
