### ISSUE TITLE
[Tags Input] Why doesn't it appear the keyboard for mobile?

### ISSUE THREAD

**Issue by ojj1123** [chakra-ui/ark#1396]
### Description

When I did try to edit the tags in the mobile environment, I expected to pop up the keyboard. But It doesn't happen:
(In the desktop, It's working; you can edit the tags.)

https://github.com/chakra-ui/ark/assets/33178048/b22fb0d5-bb29-4825-a5b9-ec3ce55bff3d

### Link to Reproduction

https://ark-ui.com/docs/react/components/tags-input

### Steps to reproduce

1. Just Double click the tag you want to edit **in mobile**.
2. The keyboard is not appeared.

### Ark UI Version

@ark-ui/react@0.14.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Safari, Chrome

### Additional Information

I don't know it happens when using other framework(solid, vue). The documentation currently use `@ark-ui/react`.
https://github.com/chakra-ui/ark/blob/a813fa5ec9ef2b41f48fb8b53415f8abbbba7e0f/website/package.json#L13

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. After investigating it looks like this is an issue for iOS. We can not fix this on our end.
