### ISSUE TITLE
Flex properties interferres with menu toggle

### ISSUE THREAD

**Issue by codepath2019** [chakra-ui/ark#1397]
### Description

When using the `Menu` primitive, applying `display: flex` to the `MenuContent` causes the menu to always be visible even when the close action has been triggered either by clicking outside of the menu or by selecting a menu item. As a user, I expect that after applying flex properties to `MenuContent` that the the menu will maintain its ability to toggle visibility when close action is triggered. 

### Link to Reproduction

https://codesandbox.io/p/sandbox/dazzling-tdd-lqrzns?welcome=true

### Steps to reproduce

1. Go to the demo in the code sandbox
2. Click on the trigger to show the menu
3. Click on the trigger again to hide the menu
4. The menu does not go away

### Ark UI Version

0.14

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Firefox 117.0 64bit

**Comment by cschroeter** [comment]
Thanks for reporting this issue. You will find an explanation how to solve this problem here: https://github.com/chakra-ui/ark/issues/1213

You can also checkout the recipe for the Menu component here https://park-ui.com/docs/components/menu
