### ISSUE TITLE
[React][Select] inconsistent select closing on blur/click outside with lazyMount/unmountOnExit options

### ISSUE THREAD

**Issue by pawelblaszczyk5** [chakra-ui/ark#1402]
### Description

It's basically a copy of this issue, you can see my last comment over there https://github.com/chakra-ui/ark/issues/1229
I updated the reproduction to the latest version and I'm using Stackblitz instead of Codesandbox, as the second one isn't working properly for me

Hello 👋
I've tried to update my components with lately added `lazyMount` and `unmountOnExit` options. I've spotted a few scenarios in `Select` component when closing behavior on blur/click outside isn't consistent.

1st scenario: with `unmountOnExit` and `lazyMount` option it isn't always closed while navigating with keyboard out of it
2nd scenario: with `unmountOnExit` and `lazyMount` option, it isn't closed on click outside with mouse

Both of these behaviors also occur without `unmountOnExit` option, but only on the first open/close cycle of each select instance. Removing the `lazyMount` option fix the behavior. It seems to be related to the existence of `SelectContent` inside of DOM.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-z2zjd7?file=package.json

### Steps to reproduce

1st scenario:

1. Go to the reproduction URL
2. Focus and open select with keyboard
3. Use shift+tab to focus to the trigger
4. Now you can use tab to focus the next button in demo, the focus is trapped between the trigger and the next focusable element after the trigger. To close the select you need to click the trigger.

2nd scenario:

1. Go to the reproduction URL
2. Open select with mouse
3. Click outside
4. Observe select not being close, you can remove the unmountOnExit prop and observe correct behavior

This also occurs on first cycle of open/close without unmountOnExit but with lazyMount option. You can remove the unmountOnExit option and refresh the sandbox to observe it.

### Ark UI Version

0.14.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Safari 17 and Chromium 115

### Additional Information

Btw. any plans for adding these options to Menu component?

**Comment by codepath2019** [comment]
Hi @pawelblaszczyk5,

I only started to use ark-ui recently. I am seeing that you are building the `Select` component using the latest changes by using `SelectOption`. However, I do not see `SelectOption` as part of ark-ui's [documentation](https://ark-ui.com/docs/components/select#anatomy). I am curious as to how you went about discovering these newer features. It'd be difficult to know about these newer changes unless I read the source code. Thanks!

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. A fix will be available in the next release https://github.com/chakra-ui/ark/commit/fb7441d44127df0638bada4cdfebaacd489fbee1
