### ISSUE TITLE
Error in components of ark-ui with SolidJS

### ISSUE THREAD

**Issue by Tarek018** [chakra-ui/ark#1425]
### Description

When I use ark-ui with SolidJS, I import some components into the page and when I go to the browser, I don't find a component from ark-ui there, I find it without styleVersion 116.0.5845.188 (Official Build) (64-bit)
I can't find the component on the Ark-ui homepage.

### Link to Reproduction

https://github.com/Tarek018/Issue_SolidJS_with_Ark-ui

### Steps to reproduce

1- get clone the Repository 
2- open terminal in the folder
3- write in Terminal cd my-app
4- write in Terminal pnpm vite
5- open browser 
6- open the url 'http://localhost:3000/'

### Ark UI Version

0.11.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

### Browser

Chrome Version 116.0.5845.188

**Comment by segunadebayo** [comment]
Hi @Tarek018,

Ark UI is a headless library which means that you need to bring your own styles.

Check out park-ui.com for a styled examples of Ark that uses Panda CSS.

**Comment by Tarek018** [comment]
But how to use park-ui with SolidJS ??
