### ISSUE TITLE
menu positioned in top left corner of viewport in nuxt

### ISSUE THREAD

**Issue by stefanprobst** [chakra-ui/ark#1457]
### Description

menu opens in wrong position (top left corner of viewport) in nuxt application.

### Link to Reproduction

https://github.com/stefanprobst/issue-nuxt-ark-menu

### Steps to reproduce

1. Clonse reproduction repo https://github.com/stefanprobst/issue-nuxt-ark-menu
2. `pnpm install`
3. `pnpm run dev`
4. open <http://localhost:3000> and click on menu ("One" or "Two")
5. see the overlay open in the very top left corner of the viewport

### Ark UI Version

@ark-ui/vue 0.8.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

**Comment by segunadebayo** [comment]
This has now been fixed in the most recent versions. Here's a screen recording

https://github.com/chakra-ui/ark/assets/6916170/0900ed21-febe-43eb-83c2-4d5985844f9e
