### ISSUE TITLE
React NumberInput throw flushSync error when passing number / integer props to value + using format

### ISSUE THREAD

**Issue by mlazuardy** [chakra-ui/ark#1480]
### Description

So when im trying to pass a `value` props into NumberInput using integer /number plus using format props, it throw a flush sync error

### Link to Reproduction

https://codesandbox.io/s/solitary-bash-7fzrst?file=/src/App.js

### Steps to reproduce

check on the CSB link or copy this component

```
<NumberInput
        value={50000 as any}
        format={(value) => `$${value}`}
        parse={(value) => value.replace(/\$/g, "")}
      >
        <NumberInput.Input />
      </NumberInput>
```

### Ark UI Version

0.15.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. The `NumberInput` component has been revised and the issue should be solved with the next release.
