### ISSUE TITLE
Pagination Context missing types

### ISSUE THREAD

**Issue by juliomuhlbauer** [chakra-ui/ark#1501]
### Description

When rendering the function children in Pagination Root, it doesn't give me types.

### Link to Reproduction

"

### Steps to reproduce

![image](https://github.com/chakra-ui/ark/assets/53458125/816b3b4e-76f2-4f09-ae75-68edb3cbb632)

### Ark UI Version

0.15.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. Happy to say that this issue will be fixed within the next release:

<img width="418" alt="image" src="https://github.com/chakra-ui/ark/assets/1846056/416b4035-02da-4b92-95ec-f175aac716ee">
