### ISSUE TITLE
[React][RadioGroup] Scroll issue when clicking on a radio within a scrollable vertical list

### ISSUE THREAD

**Issue by fseglard** [chakra-ui/ark#1502]
### Description

Hi there!

When we have a scrollable vertical list of radio inputs, there is an issue when clicking on a radio input outside of the initial viewport (when scrolling down).

I notice that the issue appears because after clicking on a radio input, the browser get the focus on the hidden input related to the radio item you clicked, but all the hidden inputs are all positiong at the same place, at the top of the container, causing the browser to scroll top.

As a workaround, I'm using the `position: relative` CSS property on a manually added container on top of the `RadioGroup.Radio` so the related hidden input is correctly positioned, but that's not really ideal. You can check here the result: https://codesandbox.io/s/stupefied-hooks-mkfh3w?file=/src/App.js

### Link to Reproduction

https://codesandbox.io/s/tender-frog-wj37pc?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/tender-frog-wj37pc?file=/src/App.js
2. Scroll down the list
3. Click on a radio item
4. Notice the scroll top

### Ark UI Version

0.15.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome 117

**Comment by cschroeter** [comment]
@fseglard 

Thanks for taking your time to create this issue. I can confirm the issue and a fix will be available in the next release
