### ISSUE TITLE
[React][Carousel] handle drag/swipe gesture

### ISSUE THREAD

**Issue by FilipePfluck** [chakra-ui/ark#1520]
### Description

add support for changing the slides by dragging/swiping the carousel. 

### Proposed Solution or API

some apis already implement this behaviour: 
https://swiperjs.com/
https://formidable.com/open-source/nuka-carousel/
https://www.embla-carousel.com/

**Comment by cschroeter** [comment]
@FilipePfluck 

Thanks for creating this issue. We will track feautre request in canny 
https://ark-ui.canny.io/feature-requests/p/ability-to-slide-with-touch-on-carousels
