### ISSUE TITLE
[Combobox] Closed state animation is not working

### ISSUE THREAD

**Issue by samadadi** [chakra-ui/ark#1538]
### Description

Closed state animation is not working for combobox but it is working for select.

### Link to Reproduction

https://ark-ui.com/docs/components/combobox

### Steps to reproduce

Using just simple css animation is not working. As you can see in this css file there is a css animation for closed state but it is not working. I tested it locally too. [https://github.com/chakra-ui/ark/blob/main/packages/frameworks/react/src/combobox/combobox.css](https://github.com/chakra-ui/ark/blob/main/packages/frameworks/react/src/combobox/combobox.css)

### Ark UI Version

latest version

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by segunadebayo** [comment]
This is now resolved within Zag.js and will be fixed in the next release.

**Comment by samadadi** [comment]
Thanks. I am closing this issue.
