### ISSUE TITLE
Solid npm package not updated

### ISSUE THREAD

**Issue by charmbyte** [chakra-ui/ark#1544]
### Description

Just curious as to why the Solid (and Vue) npm package versions haven't been updated recently? The React package is at v0.15.0 while Solid is still at v0.11.0 despite a lot of the same updates. For example, I can't use SelectClearTrigger, SelectItemTexrt, etc. I can see that they are in the repo though.

### Proposed Solution or API

Bump the npm package version.

**Comment by cschroeter** [comment]
Thanks for taking your time to create this issue. We plan to ship release candidates for v1 later this week.
