### ISSUE TITLE
please help-->AutoComplete component seems to have a bug in safari

### ISSUE THREAD

**Issue by haikumedia** [chakra-ui/ark#1558]
### Description

Hello we have implemented an autocomplete component into our OTP feature.
When it auto completes on safari from a OTP it generates first two inputs in different color (yellow) as well as it takes a second input and populates it into remaining inputs effectively allowing for double digit inputs instead of single...
![otp2](https://github.com/chakra-ui/ark/assets/63272383/fec6d636-92ce-47bc-9d92-7137707e6f76)

### Link to Reproduction

https://customer.tryeatout.com/

### Steps to reproduce

PERFORM THIS TEST ON MOBILE SAFARI

go to: https://customer.tryeatout.com/
press `login with phone`
input your phone # and press `lets verify your phone`
redirects to opt verification page
autocomplete OTP that was sent to you.
you will see the auto completes issue. 

### Ark UI Version

0.1.0 (newest)

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

safari

**Comment by haikumedia** [comment]
here is the code we have implemented: "use client";
import {
  PinInput as ArkPinInput,
  PinInputControl,
  PinInputInput,
} from "@ark-ui/react";
import { classNames } from "../../../utils";
import { inputTheme } from "../../../themes";

type Details = { value: string[] };

interface Props {
  pinLength?: number;
  // class for root
  className?: string;
  inputClass?: string;
  onChange?: (value: string) => void;
  onFilled?: (value: string) => void;
  otp?: boolean;
}

export const PinInput: React.FC<Props> = ({
  pinLength = 6,
  className,
  inputClass,
  onChange,
  onFilled,
  otp,
}) => {
  const handleChange = (details: Details) => {
    const newValue = details.value?.filter((v) => !!v).join("");
    onChange?.(newValue);

    if (newValue.length === pinLength) {
      onFilled?.(newValue);
    }
  };

  return (
    <ArkPinInput asChild onChange={handleChange} otp={otp}>
      <PinInputControl className={className}>
        {Array.from({ length: pinLength }).map((v, index) => (
          <PinInputInput
            index={index}
            key={index}
            className={classNames(
              "text-center w-12 h-12 sm:w-14 sm:h-14 text-xl",
              inputTheme.bgColor.base,
              inputTheme.color,
              inputTheme.border,
              inputTheme.ring,
              "rounded-md",
              inputClass,
            )}
            placeholder=""
          />
        ))}
      </PinInputControl>
    </ArkPinInput>
  );
};

**Comment by cschroeter** [comment]
We applied a lot of changes. Please use Ark UI 1.0 and repoen an issue if the problem persist.
