### ISSUE TITLE
Props tab in Ark documentation is missing

### ISSUE THREAD

**Issue by juliomuhlbauer** [chakra-ui/ark#1575]
### Description

When I go to a components page, it was used to have a props that had all the APIs of the component.

### Link to Reproduction

https://ark-ui.com/docs/components/accordion

### Steps to reproduce

Go to the component page

### Ark UI Version

0.15.0

### Framework

- [X] React
- [X] Solid
- [X] Vue

**Comment by juliomuhlbauer** [comment]
Also, in dark mode, this section is with the wrong color: ![image](https://github.com/chakra-ui/ark/assets/53458125/b69b7c38-dd71-4ce6-b0e3-bc5dfbc07718)

**Comment by Omikorin** [comment]
> Also, in dark mode, this section is with the wrong color: ![image](https://user-images.githubusercontent.com/53458125/277352722-b69b7c38-dd71-4ce6-b0e3-bc5dfbc07718.png)

The color is fixed.

In the topic of API docs, @cschroeter are there some plans for that?

**Comment by cschroeter** [comment]
Done
