### ISSUE TITLE
Incorrect demo on doc of Popover component

### ISSUE THREAD

**Issue by Jokcy** [chakra-ui/ark#1578]
### Description

```jsx
const [isOpen, setIsOpen] = React.useState(false)
return (
  <>
    <button onClick={() => setIsOpen((open) => !open)}>Toggle Popover
    <Popover isOpen={isOpen}>{/*...*/}</Popover>
  </>
)
```

there is no `isOpen` prop for Popover component, it should be `open`.

And I test for the `open` prop, the Popover is not fully controlled by it, when user click the Trigger again the Popover fade away even when `open` is still true. 
If it is by design, then this is not a good demo because when user click the button again it will set `isOpen` to false which will not show the Popover, this will be consider a bug on user side.

### Link to Reproduction

https://ark-ui.com/docs/components/popover

### Steps to reproduce

It just a document bug

### Ark UI Version

0.15.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

chrome 118

**Comment by Omikorin** [comment]
Hi, thank you for your notice, I'll check this.

In the topic of docs, I revised all of it lately (you can check [here](https://github.com/chakra-ui/ark/pull/1573/files#diff-50c24f1fba18978effae7b19719a2c978cb781e4ff9f767d2c09ba119a0e0a47L38)), so every page will be up to date in a while.

**Comment by cschroeter** [comment]
@Jokcy 

With the release of Ark UI 1.0 the docs are now in sync.
