### ISSUE TITLE
[Text on Dark Mode]: I dont know how to name it but has a poor visibility on dark mode

### ISSUE THREAD

**Issue by ranielcsar** [chakra-ui/ark#1581]
### Description

when i was looking for some components in the docs, this happen:
![imageedit_2_5275876865](https://github.com/chakra-ui/ark/assets/20558676/a6ae9671-8a25-4fff-ab43-d37d7e69d22d)

this text is not looking nice on dark mode

ps: the red rect is my edit

### Link to Reproduction

no link

### Steps to reproduce

1. Go to "Avatar" or "Checkbox" at Components sections

### Ark UI Version

latest

### Framework

- [ ] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome 117

**Comment by cschroeter** [comment]
Good catch. Will push a fix shortly

**Comment by cschroeter** [comment]
D
