### ISSUE TITLE
[Menu] Items can not be tapped on mobile

### ISSUE THREAD

**Issue by ben-xD** [chakra-ui/ark#1600]
### Description

When I tap any menu items in [Menu](CleanShot 2023-10-29 at 10.51.39) they do not get tapped.

You can try the app in https://talkdash.orth.uk/
The menu code: https://github.com/ben-xD/talkdash/blob/f2884bb23a9d6634eed8f5cd866d0718e6cae268/frontend/src/App.tsx#L62-L139

### Link to Reproduction

https://github.com/ben-xD/talkdash/blob/f2884bb23a9d6634eed8f5cd866d0718e6cae268/frontend/src/App.tsx#L62-L139

### Steps to reproduce

![menu-taps](https://github.com/chakra-ui/ark/assets/24711048/2ec63dc9-1994-49ce-b20d-c12921dd5478)

- Visit https://talkdash.orth.uk/
- Try after turning on devtools and enabling mobile (Command + shift + M) or use on mobile
- Click/tap any menu item
![device toolbar](https://github.com/chakra-ui/ark/assets/24711048/6c643095-aae8-49d3-9724-f2ed5c91991a)

### Ark UI Version

0.11.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

### Browser

Chrome

### Additional Information

It doesn't affect Firefox "responsive design mode", but that's because they probably still send `onclick` events. It still affects firefox mobile.

**Comment by cschroeter** [comment]
@ben-xD 
Thanks for taking your time to create this issue. Will have a look shortly

**Comment by ben-xD** [comment]
Thanks for your response.

I wanted to add a bit more detail: when using nested menu, the nested menu can still open. However, it looks like the leaf nodes are the ones that cannot be clicked (only on mobile)

https://github.com/chakra-ui/ark/assets/24711048/3e914662-8a21-41e9-bd70-52afae9a642d

**Comment by segunadebayo** [comment]
Good catch @ben-xD,

I've gone ahead to fix this from within Zag.js [8e2b430](https://github.com/chakra-ui/zag/commit/8e2b43031cb9f81957fd9245b971606faa4979dd).

We'll publish an update shortly.

**Comment by ben-xD** [comment]
This doesn't seem to be fixed in the latest `@ark-ui/solid` version `1.1.0` https://www.npmjs.com/package/@ark-ui/solid

I have the same issue

**Comment by Southclaws** [comment]
I'm also running into this. Though I've noticed that `onSelect` works fine so I may just switch to using that instead of a listener for each individual `Menu.Item` - which seems to be the advised way according to the docs.

**Comment by Omikorin** [comment]
@ben-xD @Southclaws it's fixed in Zag https://github.com/chakra-ui/zag/commit/c7141e8b458c5ac95b39b38a3cd6dbd2987403c8

Will be in next Ark release
