### ISSUE TITLE
[Number Input] - Optional long press behavior

### ISSUE THREAD

**Issue by gperdomor** [chakra-ui/ark#1609]
### Description

Currently values are incremented or decremented with clicks and long press... Would be nice if we can disable the long press behavior in order to change the values one click at time

### Proposed Solution or API

No idea :(

**Comment by segunadebayo** [comment]
Hi @gperdomor,

Yes, you can disable this by passing `spinOnPress: false` to the number input component.

**Comment by gperdomor** [comment]
@segunadebayo Nice... Good to know... I'm very excited in this project because in the company where I'm working, we want to create a design system and we want to use this or the next chakra v3...
