### ISSUE TITLE
Input element within content doesn't invoke onChange

### ISSUE THREAD

**Issue by toptal-dave** [chakra-ui/ark#1612]
### Description

When I add an `input type="text"` field to a `Menu`'s `Portal`, I expect it to work just like any other input in React.  However, when I do, the `onChange` event never fires.

### Link to Reproduction

https://codesandbox.io/p/sandbox/great-leakey-9rdjtt

### Steps to reproduce

1. Create a `Menu` based on the documentation [here](https://ark-ui.com/docs/components/menu).
2. Add an `input` field within the `Portal` element (doesn't even matter where).
3. Add an `onChange` event and try to set state or `console.log` the change.

### Ark UI Version

0.15.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome 118.0.5993.117 & Firefox 118.0.2

### Additional Information

- Is there a better component to use for a menu that contains a search box?
- Should I use a ref somehow?
- onKeyDown works but that's a lot of work to get this to behave normally.

**Comment by Omikorin** [comment]
Similar error like #1600. There is a high possibility reason is the same.

**Comment by cschroeter** [comment]
@toptal-dave 

Thanks for taking your time to create that issue. I think it is more related to the `Menu` component that to the`Portal`. Since removing the portal still results in the same error. Will have a look shortly
