### ISSUE TITLE
[React] The handler for the onExitComplete event is never called

### ISSUE THREAD

**Issue by fseglard** [chakra-ui/ark#1627]
### Description

Hi!

I'm not really sure if this is a bug or if I don't understand how it's supposed to be used but I can't seem to get the `onExitComplete` property to work. The handler defined within this props is never called.

It's related to the `Presence` component and the issue occurs in all components that use it: Dialog, Popover, etc.

### Link to Reproduction

https://codesandbox.io/s/awesome-bogdan-ctsm8r?file=/src/Dialog.tsx

### Steps to reproduce

1. Open the dialog by clicking on the button
2. Close the dialog
3. Check the console: there is no log

### Ark UI Version

0.15.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome 118

**Comment by Omikorin** [comment]
Hi! Thank you for your notice. The `onExitComplete` invoke is fixed in chakra-ui/zag#1002 and it will be released soon.

About your code, there is a working example:
```tsx
  <Dialog.Root
    lazyMount
    unmountOnExit
    onExitComplete={() => console.log('onExitComplete invoked')}
  >
    {/* ... */}
  </Dialog.Root>
```

It seems docs are outdated here, you should use the `Root` part for mentioned props.
