### ISSUE TITLE
Several Component don't work as described (DatePicker, Pin, Combobox, Dialog)

### ISSUE THREAD

**Issue by EfstathiadisD** [chakra-ui/ark#1634]
### Description

When I am using the Docs for several components, I expect to see the Component as described on the Docs, but I see several issues:

- I am using Pin and I expect `onValueCompleted` to be a prop in one of the Compound Components but it isn't working. (Link to Stackblitz)
- I am using the DatePicker and several Compound Elements aren't there. (DatePicker.View, DatePicker.Label, ViewControl and more)
- I am using the DatePicker and the renderProp section are throwing the error. (`Type '(api: any) => Element' is not assignable to type 'ReactNode'.ts(2322)`).

Both the Dialog and Combobox are having similar issues.

### Link to Reproduction

https://stackblitz.com/edit/stackblitz-starters-jdr8yt?description=React%20%20%20TypeScript%20starter%20project&file=src%2FApp.tsx&title=React%20Starter

### Steps to reproduce

1. Go to the Stackblitz
2. And use the Pin
3. You will not see anything logged

### Ark UI Version

1.0.0-beta-4, 0.15.0, 0.14.0, 0.12.0, 0.10.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome Latest, Firefox Latest

### Additional Information

It seems that several components Docs and their TS Definitions have diverged quite a bit. On top of that, the Docs need a lot of work since `weekDays` `weeks`, `perMonthsGrid` isn't available anymore. Same for the Pin and Dialog. Stuff are missing.

I weird thing is, I see instances of the Public API in the code, but it is not working as the Docs suggest.

**Comment by segunadebayo** [comment]
Hi @EfstathiadisD,

The docs currently reflects the v1-beta code, if you swap out the version to “beta” in your package.json, it should work as expected.

We’re working to get the v1 release out in a few days.

Thanks for understanding

**Comment by EfstathiadisD** [comment]
Cool. I think the `beta.4` has an issue as well. `beta.3` worked. Thanks!
