### ISSUE TITLE
Enable using ColorPicker with both RGBA and HSL values, or return HEX value with onChange's details.

### ISSUE THREAD

**Issue by Infektid782** [chakra-ui/ark#1649]
### Description

According to documentation, it should be possible, to achieve the following feature:
<img width="675" alt="image" src="https://github.com/chakra-ui/ark/assets/79762383/ca0a5510-0f4d-443b-a1d2-e369271af88b">

### Proposed Solution or API

In our experience, if we provide RGBA value, we can only use the ChannelInputs without ColorPickerArea and ColorPickerChannelSliderTrack and if we provide HSL value, then it is the other way around. Providing both values, the component will only use the one we provide first. Examples for values:

'rgba(10.5, 10, 10, 1)' - Only ChannelInputs with channel red, green, blue and alpha are working.
'hsl(10, 10.5%, 10%)' - Only ColorPickerArea and ColorPickerChannelSliderTrack are working.
'hsl(10, 10.5%, 10%), rgba(10.5, 10, 10, 1)' - Only ColorPickerArea and ColorPickerChannelSliderTrack are working. Errors:
Unknown color channel: red
Unknown color channel: green
Unknown color channel: blue
'rgba(10.5, 10, 10, 1), hsl(10, 10.5%, 10%)' - Only ChannelInputs with channel red, green, blue and alpha are working. Errors:
Unknown color channel: hue
Unknown color channel: saturation
Unknown color channel: lightness

We've noticed, that the conversion from and to HEX colors works with both RGBA and HSL values, but the details.value does not contain it. Temporary solution would be to provide the HEX value, when onChange is called, as it can act as a bridge between HSL and RGBA, so the ChannelInputs with channel red, green, blue and alpha could be replaced with simple controlled NumberInputs outside the scope of ColorPicker. 
The ideal, long term solution in our opinion is to replace the string value with HEX or RGB props, and do the HSL conversion inside the ColorPicker, so every channel is working at all times.

**Comment by cschroeter** [comment]
@Infektid782 thanks for taking your time to create the issue.

Depending on your current color format, you will have diffent channels available https://github.com/chakra-ui/ark/commit/0a5af02323ed68b85ed36ef7a300e8c2d29312ce

```tsx
<ColorPicker.View format="rgba">
  <ColorPicker.ChannelInput channel="hex" />
  <ColorPicker.ChannelInput channel="alpha" />
</ColorPicker.View>
```

or in HSL

```tsx
 <ColorPicker.View format="hsl">
   <ColorPicker.ChannelInput channel="hue" />
  <ColorPicker.ChannelInput channel="saturation" />
  <ColorPicker.ChannelInput channel="lightness" />
</ColorPicker.View>
```

It is somewhat similar to the `DatePicker` api where you can drafte different views for different modes:

```tsx
<DatePicker.View view="day">{/* All the things in Day View */}</DatePicker.View/>
  ```

**Comment by Infektid782** [comment]
Thank you for your response! 
I am currently working on a sandbox project to better illustrate the issue I mentioned. It will be completed soon.

**Comment by segunadebayo** [comment]
This is currently addressed in Zag.js, and should be fixed in the next version

**Comment by Infektid782** [comment]
Sorry for the delayed response and not delivering the sandbox project as promised. I've been swamped with a ton of work lately.

I'm glad to hear that a fix is on the way for the issue we've been dealing with. I'll definitely check it out when it's live.

Feel free to close this discussion when the fix is done.

**Comment by cschroeter** [comment]
@Infektid782 

Please try out the latest ColorPicker in verison `v1.1.0` when available and open a new ticket if the issue persist.
