### ISSUE TITLE
createToaster don't exist in @ark-ui/react

### ISSUE THREAD

**Issue by matto49** [chakra-ui/ark#1653]
### Description

@ark-ui/react don't export  createToaster  function

### Link to Reproduction

https://codesandbox.io/s/createtoaster-pwwmkg

### Steps to reproduce

err happen

### Ark UI Version

"@ark-ui/react": "^0.15.0",

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by easylogic** [comment]
hi @matto49 

The ARK official site is using version "1.0.0-beta.4", so the documentation and the final npm library version don't match.

You can update the version 

```
pnpm update -r "@ark-ui/react@1.0.0-beta.4"
```

**Comment by cschroeter** [comment]
@matto49 

As explained by @easylogic please use `@ark-ui/react@1.0.0-beta.4` or later
