### ISSUE TITLE
[Accordion] onChange not triggering when closing an item when the accordion has `collapsible` or `multiple`

### ISSUE THREAD

**Issue by FilipePfluck** [chakra-ui/ark#1656]
### Description

I am using a controlled accordion so I can set custom animations. The onChange function does not seem to be triggering when I close one item (when it has collapsible or multiple, so I can close one item without opening another one)

### Link to Reproduction

https://github.com/FilipePfluck/PlucoUI

### Steps to reproduce

1. clone the repo
2. start storybook server
3. Check the accordion component and see the console.log

### Ark UI Version

0.15

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by FilipePfluck** [comment]
after investigating further I figured it only happen if you have `multiple`. If you have `collapsible` but not `multiple`, it works fine.

**Comment by segunadebayo** [comment]
Good catch @FilipePfluck.

I just fixed this in Zag.js [e433b3e](https://github.com/chakra-ui/zag/commit/e433b3ee5b49a1099b8be2df99a4a5056fc1ecfd). We'll publish a new release pretty soon
