### ISSUE TITLE
[React][Menu] Presence is not working on the positioner component

### ISSUE THREAD

**Issue by fseglard** [chakra-ui/ark#1660]
### Description

Hi!

The `Menu.Positioner` component is always mounted even if we set the `lazyMount` property to `true` on the `Menu.Root` component.

If we look at the [source code](https://github.com/chakra-ui/ark/blob/main/packages/frameworks/react/src/menu/menu-positioner.tsx), we can see that the presence logic is missing:

```ts
const presenceApi = usePresenceContext()

if (presenceApi.isUnmounted) {
  return null
}
```

### Link to Reproduction

https://codesandbox.io/s/purple-feather-gwcqsw?file=/src/Menu.tsx

### Steps to reproduce

1. Look at the devtools
2. Check the positioner element in the DOM: it's mounted

### Ark UI Version

1.0.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome 119

**Comment by cschroeter** [comment]
A fix will be availabe in 1.0.1
