### ISSUE TITLE
[React][Combobox] The content is not properly positioned when setting the lazyMount property

### ISSUE THREAD

**Issue by fseglard** [chakra-ui/ark#1662]
### Description

Hi,

When setting the `lazyMount` to the `Combobox` component, the `Combobox.Positioner` is not positioned properly. If I remove the property, everything looks good.

### Link to Reproduction

https://codesandbox.io/s/competent-hill-9cn54h?file=/src/App.js

### Steps to reproduce

1. Click on the working combobox
2. The content is properly positioned
3. Click on the not working combobox
4. The content is not properly positioned

### Ark UI Version

1.0.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome 119

**Comment by segunadebayo** [comment]
This has been fixed in Zag.js, we’ll publish a new version shortly
