### ISSUE TITLE
[React][Dialog] The close animation does not work

### ISSUE THREAD

**Issue by fseglard** [chakra-ui/ark#1663]
### Description

Hi,

The close animation on the `Dialog` component does not work anymore.
It should be related to the Presence API as the DOM nodes are removed before the close animation end.

The issue occurs both with and without lazy mounting.

### Link to Reproduction

https://codesandbox.io/s/festive-smoke-zn3w2n?file=/src/App.js

### Steps to reproduce

1. Click on the buttons to open the dialogs
2. When closing any of the dialogs, the close animation is not working

### Ark UI Version

1.0.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome 119

**Comment by cschroeter** [comment]
Issue will be fixed with `1.0.1`
