### ISSUE TITLE
[React][Checkbox] Weird behavior in unit tests

### ISSUE THREAD

**Issue by fseglard** [chakra-ui/ark#1664]
### Description

Hi,

I'm not able to unit test correctly the `Checkbox` component for the checked/unchecked state.

When I test only the checked state, the test is passing, but when I add a second click to test the unchecked state, the test is failing weirdly.

### Link to Reproduction

https://codesandbox.io/s/festive-smoke-zn3w2n?file=/src/Checkbox.test.tsx

### Steps to reproduce

1. Run the tests
2. The test for the checked state only is passing
3. The test for the checked/unchecked states is not passing

### Ark UI Version

1.0.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome 119

### Additional Information

I've tried older versions of ArkUI (0.15.0) and the issue is occuring too.

**Comment by cschroeter** [comment]
@fseglard 

Thanks for taking your time to create this issue. We will look into this issue shortly.

**Comment by cschroeter** [comment]
Maybe related: https://github.com/chakra-ui/ark/issues/1618

**Comment by cschroeter** [comment]
```jsx
it('should invoke onCheckedChange', async () => {
    const onCheckedChange = vi.fn()
    render(<ComponentUnderTest onCheckedChange={onCheckedChange} />)

    fireEvent.click(screen.getByRole('checkbox'))
    waitFor(() => expect(onCheckedChange).toHaveBeenCalledWith({ checked: true }))

    fireEvent.click(screen.getByRole('checkbox'))
    waitFor(() => expect(onCheckedChange).toHaveBeenCalledWith({ checked: false }))
  })
  ```
  
If added some test that in React for Checkbox.
