### ISSUE TITLE
[React] [Toast] Duplicate Key Warning on Multiple Toast Creation

### ISSUE THREAD

**Issue by damzobridge** [chakra-ui/ark#1699]
### Description

When triggering multiple toasts in Ark UI by clicking a button, I expected each toast to appear without issue. Although the toasts show up, I receive a console warning about duplicate keys.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/sandbox/ark-ui-toast-bug-forked-msml7h

### Steps to Reproduce

1. Integrate the `Basic Example` from the [[ark ui documentaion](https://ark-ui.com/docs/components/toast)](https://ark-ui.com/docs/components/toast) into a Next.js 14 project
2. Render the component on any page.
3. Click the 'Toast' button multiple times quickly.
4. Observe the error in the browser's developer console.

### Ark UI Version

1.0.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome

### Additional Information

Here’s the warning that is logged to the console:

"Warning: Encountered two children with the same key, `toaster`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version."

**Comment by cschroeter** [comment]
@damzobridge 

Thanks for taking your time to report this issue. A fix will be availabe in the next release.
