### ISSUE TITLE
[Menu] using arrow keys on Submenus affect the Menu

### ISSUE THREAD

**Issue by raminrez** [chakra-ui/ark#1706]
### Description

We expect it not to change the selected menu style of the parent. 

### Link to Reproduction (or Detailed Explanation)

https://ark-ui.com/docs/components/menu

### Steps to Reproduce

1. Go to [Menu Page](https://ark-ui.com/docs/components/menu)
2. Click Menu to open
3. use arrow keys to navigate
4. go to submenu
5. try to use the up and down arrow keys
6. you will see the problem

### Ark UI Version

1.0.1

### Framework

- [ ] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome, Brabe

### Additional Information

https://github.com/chakra-ui/ark/assets/7345325/95c1ab71-a5f4-4deb-ad08-1a79ad201eae

_No response_

**Comment by Omikorin** [comment]
Hi! I appreciate the notice. I've checked this problem in Zag and it seems it's the issue with Ark UI.
We'll look into that soon!

**Comment by raminrez** [comment]
> On the other hand, we cannot simply use `Portal` because of lazy mounting issues.
I understand, so what is the best approach to handle the problem?

is it the responsibility of ZagJS to manage?

**Comment by Omikorin** [comment]
I think it's fine to use this method for now.

Let's wait for @cschroeter response. You revised the presence and menu lately, so you'll know better.

**Comment by cschroeter** [comment]
@raminrez 
Nexted Menus should be portalled. I will updated the docs accordingly. Thanks for creating the issue
