### ISSUE TITLE
404 Contribution Guidelines not found

### ISSUE THREAD

**Issue by MathurAditya724** [chakra-ui/ark#1719]
### Description

- [ ] The link on the `README.md` for contribution guidelines returns 404
- [ ] There is no `CONTRIBUTING.md` file in the repo.

### Link to Reproduction (or Detailed Explanation)

https://github.com/chakra-ui/ark/blob/main/CONTRIBUTING.md

### Steps to Reproduce

This is the line in `README.md` - https://github.com/chakra-ui/ark/blob/5b1b0d50e8b192c0a0df3d26f3c1483476fbbb27/README.md?plain=1#L63

### Ark UI Version

1.0.1

### Framework

- [ ] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
@MathurAditya724 

Thanks for pointing out the missing `CONTRIBUTING.md`. I've added a base version. Feel free to contribute. Any help is appreciated
