### ISSUE TITLE
Number Input component doesn't accept a children function

### ISSUE THREAD

**Issue by juliomuhlbauer** [chakra-ui/ark#1734]
### Description

When I try to wrap the children of the Root of the Number Input component with a function, it doesn't render and don't give me types on the context.

![image](https://github.com/chakra-ui/ark/assets/53458125/bdfdca09-0564-463c-be25-c2ce00b6a94c)

### Link to Reproduction (or Detailed Explanation)

Steps below

### Steps to Reproduce

Wrap the children of a Root Number Input with a function

### Ark UI Version

1.0.1

### Framework

- [X] React
- [x] Solid
- [ ] Vue

**Comment by juliomuhlbauer** [comment]
Also, it could be added an stories with this example in the docs

**Comment by Omikorin** [comment]
Thank you. It will be added in the next release.
