### ISSUE TITLE
docs: Multiple Vue components examples disabled

### ISSUE THREAD

**Issue by polarathene** [chakra-ui/ark#1736]
### Description

[Vue Components](https://github.com/chakra-ui/ark/tree/main/packages/frameworks/vue/src/) with stories that presently lack an equivalent [`.stories.json` config](https://github.com/chakra-ui/ark/tree/main/packages/website/src/content/stories/vue) for website docs:

- checkbox
- dialog
- environment
- menu
- pin-input (_`.stories.vue` is not located under `stories/`_)
- popover
- rating-group

Presently this causes the docs page of a component to have Vue grayed out (eg: [Popover](https://ark-ui.com/docs/components/popover)), which I've found has misled some devs into the belief the component is not supported for Vue, rather than just lacking the Vue example.

### Link to Reproduction (or Detailed Explanation)

https://ark-ui.com/docs/components/popover

### Steps to Reproduce

1. Visit https://ark-ui.com/docs/components/popover
2. Notice all examples have a grayed out Vue tab
3. Stories are defined at component source: https://github.com/chakra-ui/ark/tree/main/packages/frameworks/vue/src/
4. Missing related config for web docs: https://github.com/chakra-ui/ark/tree/main/packages/website/src/content/stories/vue

### Ark UI Version

0.8.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

Chrome

### Additional Information

![image](https://github.com/chakra-ui/ark/assets/5098581/a26b0d94-f73f-4079-9f15-fa34afda1e10)

### Minor issue encountered

Additionally encountered prior doc links to components from Sep 2023 have become 404 due to docs now unifying frameworks into single pages, but did not add redirects for the transition:
- Old: https://ark-ui.com/docs/vue/components/popover
- New: https://ark-ui.com/docs/components/popover

https://ark-ui.com/docs/components and https://ark-ui.com/docs likewise 404 and should probably redirect to an appropriate page instead.

**Comment by cschroeter** [comment]
@polarathene 

Thanks for pointing out the missing documentation parts for Vue.js. Unfortunately we don't have active maintainers for Vue. Feel free to contribute and update the missing Stories. Any help is appreciated.

**Comment by polarathene** [comment]
> Unfortunately we don't have many active maintainers for Vue.
> Feel free to contribute and update the missing Stories. Any help is appreciated.

That's ok I understand 👍 

I'm not a Vue dev myself, just thought I'd bring it to your attention. Was closing the issue intentional?

An alternative is to better communicate in docs that the component is supported / implemented with Vue, just lacking a story example? That was the main reason for raising the issue, since I encountered devs getting the impression that Vue is not supported by Ark.

If the Vue support is likely to stagnate due to lack of maintainers, it may be better to not display any support for Vue going forward? This issue otherwise provides visibility to interested Vue devs 🤷‍♂️

**Comment by cschroeter** [comment]
> Was closing the issue intentional?

Yes for the reasond that we try to avoid potentially long-lasting collection tickets, so an issue stays actionable and can be closed with a single PR. Feel free to create issue on per component basis.

> An alternative is to better communicate in docs that the component is supported / implemented with Vue, just lacking a story example?

Yes, we technically could. For example enable all tabs and just show a message that this demo is not yet available for the given framework. However this makes it harder to spot this because now we have to click through every single tab to spot unimplemented examples.

> If the Vue support is likely to stagnate due to lack of maintainers, it may be better to not display any support for Vue going forward? 

Why should we. The lib works its just missing a few examples.

**Comment by polarathene** [comment]
> For example enable all tabs and just show a message that this demo is not yet available for the given framework.

That's roughly what you get already when the button isn't disabled and the story is missing.

When investigating it myself, I had to go into dev-tools to inspect the tab, remove the buttons disabled attribute, ~~and possibly find and adjust some CSS to interact with the button~~ and get that failure message about missing story.

![image](https://github.com/chakra-ui/ark/assets/5098581/5bd1d570-cbf6-4feb-8ba9-3b4731fd15d1)

Only then did I look up the docs source regarding stories config for components 😅 

### UX - Missing example vs Unsupported by framework

> However this makes it harder to spot this because now we have to click through every single tab to spot unimplemented examples.

You could have a tooltip for the disabled tab to convey that? (_the reader only needs to see it the first time to understand what the disabled state actually means_)

Alternatively, the button could be enabled but some additional visual context to convey at a glance it's missing support.

The main UX issue with the current disabled approach, is the tab is the only indication in the docs IIRC to the reader that the component is supported for the framework, where the disabled state was inferred as "unsupported by the framework" rather than "missing example".

This was probably less of a misunderstanding when the docs previously had explicit framework subpaths in the URL (_which now 404 if revisited_).

Inline context is probably better, but I guess an earlier page (_since there is no top-level `components` page_), like the [Introduction](https://ark-ui.com/docs/overview/introduction) page could convey that all documented components are supported by the frameworks listed, but if a tab is disabled it's just missing an example of how to use the component?

---

### Maintenance

> Why should we. The lib works its just missing a few examples.

I was under the impression that it was no longer seeing maintenance / development. So new components would not have a Vue equivalent, or any updates that may land for other frameworks?

If it's not going to cause you any issues / friction, no worries 👍
