### ISSUE TITLE
Updating state with useSearchParams on Select component causes multiple reenders

### ISSUE THREAD

**Issue by juliomuhlbauer** [chakra-ui/ark#1738]
### Description

When using Nexjjs's useSearchParams hook with Select component causes multiple reenders.

### Link to Reproduction (or Detailed Explanation)

https://use-search-param-ark.vercel.app/search-param

### Steps to Reproduce

1. Go to the reproduction
2. Open console
3. Change the select value

### Ark UI Version

1.0.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome

### Additional Information

GitHub Repo: https://github.com/juliomuhlbauer/use-search-param-ark

**Comment by juliomuhlbauer** [comment]
https://github.com/chakra-ui/ark/assets/53458125/1473c7f6-570c-4c97-a581-3bf8f001e180

**Comment by juliomuhlbauer** [comment]
Also, it would be cool seeing an example of integrating Nextjs with url on state

**Comment by segunadebayo** [comment]
I looked into this deeply today and found that it's a Next.js bug 

https://github.com/vercel/next.js/issues/43691
https://github.com/vercel/next.js/issues/49881

In the meantime, you can use the good'ol `history.pushState`

```jsx
const handleChange = (details) => {
        const params = new URLSearchParams(searchParams)
        params.set('city', value[0])
       // workaround until Next.js fix
        window.history.pushState(
          {},
          '',
          `/search-param?${params.toString()}`
         )
     }
}
```

**Comment by juliomuhlbauer** [comment]
But how do I read from the url with Nextjs? It would cause hydration problems

**Comment by juliomuhlbauer** [comment]
I opened an issue on Nextjs: https://github.com/vercel/next.js/issues/58684
