### ISSUE TITLE
File Upload not respecting files property

### ISSUE THREAD

**Issue by juliomuhlbauer** [chakra-ui/ark#1778]
### Description

When I set a hardcoded value to the File Upload component (because I want to control it) it doesn't respect it.

### Link to Reproduction (or Detailed Explanation)

.

### Steps to Reproduce

Set a custom value to files and try to upload something.
It shouldn't be able to change the value, except if changes the value I set.

### Ark UI Version

1.1.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
@juliomuhlbauer,

Thank you for bringing this (and many other issues) to our attention. Your input is invaluable in the development of Ark UI. <3

However, we use issue templates for important reasons. Setting up a reproduction example (Stackblitz) requires significant time and effort, and it's most efficiently done by the person reporting the issue. In light of this, I will close this issue and kindly ask you to create a new one, ensuring the issue template is properly filled out.
