### ISSUE TITLE
HoverCard component visibility issue

### ISSUE THREAD

**Issue by arekrgw** [chakra-ui/ark#1791]
### Description

I'm trying to use HoverCard component as below

```jsx
<HoverCard.Root key={item.title} positioning={{ placement: 'bottom-end' }} openDelay={0} closeDelay={0}>
  <TextStyle asChild variant="body/title_14_bold" className="flex items-center gap-2">
    <HoverCard.Trigger>
      {item.title}
      <SmallChevronDown />
    </HoverCard.Trigger>
  </TextStyle>
  <HoverCard.Positioner>
    <HoverCard.Content className="flex min-w-[20rem] flex-col items-start bg-white px-6 pb-6 pt-4 text-gray-600">
      {item.children.map((child) => (
        <TextStyle key={child.title} asChild variant="body/paragraph_16_light" className="py-3">
          <Link href={child.path}>{child.title}</Link>
        </TextStyle>
      ))}
      <Button variant="ghost" asChild className="mt-4 self-center">
        <Link href={item.path}>
          {item.allTitle}
          <LinkIcon />
        </Link>
      </Button>
    </HoverCard.Content>
  </HoverCard.Positioner>
</HoverCard.Root>
```
### Component behaves as described
Content of hover card is visible all the time.

### Expected behaviour
Content shows after cursor is moved above trigger element

### Possible issue:
I've check the devtools all seems right, HoverCard.Content has hidden prop on it, but it is being overridden by flex tailwind class. I believe any other CSS that modifies display style will break this component

Should we structure content differently? If so, it should have been mentioned in the docs to prevent head scratching :)

### Link to Reproduction (or Detailed Explanation)

As above ^

### Steps to Reproduce

As above ^

### Ark UI Version

1.1.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Brave: 1.60.118, Chromium: 119.0.6045.163 (Official Build) (arm64)

**Comment by cschroeter** [comment]
@arekrgw 

Thanks for taking your time to create this issue. The problem here is that the depending on the state the content is hidden.
So if you add the class `flex` you force the hover card to be visible all the time.

What you can do is when the component is maybe `hover:flex` or move the flex container in the content as an extra node.
Here is what I do in [Park UI ](https://park-ui.com/) using [Panda CSS](https://panda-css.com/)

```jsx
 content: {
  display: 'flex',
  _hidden: {
    display: 'none',
  },
}
```

**Comment by arekrgw** [comment]
That's how I resolved it but thought that it could be mentioned somewhere in the docs that specifying display style directly on the HoverCard.Content can lead to issue and more styles is needed or nesting.

That's our first production use of Ark UI and I want to help as much as I can with pointing out missing docs or places for improvement.

Anyway, thanks for fast response!
