### ISSUE TITLE
AsChild is propagated down the tree

### ISSUE THREAD

**Issue by arekrgw** [chakra-ui/ark#1804]
### Description

When composing multiple asChild components asChild is being propagated down the tree despite having explicit `asChild={false}` prop set or non-existent at all. See an example

```jsx
 <HoverCard.Trigger asChild>
    <TextStyle asChild={false} variant="body/title_14_bold" className="group flex items-center gap-2">
      {locale}
      <SmallChevronDown className="transition-transform group-data-[state=open]:rotate-180" />
    </TextStyle>
  </HoverCard.Trigger>
```

```jsx
export const TextStyle = forwardRef<HTMLSpanElement, TextStyleProps>((props, ref) => {
  const { className, variant = 'body/paragraph_16_light', asChild, ...rest } = props;
  return <ark.span ref={ref} className={cn(textStyles({ variant }), className)} asChild={asChild} {...rest} />;
});
```

In the example I have created custom TextStyle component with ark factory to be able to use asChild. Then I'm using it to create trigger for hover card. As a result I have the following error in console from react

```
Warning: React does not recognize the `asChild` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `aschild` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

Is it an expected behaviour? 

```jsx
 <HoverCard.Trigger asChild>
    <TextStyle variant="body/title_14_bold" className="group flex items-center gap-2">
      <span>
        {locale}
        <SmallChevronDown className="transition-transform group-data-[state=open]:rotate-180" />
      </span>
    </TextStyle>
  </HoverCard.Trigger>
```

It can be fixed as above, but I'm a bit confused.

### Link to Reproduction (or Detailed Explanation)

-

### Steps to Reproduce

-

### Ark UI Version

1.1.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Brave: 1.60.118, Chromium: 119.0.6045.163 (Official Build) (arm64)

**Comment by cschroeter** [comment]
@arekrgw 

Thanks for taking your time to create this issue. A fix and some tests for the `ark` factory fn have been implemented (https://github.com/chakra-ui/ark/commit/9ad1b29de111ef512834e1853cb86d0016adc77d)

As a workaround you can not set the `aschild` prop explictly:

```tsx
<HoverCard.Trigger asChild>
    <TextStyle variant="body/title_14_bold" className="group flex items-center gap-2">
      {locale}
      <SmallChevronDown className="transition-transform group-data-[state=open]:rotate-180" />
    </TextStyle>
  </HoverCard.Trigger>
  ```
