### ISSUE TITLE
NumberInput increment/decrement triggers buggy behaviour with fr-FR locale

### ISSUE THREAD

**Issue by markoffden** [chakra-ui/ark#1838]
### Description

When I use `NumberInput` with currency format style in `fr-Fr` locale I get buggy increment/decrement behaviour after manual input.

### Link to Reproduction (or Detailed Explanation)

(see steps to reproduce)

### Steps to Reproduce

1. Setup `NumberInput` with the following root options and increment/decrement triggers:

```
formatOptions={{
    style: 'currency',
    currency: 'EUR',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
}}
step={1}
locale="fr-FR"
```

2. Manually enter any decimal number (comma separated), e.g. `10,50`
3. Click on e.g. increment trigger
4. Expected result `11,50 €`, but actual result `1 051,00 €`

### Ark UI Version

1.1.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome 119.0.6045.159

**Comment by segunadebayo** [comment]
This has been fixed in Zag.js; here's a similar issue (https://github.com/chakra-ui/zag/issues/1022)

We'll release an update shortly. If the issue persists after the release, I'll re-open it.
