### ISSUE TITLE
[Vue] Module has no exported member

### ISSUE THREAD

**Issue by ListenV** [chakra-ui/ark#1871]
### Description

Just like this:

`Module "@ark-ui/vue" has no exported member "Tooltip"`

![image](https://github.com/chakra-ui/ark/assets/45219522/22c708d8-c65e-47ea-8726-a61593bae814)

The module `Tooltip` is missing `index.d.ts`.

This is also the case with `ColorPicker` and `HoverCard`.

![image](https://github.com/chakra-ui/ark/assets/45219522/a1308943-365c-41f6-8c6c-97feb5290022)

### Link to Reproduction (or Detailed Explanation)

null

### Steps to Reproduce

null

### Ark UI Version

"@ark-ui/vue": "^0.8.0"

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

Microsoft Edge

**Comment by Omikorin** [comment]
Hi, Vue implementation needs more revision, so the package is not yet released.
If you want to use the latest codebase you can use [gitpkg](https://gitpkg.vercel.app/)

We are nearly there.

**Comment by ListenV** [comment]
@Omikorin Thank you for your answer.

**Comment by cschroeter** [comment]
@ListenV 

I've released `@ark-ui/vue:0.9.0`. This should solve your issue.
