### ISSUE TITLE
`HTMLPolymorphicProps` type not exposing intrinsic element attributes

### ISSUE THREAD

**Issue by TylerAPfledderer** [chakra-ui/ark#1884]
### Description

The type signature of [HTMLPolymorphicProps](https://github.com/chakra-ui/ark/blob/4f8d697dc07f1a760d069781cdd8b3ffe3f79850/packages/frameworks/vue/src/factory.tsx#L51-L53) for the Vue package seems to be incomplete, as it is not properly extracting props from `IntrinsicElementAttributes` of a given HTML tag.

This effects prop typing of components that extend `HTMLArkProps`

### Link to Reproduction (or Detailed Explanation)

N/A

### Steps to Reproduce

You can view in any component story in package the lack of auto completion of props that come from `InstrinsicElementAttribute` of a given HTML tag. For example, if `HTMLArkProps<"img">` you will not get the auto-completion of props such as `src`, `alt`, or any of the `aria-*`

### Ark UI Version

0.9.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

N/A

### Additional Information

There is already a possible solution that is inline with this type's usage in the other frameworks (the other frameworks do not actually have the `HTMLPolymorphicProps` type and just `HTMLArkProps`, but the general approach is the same to work in Vue).

For the generic type supplied to `HTMLPolymorphicProps`, it is only extending `keyof IntrinsicElementAttributes`, which means `ExtractPropTypes` is receiving a string type and not an object type, thereby extracting nothing.

The fix:
```ts
export type HTMLPolymorphicProps<T extends ElementType> = Omit<
  // If T is the keyof a DOM element (i.e. `img`) then need to obtain that element's attribute object to extract props.
  // Otherwise, return T which could be a component (`DefineComponent` definition)
  ExtractPropTypes<T extends DOMElements ? IntrinsicElementAttributes[T] : T>,
  'ref'
> & {
  asChild?: boolean
}
```
## Warning 🚨
This issue is only created for tracking and should be considered backlogged at this time. Currently, the caveat to the above fix creates the type error `Type instantiation is excessively deep and possibly infinite.` related to [ComponentWithProps](https://github.com/chakra-ui/ark/blob/4f8d697dc07f1a760d069781cdd8b3ffe3f79850/packages/frameworks/vue/src/utils.ts#L33-L41).

There is a consideration in doing away with `ComponentWithProps` in favor of receiving the necessary typing from the [defineComponent function signature approach](https://github.com/vuejs/core/blob/a6503e3e77b04a1ab8c07078e07091b06d51131d/packages/runtime-core/src/apiDefineComponent.ts#L97-L130) introduced to aid in user-defined generic typing of components.

Unless there is a solution for the instantiation error that I could not recognize, need to wait until determining if the change to `defineComponent` is viable and be completed first.

**Comment by iamdin** [comment]
Hi, I also encountered the same issues. And I also think there is a little hack to use `ComponentWithProps` to annotate a component. 

The new feature [Function Signature](https://vuejs.org/api/general.html#function-signature) released in Vue3.3  is awesome, the main use case is with TypeScript (and in particular with TSX), as it supports generics. So I think we can change the way we define components.

**Comment by TylerAPfledderer** [comment]
@iamdin one of the current issues with the function component signature is not exposing slots as props. This is currently being addressed in an open Pr: https://github.com/vuejs/core/pull/9721 but I have not seen any update on this. Emit typing seems to also be a dirty regardless of how `defineComponents` is being used.

However, I think doing the function signature would still be cleaner if a hack needed to exist to make sure we get all the correct typing when calling props or directives.

**Comment by iamdin** [comment]
I agree with you. Looks like there are some trade-offs to be made. And if we use this feature,  does it mean that the user's Vue version must greater than 3.3? [defineComponent in Vue3.3](https://github.com/vuejs/core/blob/9fa82414eba9748313d2ef28c939224b8929f046/packages/runtime-core/src/apiDefineComponent.ts#L285C1-L285C76) vs [defineComponent in Vue3.2](https://github.com/vuejs/core/blob/45984d559fe0c036657d5f2626087ea8eec205a8/packages/runtime-core/src/apiDefineComponent.ts#L202). The version 3.3 extend `extraOptions` for runtime props, but not implement before.
```ts
// implementation, close to no-op
/*! #__NO_SIDE_EFFECTS__ */
export function defineComponent(
  options: unknown,
  extraOptions?: ComponentOptions
) {
  return isFunction(options)
    ? // #8326: extend call and options.name access are considered side-effects
      // by Rollup, so we have to wrap it in a pure-annotated IIFE.
      /*#__PURE__*/ (() =>
        extend({ name: options.name }, extraOptions, { setup: options }))()
    : options
}
```

**Comment by Omikorin** [comment]
> I agree with you. Looks like there are some trade-offs to be made. And if we use this feature,  does it mean that the user's Vue version must greater than 3.3? [defineComponent in Vue3.3](https://github.com/vuejs/core/blob/9fa82414eba9748313d2ef28c939224b8929f046/packages/runtime-core/src/apiDefineComponent.ts#L285C1-L285C76) vs [defineComponent in Vue3.2](https://github.com/vuejs/core/blob/45984d559fe0c036657d5f2626087ea8eec205a8/packages/runtime-core/src/apiDefineComponent.ts#L202). The version 3.3 extend `extraOptions` for runtime props, but not implement before.
> ```ts
> // implementation, close to no-op
> /*! #__NO_SIDE_EFFECTS__ */
> export function defineComponent(
>   options: unknown,
>   extraOptions?: ComponentOptions
> ) {
>   return isFunction(options)
>     ? // #8326: extend call and options.name access are considered side-effects
>       // by Rollup, so we have to wrap it in a pure-annotated IIFE.
>       /*#__PURE__*/ (() =>
>         extend({ name: options.name }, extraOptions, { setup: options }))()
>     : options
> }
> ```

I think we should wait. The feature is new and it's possible for new issues to emerge. The current approach works and is accessible to vastly more users.

**Comment by TylerAPfledderer** [comment]
@Omikorin ok.

Then how should this GH issue be addressed in getting those intrinsic attributes exposed as props?

**Comment by Omikorin** [comment]
@TylerAPfledderer to be honest, I haven't thought about that yet

I checked the Vue 3.3 release date, and it's not so new (May 2023).

I changed my mind. We are before v1.0, so whether it's a breaking change or not doesn't matter.

**Comment by Omikorin** [comment]
Done in #1928 without `Combobox.Root` (same as Select) due to more typing issues

**Comment by iamdin** [comment]
> Done in #1928 without `Combobox.Root` (same as Select) due to more typing issues

Unbelievable. Your work productivity is outstanding. @Omikorin

**Comment by TylerAPfledderer** [comment]
> Done in #1928 without `Combobox.Root` (same as Select) due to more typing issues

Since that is done, I'll go ahead and address this.

**Comment by TylerAPfledderer** [comment]
> Done in #1928 without `Combobox.Root` (same as Select) due to more typing issues

I can take a look at the outstanding ones, but I found this that may be of use:
https://logaretm.com/blog/generic-type-components-with-composition-api/

(Not meaning to possibly walk backwards here on some of this person's suggestions! 😅)

**Comment by Omikorin** [comment]
It's funny to know that types work because I needed to comment the `Menu` exports test (Menu lacks three parts in each framework).
