### ISSUE TITLE
Vue: 1.0

### ISSUE THREAD

**Issue by cschroeter** [chakra-ui/ark#1889]
If you're reading this, you might be interested in helping us bring the Vue.js version of Ark UI to version 1.0. We're thrilled to have you onboard ;)

 The Vue.js implementation is in a decent state—most components have been implemented. However, we've identified a few key tasks to reach our 1.0 milestone:

- [x] Port the React test suite to Vue.js.
- [x] Verify the accuracy of typings (Slots, Props).
- [x] Update Storybook to match stories from Solid/React versions.
- [x] Release `@ark-ui/vue:0.10.0` for testing
- [ ] Release `v1.0`

**Any help is greatly appreciated!** The best way to start is by porting tests to each Vue component. If you encounter a more fundamental issue, please reach out here in this issue or contact us on Twitter.

**Comment by tve** [comment]
It would help a lot if you could provide steps to set-up dev environment. See #1941

**Comment by cschroeter** [comment]
Release coming shortly. Closing
