### ISSUE TITLE
Pin Input not very strict

### ISSUE THREAD

**Issue by marcoarnulfo** [chakra-ui/ark#1916]
### Description

I tried to implement the pin input in my project, specifically for the 'otp' feature. It works, BUT if the user pastes repeatedly into the last pin input, everything that has been pasted will be repeatedly written in that last 'cell'.
![Screenshot 2023-12-20 000352](https://github.com/chakra-ui/ark/assets/103679419/17b898db-52b2-41dd-9af2-c5e1566a31db)

### Link to Reproduction (or Detailed Explanation)

React with create react app

### Steps to Reproduce

``const Basic = () => (
        <PinInput.Root placeholder='__' otp type='numeric' onValueComplete={(e) => console.log(e.valueAsString)}>
            {/* <PinInput.Label>Label</PinInput.Label> */}
            <PinInput.Control>
                {[0, 1, 2, 4, 5, 6].map((id, index) => (
                    <PinInput.Input className='input_square me-3' key={id} index={index} />
                ))}
            </PinInput.Control>
        </PinInput.Root>
    )
``

### Ark UI Version

^1.2.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome

**Comment by marcoarnulfo** [comment]
For now, I've resolved the issue by adding maxLength ONLY to the last input (if I added it to all, the OTP wouldn't work).

`
const Basic = () => (
        <PinInput.Root placeholder='__' otp type='numeric' onValueComplete={(e) => console.log(e.valueAsString)}>
            {/* <PinInput.Label>Label</PinInput.Label> */}
            <PinInput.Control>
                {[0, 1, 2, 4, 5, 6].map((id, index, array) => (
                    <PinInput.Input 
                    className='input_square me-3' 
                    key={id} 
                    index={index} 
                    maxLength={index === array.length - 1 ? 1 : undefined} // Set maxLength only for the last input
                />
                ))}
            </PinInput.Control>
        </PinInput.Root>
    )
`

**Comment by Omikorin** [comment]
chakra-ui/zag#1132 will resolve this issue

**Comment by segunadebayo** [comment]
This has been fixed in Zag. We'll cut a new release shortly.
