### ISSUE TITLE
[vue] [ColorPicker] ColorPicker.ChannelInput asChild prop is not working

### ISSUE THREAD

**Issue by renatodeleao** [chakra-ui/ark#1922]
### Description

When I wanted to use either a single raw `<input>` element or an already existent `<AppInput />` from a design system as `ChannelInput` part, the component throws an error saying that they're not valid children. 

According to docs `asChild` is supported for this part.

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/vitejs-vite-kvd9ba?file=src%2FApp.vue

### Steps to Reproduce

1. The demo uses the default documentation markup
1. Just try to load it and open dev console, it doesn't render because it throws an error.

If you remove the `asChild` prop from Channelnput part everything works as expected.

### Ark UI Version

0.9.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

Any

### Additional Information

I can confirm that this bugs exists at least since version `0.7.0`

**Comment by Omikorin** [comment]
Hi, thank you for the notice. I fixed it now.

**Comment by renatodeleao** [comment]
Thanks 🙏
