### ISSUE TITLE
Missing display names for Root

### ISSUE THREAD

**Issue by Omikorin** [chakra-ui/ark#1931]
### Description

`displayName` is missing for Combobox.Root and Select.Root in React.

### Link to Reproduction (or Detailed Explanation)

.

### Steps to Reproduce

.

### Ark UI Version

1.2.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
<img width="350" alt="grafik" src="https://github.com/chakra-ui/ark/assets/1846056/3f1226ab-f21b-450a-897d-c9fec1b5aea2">

@Omikorin 

Could you help me understand this issue. From the React Developer Tools I can not spot an issue witht display names

**Comment by Omikorin** [comment]
There was a typing issue for generic components. It seems solved for some other reason.
