### ISSUE TITLE
Any interaction in a popover is considered an "outside" interaction and closes the popover

### ISSUE THREAD

**Issue by Southclaws** [chakra-ui/ark#1933]
### Description

I'm embedding some interactive components within a Popover, styled with Panda. I've tried buttons and my main use-case, EmojiMart emoji picker. Weirdly, some interactions work as expected but most don't.

In the video, I'm clicking all around the popover, some interactions are captured correctly (the tabs) but others are caught by Ark as an "outside" interaction and thus close the popover.

https://github.com/chakra-ui/ark/assets/1636971/075b9930-712b-4dbe-9610-8cc8c4481839

### Link to Reproduction (or Detailed Explanation)

https://github.com/Southclaws/storyden/pull/58/

### Steps to Reproduce

Create a popover with some interactive elements, a button or in my case, EmojiMart picker.

### Ark UI Version

1.2.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome, Firefox, Safari

### Additional Information

I can put together a full minimal repro if needed, but it'll take some time. Just opening this first to check if it's a known issue or a documentation issue.

**Comment by Southclaws** [comment]
My current workaround is to just handle the click outside myself using [useClickAway](https://usehooks.com/useclickaway) with the `ref` passed to the `PopoverPositioner` component.

**Comment by cschroeter** [comment]
@Southclaws 

This should be fixed with the next major release
