### ISSUE TITLE
Inconsistent and Non-unified `v-model` API Design in Vue Components

### ISSUE THREAD

**Issue by iamdin** [chakra-ui/ark#1940]
### Description

I would like to discuss the design of the `v-model` API about our Vue component.

Currently, I think there is inconsistency in how the `v-model` API is implemented across different components. While some components use the `modelValue` prop and emit the `update:modelValue` event with the `onValueChange` callback, others use different prop names and events, such as [Checkbox](https://github.com/chakra-ui/ark/blob/333a401f1a9d76af7253e727d4e05330ed53ef45/packages/frameworks/vue/src/checkbox/use-checkbox.ts#L27) `checked` and `update:modelValue`, or [Dialog](https://github.com/chakra-ui/ark/blob/333a401f1a9d76af7253e727d4e05330ed53ef45/packages/frameworks/vue/src/dialog/use-dialog.ts#L25) `open` and `update:modelValue`. This inconsistency can be confusing for users.

### Suggestion: Unified `v-model`

I suggest unifying the `v-model` API across all components by simply equating the `value` prop with the `modelValue` prop. This means that we would only emit the `update:modelValue` event with the `onValueChange` callback. This approach is straightforward and intuitive, providing a consistent experience for users.

### Suggestion: `v-model:checked` or `v-model:open`

For components like `Checkbox` or `Dialog`, we can use the `update:checked` or `update:open` events for two-way binding. This means that users can use `v-model:checked` or `v-model:open` with the respective components. This approach aligns better with the design pattern of Vue components and provides a more intuitive usage for users.

### Ark UI Version

0.9.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

**Comment by Omikorin** [comment]
Second is better with the current API (used also in React and Solid).

**Comment by Omikorin** [comment]
I meant that the checked and open naming should be left as is. So the model:checked is ok.

**Comment by Omikorin** [comment]
I'd be glad to hear your @TylerAPfledderer opinion 😎

**Comment by iamdin** [comment]
What I want to say in this issue is that, for components with props like `open` or `checked`, it might be better to use `v-model:open` / `v-model:checked` for two-way binding instead of `v-model`

**Comment by TylerAPfledderer** [comment]
Hmm I find this to be a tricky situation.

We certainly need to learn towards the user's tendencies in handling v-model when they use it for other custom components, especially with forms.

I would refer to the [Vue docs](https://vuejs.org/guide/essentials/forms.html#form-input-bindings) for form inputs. Here, for the `checkbox` input a v-model is binding the `checked` prop with the `change` event. So in our application, I could only assume that a user would expect `v-model` for the `Checkbox` component to do the same...not `v-model:checked`. 

Me and @Shyrro already had a discussion like this 😅 and I'm trying to recall what the general consensus was.

**Comment by iamdin** [comment]
Agree with `Checkbox` component using `v-model`, so what about `open` state in `Dialog`...

**Comment by Omikorin** [comment]
Dialog open state is more complicated. I think this is relevant to Vue too -> zag#1027

**Comment by TylerAPfledderer** [comment]
> Dialog open state is more complicated. I think this is relevant to Vue too -> https://github.com/chakra-ui/zag/issues/1027

I fixed your link 🤪

**Comment by cschroeter** [comment]
Could we check other Vue libs what they use as `v-model` for certain components? Radix Vue, Vuetify just to name a few?

cc: @Omikorin @TylerAPfledderer

**Comment by Omikorin** [comment]
Quick check:

Radix Vue uses `v-model:checked` for [Checkbox](https://www.radix-vue.com/components/checkbox.html) and `v-model:open` for [Dialog](https://www.radix-vue.com/components/dialog.html).

Vuetify is different, it uses simply `v-model` for [Checkbox](https://vuetifyjs.com/en/components/checkbox) and [Dialog](https://vuetifyjs.com/en/components/dialogs/#v-model).

**Comment by cschroeter** [comment]
I don't have a strong opinion how we do it aslong as it is consistent across all our components and we have a common understanding why we picked that route <3

**Comment by TylerAPfledderer** [comment]
> I don't have a strong opinion how we do it aslong as it is consistent across all our components and we have a common understanding why we picked that route <3

Having some kind of style guide would be nice to have for reasons like this

**Comment by iamdin** [comment]
I find that, component Dialog `v-model` can't work, because we only emit 'update:modelValue)', but not process `modelValue` [Code](https://github.com/chakra-ui/ark/blob/454dd9c3d374fa7b3eafd8b2f75902de0cc3bea5/packages/frameworks/vue/src/dialog/use-dialog.ts#L25). so, we should transform `modelValue` to `open`?

**Comment by Omikorin** [comment]
@iamdin after some discussion, the choice is to have the Radix Vue approach e.g. `v-model:checked`. You can change what you need to get this working.

@TylerAPfledderer please correct me if I'm wrong

**Comment by TylerAPfledderer** [comment]
I'm good with it if we want to be explicit.

I would still say that we should have another PR open dedicated to a style guide for future contributors or others that need more information on the chosen approach. The more background we can provide, the better with DX!

**Comment by Omikorin** [comment]
Yeah, one thing I found, we are missing CONTRIBUTING.md nowm

The one in the repo is in reality a code of conduct.

**Comment by cschroeter** [comment]
I think we used https://generator.contributing.md/ feel free to extend. Also we can have different files for different frameworks I believe.

**Comment by iamdin** [comment]
> @iamdin after some discussion, the choice is to have the Radix Vue approach e.g. `v-model:checked`. You can change what you need to get this working.
> 
> @TylerAPfledderer please correct me if I'm wrong

That's great. I will do it in the next PR

**Comment by Omikorin** [comment]
Hover Card and Popover needs an update too

**Comment by segunadebayo** [comment]
This is now tackled in the #1889 ticket
