### ISSUE TITLE
[vue] Menu.Content generates nested div and applies attrs to both

### ISSUE THREAD

**Issue by tve** [chakra-ui/ark#1964]
### Description

Using Menu.Content I see two nested divs generated and the attrs of the Menu.Content are applied to both. When trying to style the Menu.Content using something like tailwind css this is problematic because the styles are applied to both nested divs.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/github/tve/ark-vue-dev/menu-nested-divs

### Steps to Reproduce

1. Start the codesandbox
2. It should build ark-ui/vue and the demo
3. In a terminal, `cd demo; pnpm run dev`
4. Refresh the preview and click the menu button
5. Observe the double border (the inner may be white instead of red due to focus)

### Ark UI Version

main branch https://github.com/chakra-ui/ark/commit/ebc00f3c8b96c38ccff6e5862722f19b5f6e35a0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Additional Information

Here's the html/css, notice the class `menu-content` on the Menu.Content:

![image](https://github.com/chakra-ui/ark/assets/39480/de8f9788-e4a0-48de-8aac-1f3f4b2111a5)

Here's what it looks like, notice the double red border due to the two nested divs:

![image](https://github.com/chakra-ui/ark/assets/39480/c9aa5ca4-9bbf-4de8-9278-c54b23e26e50)

Here's the DOM, notice the two nested divs with `class="menu-content"`

![image](https://github.com/chakra-ui/ark/assets/39480/b71490d7-eea6-442b-87e8-2831a20516fb)

**Comment by Omikorin** [comment]
Your testing branch is behind our `main` branch. The `data-scope="presence"` should not be existing there for now. It was changed in #1943.

Please sync and check again

**Comment by tve** [comment]
Oops. Checking...

**Comment by Omikorin** [comment]
It's interesting to see I accidentally fixed an unknown bug 😅
