### ISSUE TITLE
Flaky test in Slider for React

### ISSUE THREAD

**Issue by Omikorin** [chakra-ui/ark#1970]
### Description

It started with a new Zag update (IIRC)

![image](https://github.com/chakra-ui/ark/assets/6079265/bbe0a2af-a318-4336-8256-62b6ba9c4d1e)

### Link to Reproduction (or Detailed Explanation)

.

### Steps to Reproduce

1. Run tests many times

### Ark UI Version

1.2.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by Omikorin** [comment]
It's pretty random (I've seen with 19 too)
![image](https://github.com/chakra-ui/ark/assets/6079265/8b78486b-4ef4-48b7-b565-8f09c42317cc)

**Comment by TylerAPfledderer** [comment]
@Omikorin just updated my local and it appears to be passing. Is it still there for you?

**Comment by Omikorin** [comment]
I did tests in Storybook and everything is fine. The problem is tests are more sensitive or something

**Comment by cschroeter** [comment]
@Omikorin 

Overall I am quite happy with the test suite I don't any issue with the pipeline. However I set the `retry` count to `2`. This should be good for now.
