### ISSUE TITLE
Combobox input is being focused for a brief moment upon opening iOS Safari

### ISSUE THREAD

**Issue by jimmy-qian** [chakra-ui/ark#1999]
### Description

When I make use of `<Combobox>` on iOS Safari, and try to open the menu by pressing on `Combobox.Trigger`, it puts focus on `Combobox.Input` for a split of a second and loses focus.

This implies 2 glitchy UI issues:
- Focus state of the input flickers for a brief moment
- Native keyboard tries to open and closes within the same moment, which causes layout changes in the browser UI.

### Link to Reproduction (or Detailed Explanation)

-

### Steps to Reproduce

1. Add `<Combobox/>` to your application (with no styling)
2. Open your application on iOS Safari.

### Ark UI Version

1.2.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

iOS Safari 16.5.2

**Comment by cschroeter** [comment]
@jimmy-qian 

Thanks for taking your time to create this issue. Do you have a screencast or sth - since I don't have a way to check this in iOS

**Comment by jimmy-qian** [comment]
Hey @cschroeter, here it is!

https://github.com/chakra-ui/ark/assets/102806545/90363b55-49c9-4634-ad55-b7d673d544cc

As you can notice the reported bug by the default blue outline for Safari focus state, and the Safari navigation section being raised slightly every time it's I click on open.

**Comment by cschroeter** [comment]
This should be fixed in the upcoming 3.0 release. Please re-open if the issue persist.
