### ISSUE TITLE
[Vue] Menu `@select` event no longer send selected item

### ISSUE THREAD

**Issue by RomainLanz** [chakra-ui/ark#2000]
### Description

Hey there! 👋🏻 

Since version `0.9.0`, the `@select` event in the `Menu.Root` component no longer returns the selected item.
Reverting back to `0.8.0` makes the Menu work again.

### Link to Reproduction (or Detailed Explanation)

Version 0.9.0 (with bug): https://stackblitz.com/edit/vitejs-vite-rzhfml?file=src%2Fcomponents%2FMenuBug.vue
Version 0.8.0 (without bug): https://stackblitz.com/edit/vitejs-vite-ajq8zw?file=src%2Fcomponents%2FMenuBug.vue

### Steps to Reproduce

1. Go to https://stackblitz.com/edit/vitejs-vite-rzhfml?file=src%2Fcomponents%2FMenuBug.vue
2. Open the Console
3. Click on `Open`
4. Select any item
5. Notice the `[]` logged value.

### Ark UI Version

0.9.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

Arc

**Comment by Omikorin** [comment]
Thanks for the notice. I took a look at the problem and your example works on the `main` branch again.

Btw, you accidentally installed vue 0.9 on the 0.8 example.

**Comment by RomainLanz** [comment]
> Btw, you accidentally installed vue 0.9 on the 0.8 example.

Ooops. 😅 

> It was fixed in https://github.com/chakra-ui/ark/pull/1906

Good to know!
Thanks.

**Comment by Omikorin** [comment]
You can use the main branch instead of v0.9 right now. There are so many helpful changes you'll notice in an instant.

You can tell me about new problems thanks to this ;D
