### ISSUE TITLE
[Solid][Combobox] options not being filtered

### ISSUE THREAD

**Issue by trevorblades** [chakra-ui/ark#2006]
### Description

When I type "so" into the combobox input, I expect the list to be filtered to show "Solid", but nothing happens. I'm using the example code from the ark combobox docs, so I'm not sure if there's something else that I need to do to make this work that is undocumented, or if it's an issue with the library itself.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/agitated-banach-f2rt7j?file=/src/Combobox.tsx:11,27

### Steps to Reproduce

1. Go to https://codesandbox.io/p/devbox/agitated-banach-f2rt7j?file=/src/Combobox.tsx:11,27
2. Type "so" into the combobox input
3. The list of options doesn't change

### Ark UI Version

1.2.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
@trevorblades 

Thanks for taking your time to create this issue. Unfortunately the combobox could be document a bit better. You need to bring your own filter function like so:

```tsx
const MyCombobox = () => {
  const handleChange = (e: any) => {
    const filtered = data.filter((item) => item.label.toLowerCase().includes(e.value.toLowerCase()))
    setItems(filtered.length > 0 ? filtered : data)
  }
```

https://github.com/chakra-ui/ark/blob/main/packages/website/src/demos/combobox.demo.tsx

  return (
    <Combobox.Root width="2xs" onInputValueChange={handleChange} items={items}>...</ComboboxRoot>
    )
 }

**Comment by Omikorin** [comment]
> @trevorblades 
> 
> Thanks for taking your time to create this issue. Unfortunately the combobox could be document a bit better. You need to bring your own filter function like so:
> 
> ```tsx
> const MyCombobox = () => {
>   const handleChange = (e: any) => {
>     const filtered = data.filter((item) => item.label.toLowerCase().includes(e.value.toLowerCase()))
>     setItems(filtered.length > 0 ? filtered : data)
>   }
>   return (
>     <Combobox.Root width="2xs" onInputValueChange={handleChange} items={items}>...</ComboboxRoot>
>     )
>  }
> ```
> 
> https://github.com/chakra-ui/ark/blob/main/packages/website/src/demos/combobox.demo.tsx

@trevorblades could you help us with adding info about this in the docs? :)
