### ISSUE TITLE
Select's Value Text can't display dynamically update items

### ISSUE THREAD

**Issue by crasite** [chakra-ui/ark#2029]
### Description

Newly added item to `items` via signal doesn't get displayed properly

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/solidjs-templates-xozmyg?file=src%2FApp.tsx

### Steps to Reproduce

1. create a signal for items
2. use said signal as `items` props on `Select.Root`
3. add new item to that signal
4. select that new item

_**Default Placeholder is shown instead of the new item**_

### Ark UI Version

1.2.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

### Browser

*

**Comment by Reverier-Xu** [comment]
Hi, this issue still happened on the latest rc `3.0.0-2`, see https://stackblitz.com/edit/solidjs-templates-numplr?file=package.json,src%2FApp.tsx
