### ISSUE TITLE
[vue] AccordionItemContent duplicate attrs on presence and item-content

### ISSUE THREAD

**Issue by Ask1n** [chakra-ui/ark#2038]
### Description

When using AccordionItemContent it creates two divs that duplicate the attr, including classes

### Link to Reproduction (or Detailed Explanation)

init Accordion and add class to AccordionItemContent

### Steps to Reproduce

1. add class on AccordionItemContent

### Ark UI Version

0.9.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

**Comment by Omikorin** [comment]
Should be fixed in v0.10

Not sure because there's missing repro / screens
