### ISSUE TITLE
Module has no exported member

### ISSUE THREAD

**Issue by mcfarljw** [chakra-ui/ark#2041]
### Description

I expect to be able to export Combobox and Select from the @ark-ui/vue library using TypeScript.

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/nuxt-starter-wec8zb?file=components%2FSelect.vue

### Steps to Reproduce

1. Navigate to https://stackblitz.com/edit/nuxt-starter-wec8zb?file=components%2FSelect.vue
2. Check console for errors

### Ark UI Version

0.9.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Additional Information

It seems like some work like ToggleGroup but others like Select and Combobox do not export.

**Comment by Omikorin** [comment]
Resolved in v0.10 :)
