### ISSUE TITLE
Avatar.Root wrongly merging passed className with original ones

### ISSUE THREAD

**Issue by 6qat** [chakra-ui/ark#2053]
### Description

There is a problem when merging props in Avatar component. When I pass a className to root, it clears the original root classes and just keeps the passed ones. Just solved removing the className prop before avatar.splitVariantProps() function, and then adding it back to Avatar.Root className (pass it to cx() function).
![Ark-Avatar-Bug](https://github.com/chakra-ui/ark/assets/1149271/8f77f37a-8fbd-4908-838a-f91a1ca41fb0)

### Link to Reproduction (or Detailed Explanation)

Using Park Avatar component, based on Ark Avatar. When I pass a className to root, even an empty one, the original root styles get erased, keeping just the added ones.

### Steps to Reproduce

1. Install ark
2. Install park
3. Generate Avatar component
4. Instantiate it with any className, even an empty one<Avatar className="" />
5. The avatar is rendered without any style

### Ark UI Version

1.3.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome

**Comment by cschroeter** [comment]
@6qat 

Thanks for taking your time to create this issue. Please use the following snippet. I will update the other components accordingly.

```jsx
export const Avatar = forwardRef<HTMLDivElement, AvatarProps>((props, ref) => {
  const [variantProps, avatarProps] = avatar.splitVariantProps(props)
  const [cssProps, localProps] = splitCssProps(avatarProps)
  const { name, src, className, ...rootProps } = localProps
  const styles = avatar(variantProps)

  return (
    <ArkAvatar.Root ref={ref} className={cx(styles.root, css(cssProps), className)} {...rootProps}>
      <ArkAvatar.Fallback className={styles.fallback}>
        {getInitials(name) || <UserIcon />}
      </ArkAvatar.Fallback>
      <ArkAvatar.Image className={styles.image} src={src} alt={name} />
    </ArkAvatar.Root>
  )
})
```
