### ISSUE TITLE
Popover closes on click in a web component

### ISSUE THREAD

**Issue by mybearworld** [chakra-ui/ark#2060]
### Description

When using a Web Component within a popover, any interaction in that web component will make the popover close.

### Link to Reproduction (or Detailed Explanation)

https://github.com/mybearworld/arkui-webcomponent-bug

### Steps to Reproduce

1. `pnpm install` the dependencies
2. Run `pnpm dev`
3. Click on the "Click Me" button

### Ark UI Version

Ark UI Vue 0.10.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

Microsoft Edge

**Comment by segunadebayo** [comment]
Hi @mybearworld,

I'm sure we can do better with the docs, but here's how you'd be able to handle this.

```tsx
<Popover.Root
    onInteractOutside={(e) => {
      const target = e.composedPath()[0] as HTMLElement
      if (target.closest('emoji-picker')) {
        e.preventDefault()
      }
    }}
  >
    <Popover.Trigger>
      Click Me <Popover.Indicator>{'>'}</Popover.Indicator>
    </Popover.Trigger>
    <Popover.Positioner>
      <Popover.Content>
        <Popover.Title>Title</Popover.Title>
        <Popover.Description>Description</Popover.Description>
      </Popover.Content>
    </Popover.Positioner>
  </Popover.Root>
```

Calling `e.preventDefault` will stop the popover's interaction outside logic from being called

**Comment by mybearworld** [comment]
Thank you! Sorry, I didn't realize that.
