### ISSUE TITLE
[regression] Popover controlled state only works first time.

### ISSUE THREAD

**Issue by aboveyunhai** [chakra-ui/ark#2077]
### Description

Popover controlled state outside of the `Popover.Trigger` only works the first time. 
1.1.0 works fine, broken for 1.2.0 and 1.3.0 (latest)

### Link to Reproduction (or Detailed Explanation)
Basic example from documentation:
https://codesandbox.io/p/sandbox/ark-ui-popover-k89zgt?file=%2Fsrc%2FApp.tsx%3A8%2C7

### Steps to Reproduce

Click the button trigger, it will open Popover and then fail to re-open after close.

### Ark UI Version

^1.2.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by c-butler-edacious** [comment]
Same issue with the `Dialog` component as well.

**Comment by juliomuhlbauer** [comment]
Seems that open states aren't controllable. If anyone can help to make controllable open states, I opened a PR that seems to fix for Dialog: https://github.com/chakra-ui/zag/pull/1161

**Comment by fseglard** [comment]
Maybe related to this issue https://github.com/chakra-ui/ark/issues/2077 in Zag.js

**Comment by cschroeter** [comment]
@aboveyunhai 

This issue will be fixed with the next major release.
