### ISSUE TITLE
[Vue] Warning Component emitted event "X-Y" but it is neither declared in the emits option nor as an "onX-Y" prop.

### ISSUE THREAD

**Issue by RomainLanz** [chakra-ui/ark#2079]
### Description

Dear all,

With the latest release, `0.10.0`, there are a bunch of warnings saying that Vue is missing an emits declaration.

Here are some examples when using the `Menu` component.

```
[Vue warn]: Component emitted event "select" but it is neither declared in the emits option nor as an "onSelect" prop.
```

```
[Vue warn]: Component emitted event "open-change" but it is neither declared in the emits option nor as an "onOpen-change" prop.
```

```
[Vue warn]: Component emitted event "exit-complete" but it is neither declared in the emits option nor as an "onExit-complete" prop.
```

```
[Vue warn]: Extraneous non-emits event listeners (select) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. If the listener is intended to be a component custom event listener only, declare it using the "emits" option. 
```

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/vitejs-vite-rhmxa1

### Steps to Reproduce

1. Go on https://stackblitz.com/edit/vitejs-vite-rhmxa1
2. Open the console
3. See the warning

### Ark UI Version

0.10.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

Arc

**Comment by mybearworld** [comment]
I'm facing the same issue. This also makes it impossible to actually catch any of these events - specifically for me, making [this](https://github.com/chakra-ui/ark/issues/2060#issuecomment-1909051958) not possible.

**Comment by Omikorin** [comment]
Hi @RomainLanz, thanks for the notice!

I am investigating this problem now and found a fix, but need to do some tweaks with types
![image](https://github.com/chakra-ui/ark/assets/6079265/3464d020-a9aa-4f01-a54c-f65e1ea9e99c)

**Comment by mybearworld** [comment]
> Hi @RomainLanz, thanks for the notice!
> 
> I am investigating this problem now and found a fix, but need to do some tweaks with types.
> 
> ![image](https://private-user-images.githubusercontent.com/6079265/300231647-3464d020-a9aa-4f01-a54c-f65e1ea9e99c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MjkwMDksIm5iZiI6MTcwNjQyODcwOSwicGF0aCI6Ii82MDc5MjY1LzMwMDIzMTY0Ny0zNDY0ZDAyMC1hOWFhLTRmMDEtYTU0Yy1mNjVlMWVhOWU5OWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMDc1ODI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWRlODU4MzllMzNlZmI3ZmViNDk3NTM0N2RiZDc2Zjk4NDk5N2ExODRmNTFhNDQxNDFmMjg5ZjUwNmI3ZjE1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EAo3QAOXG6H8GfKpOjWtgY_tz9Tcxud4ibQdQEdnKm0)

When using the component, would this still allow using `@focus-change`, or would you have to use `onFocus-change`?

**Comment by Omikorin** [comment]
> > Hi @RomainLanz, thanks for the notice!
> > I am investigating this problem now and found a fix, but need to do some tweaks with types.
> > ![image](https://private-user-images.githubusercontent.com/6079265/300231647-3464d020-a9aa-4f01-a54c-f65e1ea9e99c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MjkwMDksIm5iZiI6MTcwNjQyODcwOSwicGF0aCI6Ii82MDc5MjY1LzMwMDIzMTY0Ny0zNDY0ZDAyMC1hOWFhLTRmMDEtYTU0Yy1mNjVlMWVhOWU5OWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMDc1ODI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWRlODU4MzllMzNlZmI3ZmViNDk3NTM0N2RiZDc2Zjk4NDk5N2ExODRmNTFhNDQxNDFmMjg5ZjUwNmI3ZjE1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EAo3QAOXG6H8GfKpOjWtgY_tz9Tcxud4ibQdQEdnKm0)
> 
> When using the component, would this still allow using `@focus-change`, or would you have to use `onFocus-change`?

We want to keep the first and clean option.

This thing is weird. The function passed to the machine context should stay as `onFocusChange`, but renaming it to the `'onFocus-change'` fixes it. In addition, changing `emit('focus-change', details)` to `emit('focusChange', details)` in the `useAccordion` doesn't help.

Do you @iamdin want to take a look?

**Comment by iamdin** [comment]
> Do you @iamdin want to take a look?

Sure， let me take a look.

**Comment by iamdin** [comment]
> > > Hi @RomainLanz, thanks for the notice!
> > > I am investigating this problem now and found a fix, but need to do some tweaks with types.
> > > ![image](https://private-user-images.githubusercontent.com/6079265/300231647-3464d020-a9aa-4f01-a54c-f65e1ea9e99c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MjkwMDksIm5iZiI6MTcwNjQyODcwOSwicGF0aCI6Ii82MDc5MjY1LzMwMDIzMTY0Ny0zNDY0ZDAyMC1hOWFhLTRmMDEtYTU0Yy1mNjVlMWVhOWU5OWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMDc1ODI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWRlODU4MzllMzNlZmI3ZmViNDk3NTM0N2RiZDc2Zjk4NDk5N2ExODRmNTFhNDQxNDFmMjg5ZjUwNmI3ZjE1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EAo3QAOXG6H8GfKpOjWtgY_tz9Tcxud4ibQdQEdnKm0)
> > 
> > 
> > When using the component, would this still allow using `@focus-change`, or would you have to use `onFocus-change`?
> 
> We want to keep the first and clean option.
> 
> This thing is weird. The function passed to the machine context should stay as `onFocusChange`, but renaming it to the `'onFocus-change'` fixes it. In addition, changing `emit('focus-change', details)` to `emit('focusChange', details)` in the `useAccordion` doesn't help.
> 
> Do you @iamdin want to take a look?

Oh, I think we made a little mistake @Omikorin . The `emits` declaration as an array, but destructuring assign to object.

- declaration
![CleanShot 2024-02-03 at 00 11 11](https://github.com/chakra-ui/ark/assets/36906371/1cc99ead-5710-46a0-9097-849b5917d1cd)

- usage
![CleanShot 2024-02-03 at 00 09 39](https://github.com/chakra-ui/ark/assets/36906371/7c7f69d2-7c4b-4e6d-89ff-a2c512b4acf9)

**Comment by iamdin** [comment]
> @iamdin oh, you are awesome! I wouldn't find this myself :D
> 
> Do you mind fixing this issue or should I do it?

i am glad to

**Comment by Omikorin** [comment]
@RomainLanz @mybearworld if you find this issue is still relevant feel free to tell me
