### ISSUE TITLE
SegmentGroup indicator have no height and width 

### ISSUE THREAD

**Issue by thibaultmthh** [chakra-ui/ark#2080]
### Description

The indicator of the SegmentGroup component have 0x0 in size. 

The issue is present in the docs website : 
<img width="489" alt="Capture d’écran 2024-01-23 à 18 45 45" src="https://github.com/chakra-ui/ark/assets/43826073/b9f13443-cbd7-4e46-aad0-0f141cac92a0">

This little fix made it work again :   `style={{ height: "var(--height)", width: "var(--width)" }}`

### Link to Reproduction (or Detailed Explanation)

https://ark-ui.com/docs/components/segment-group ( you can see the issue here ) 

### Steps to Reproduce

1. Create a component SegmentGroup
2. see that the indicator have no size

### Ark UI Version

1.3.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Arc Browser

**Comment by cschroeter** [comment]
@thibaultmthh 

Thanks for taking your time to report this issue. Your little fix is indeed the way to got about this.

```css
height: var(--height);
width: var(--width);
```

I think we did not do a god job communicating this.
