### ISSUE TITLE
Menu does not respect positioning

### ISSUE THREAD

**Issue by HYuanAi** [chakra-ui/ark#2117]
### Description

Modifying `positioning` field of Menu is kinda buggy. 

I would like to align the trigger and content to the right by setting `positioning` to `{ placement: "bottom-end" }`.

Any value that starts with "top" or "bottom" would dock the positioner to the bottom of the trigger, while any value that starts with "left" or "right" would dock it to the left of the trigger. The 2rem added to the width of the menu content also assumes that the content and trigger is left aligned. 

Also, there isn't much documentation about `positioning` and what each value means, I could only guess from the value itself. 

I'm not sure if I should file an issue here or with Zag.js, please let me know if I should do otherwise! :)

### Link to Reproduction (or Detailed Explanation)

 Set `positioning.placement` to any allowed values

### Steps to Reproduce

1. Set  `positioning` to `{ placement: "bottom-end" }` on a `Menu.Root` component. 
2. Trigger the menu and it'd oddly placed and doesn't seem to align to the trigger. 

### Ark UI Version

1.2.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Not browser-specific

**Comment by cschroeter** [comment]
Thanks for your report! We need a bit more info to help out. Please use this [template](https://codesandbox.io/p/devbox/ark-ui-react-issue-template-7hspkh) to create a CodeSandbox that shows the issue. Once you've done that, we can re-open this and take a look.
