### ISSUE TITLE
[vue] Slider props minStepsBetweenThumbs missing

### ISSUE THREAD

**Issue by Ask1n** [chakra-ui/ark#2122]
### Description

Slider does not have props minStepsBetweenThumbs, apparently this happened after combining RangeSlider and Slider

@ark-ui/vue v0.8.0
https://github.com/chakra-ui/ark/blob/c8177031497f2f725b7062eec64b1e36a167292a/packages/vue/src/range-slider/range-slider.props.ts#L44-L46

### Link to Reproduction (or Detailed Explanation)

https://github.com/chakra-ui/ark/blob/main/packages/frameworks/vue/src/slider/stories/range-slider.story.vue

### Steps to Reproduce

https://github.com/chakra-ui/ark/blob/14d369dad381632d4fbfa2b48c14ec60c3dbc076/packages/frameworks/vue/src/slider/stories/range-slider.story.vue#L121-L133

### Ark UI Version

0.10.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

**Comment by Omikorin** [comment]
Thanks for the notice! Fixed now
