### ISSUE TITLE
Pagination bug in docs

### ISSUE THREAD

**Issue by Blinks44** [chakra-ui/ark#2126]
### Description

This is what i am talking about:

![2024-02-04_14-45-06](https://github.com/chakra-ui/ark/assets/8570193/d67d8f2a-53be-49c1-b35b-4c2fcd858e07)

### Link to Reproduction (or Detailed Explanation)

-

### Steps to Reproduce

1. Go to Ark website
2. Open Pagination component
3. Just click on page-numbers
4. See weird duplications

### Ark UI Version

latest

### Framework

- [ ] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome

**Comment by cschroeter** [comment]
@Blinks44 

Thanks for taking your time to create this issue. The issue has been fixed.
