### ISSUE TITLE
[Select] Positioner not updating to reflect trigger size

### ISSUE THREAD

**Issue by FilipePfluck** [chakra-ui/ark#2146]
### Description

When the select is set to `multiple` and I select more items then it fits in the trigger, the size of the trigger will change to comport the selected items. This is expected. However, the Positioner component doesn't seem to update to reflect this:
![Screenshot from 2024-02-05 11-16-52](https://github.com/chakra-ui/ark/assets/62773200/8b6b69a6-938b-459d-ad98-8a8dc243fa6d)

Similarlly, if I open a Select with multiple items selected and unselect them, the trigger will shrink but the Positioner will also not reflect this: 
![Screenshot from 2024-02-05 11-17-38](https://github.com/chakra-ui/ark/assets/62773200/51764589-ea88-4790-a9c7-811f1c5ba1c3)
![Screenshot from 2024-02-05 11-17-50](https://github.com/chakra-ui/ark/assets/62773200/3be9cc93-dad6-476f-86e9-57ecb768b58b)

### Link to Reproduction (or Detailed Explanation)

https://github.com/FilipePfluck/PlucoUI

### Steps to Reproduce

1. Clone the repo
2. Run storybook
3. Check the Multiple Select story
4. Open the Select, and select multiple items until the trigger expands to fit them all
5. See how the Positioner doesn't update the Content position to reflect this

### Ark UI Version

1.3

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by segunadebayo** [comment]
This is now fixed in Zag.js. A new version will be released shortly.

https://github.com/chakra-ui/zag/pull/1213
