### ISSUE TITLE
Incorrect setting of aria-readonly attributes in RatingGroup component when readOnly parameter is true

### ISSUE THREAD

**Issue by Fritze1602** [chakra-ui/ark#2248]
### Description

**Issue Title:**
Incorrect setting of aria-readonly attributes in RatingGroup component when readOnly parameter is true

**Description:**
Hello,

I have noticed that the RatingGroup component in ArcUI, when used in ReadOnly mode with the `readOnly` parameter set to `true`, sets the ARIA attribute `aria-readonly` on the `<span>` elements. This contradicts the ARIA specifications, as `aria-readonly` should not be applied to non-interactive elements such as `<span>`. At least google and w3c validator downgrade the accessibility score for this.

**Current Behavior:**
- The RatingGroup component sets `aria-readonly` on the `<span>` elements in ReadOnly mode, leading to validation errors.

**Expected Behavior:**
- In ReadOnly mode, `aria-readonly` should not be set on the `<span>` elements.

**Additional Information:**
- ArcUI Version: [ "@ark-ui/react": "^2.0.2",]
 

Thank you!

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/condescending-bush-86l4rq?file=%2Fsrc%2FApp.tsx

### Steps to Reproduce

1. Use the RatingGroup component with the `readOnly` parameter set to `true`.
2. Inspect the generated `<span>` elements and their ARIA attributes.

### Ark UI Version

2.0.2

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
@Fritze1602 

This will be fixed with https://github.com/chakra-ui/zag/commit/def93dffcb2915d918cf002ff94696fa3fb307f1
