### ISSUE TITLE
[React][DatePicker] DatePicker content doesn't close onClick outside 

### ISSUE THREAD

**Issue by Trufflesmld** [chakra-ui/ark#2265]
### Description

When properties lazyMount and unmountOnExit set to true, datePicker content doesn't close onClick outside.
There is this warn in the console
![rep](https://github.com/chakra-ui/ark/assets/70816450/8f9f4a5c-74b4-47ca-a07f-010fe649cdf7)

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/gifted-breeze-x9dmyz?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltcmt0n80007356kohu48ixy%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltcmt0n80002356kee06cla0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltcmt0n80004356kjronps73%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltcmt0n80006356kyiorlnq9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltcmt0n80002356kee06cla0%2522%253A%257B%2522id%2522%253A%2522cltcmt0n80002356kee06cla0%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltcmt0n80006356kyiorlnq9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltcmt0n80005356k7vkc4rck%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltcmt0n80006356kyiorlnq9%2522%252C%2522activeTabId%2522%253A%2522cltcmt0n80005356k7vkc4rck%2522%257D%252C%2522cltcmt0n80004356kjronps73%2522%253A%257B%2522id%2522%253A%2522cltcmt0n80004356kjronps73%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cltcn6loq00fv356kj4cuyxkl%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltcn6loq00fv356kj4cuyxkl%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to Reproduce

1.Set props lazyMount, unmountOnExit to true.
2.Open date picker content with trigger
a warning appears in the console
![rep](https://github.com/chakra-ui/ark/assets/70816450/352e6604-8c02-4eac-8975-554f2db568a8)
3.Click outside the content block (content does not close)

 Expected behavior -  when click outside the content block, he closes

### Ark UI Version

2.2.2

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome

**Comment by cschroeter** [comment]
@Trufflesmld 

Thanks for taking your time. The issue will be resolved with the next update https://github.com/chakra-ui/zag/commit/ffda06f1c30790da1331824f5b0ad6eb86c7dad3
