### ISSUE TITLE
Cannot use @ark-ui/react v2.2.2 in server components with Edge runtime in Next.js

### ISSUE THREAD

**Issue by IzumiSy** [chakra-ui/ark#2266]
### Description

I am getting the following error in using `ark-ui/react` with Edge runtime in Next.js.

```
../../node_modules/.pnpm/@ark-ui+react@2.1.1_@internationalized+date@3.5.2_react-dom@18.2.0_react@18.2.0/node_modules/@ark-ui/react/locale/locale.mjs
Attempted import error: 'useState' is not exported from 'react' (imported as 'useState').
```

![image](https://github.com/chakra-ui/ark/assets/982850/c1bdee4f-fa97-4b82-bd77-394faf6d2ef5)

Is this error expected? I am not sure if @ark-ui/react tries to support Next.js server components or not.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/vigorous-resonance-h2n274

### Steps to Reproduce

Use `@ark-ui/react` without `use client` banner.

### Ark UI Version

2.2.2

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Additional Information

* I have been observing that importing components with subpaths is the only way out like `import  { Switch } from "@ark-ui/react/switch"` instead of `import { Switch } from "@ark-ui/react"`
* Removing `export const runtime = "edge";` also works out

**Comment by cschroeter** [comment]
@IzumiSy 

Thanks for taking your time to create this issue. A fix will be available in `2.2.3`
