### ISSUE TITLE
Dialog's click outside not working across custom element boundary

### ISSUE THREAD

**Issue by aryzing** [chakra-ui/ark#2297]
### Description

The "clicking outside" detection not working when using a `Dialog` inside a custom element (Web Components).

```
[@zag-js/dismissable] node is `null` or `undefined`
```

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/~/github.com/aryzing/repro-click-outside

### Steps to Reproduce

1. Create a custom element that uses Dialog
2. Click outside the dialog

### Ark UI Version

"@ark-ui/solid": "2.2.0"

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
@aryzing 

Thanks for taking your time to report this issue. If you want to work with a different envirionment (Iframe, Shadow DOM, Electron etc) you have to configure the environment. 

Please follow the docs: https://ark-ui.com/docs/components/environment

**Comment by aryzing** [comment]
Thanks @cschroeter for pointing out the Environment docs, very useful. It seems though that `Environment.Root` doesn't exist in `@ark-ui/solid`. Is the example or the types outdated?

**Comment by Omikorin** [comment]
> Thanks @cschroeter for pointing out the Environment docs, very useful. It seems though that `Environment.Root` doesn't exist in `@ark-ui/solid`. Is the example or the types outdated?

It was changed in [2.0.0](https://ark-ui.com/docs/changelog/solid#200---2024-01-30). thanks for pointing out the missing docs!
