### ISSUE TITLE
Tooltip.Arrow does not show up on hover 

### ISSUE THREAD

**Issue by umihai2911** [chakra-ui/ark#2298]
### Description

When i hover the a button wrapped in Tooltip.Trigger the Tooltip.Arrow is not visible( but it exists in DOM ).  

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/sandbox/ark-ui-ng7x6x?file=%2Fsrc%2FApp.js%3A17%2C33

### Steps to Reproduce

[Follow the example from docs for Tooltip.](https://ark-ui.com/docs/components/tooltip#api-reference)

### Ark UI Version

2.2.3

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Arc

### Additional Information

Adding the following in-line style to Tooltip.Arrow solves the problem
```tsx
export default function App() {
  return (
    <div className="App">
      <Tooltip.Root>
        <Tooltip.Trigger>Hover Me</Tooltip.Trigger>
        <Tooltip.Positioner>
          <Tooltip.Content className="test">
            <Tooltip.Arrow
              style={{
                "--arrow-size": "2px",
                "--arrow-background": "red",
              }}
            >
              <Tooltip.ArrowTip />
            </Tooltip.Arrow>
            I am a tooltip!
          </Tooltip.Content>
        </Tooltip.Positioner>
      </Tooltip.Root>
    </div>
  );
}

```

**Comment by acalinica** [comment]
This also happens to me. I had to dig into the underlying [zag.js tooltip machine](https://zagjs.com/components/react/tooltip#styling-the-arrow) dep to figure this out.
