### ISSUE TITLE
[Date Picker] Value does not update the DatePicker.Input values

### ISSUE THREAD

**Issue by dbousamra** [chakra-ui/ark#2301]
### Description

When I supply a value to the DatePicker, I expect the DatePicker.Input components to show the most up to date values.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/sandbox/cranky-shtern-9g7vfm?file=%2Fsrc%2Findex.tsx%3A42%2C1

### Steps to Reproduce

1. Go to the CodeSandbox.
2. Enter in some dates (22/01/1990 to 22/01/1991)
3. Click reset
4. Notice the Input texts remain the same, when they should be removed.

### Ark UI Version

2.2.3

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome

**Comment by dbousamra** [comment]
I've added an even simpler CodeSandbox: https://codesandbox.io/p/sandbox/strange-darkness-xxtm2t

**Comment by cschroeter** [comment]
@dbousamra 

Thanks for taking your time to report this issue. To solve the problem, you have to render the `DatePicker.Input` within the `DatePicker.Control`

```jsx
      <DatePicker.Control>
        <DatePicker.Input index={0} asChild>
          <Input />
        </DatePicker.Input>
        <DatePicker.Input index={1} asChild>
          <Input />
        </DatePicker.Input>
      </DatePicker.Control>
```

**Comment by dbousamra** [comment]
> @dbousamra
> 
> Thanks for taking your time to report this issue. To solve the problem, you have to render the `DatePicker.Input` within the `DatePicker.Control`
> 
> ```js
>       <DatePicker.Control>
>         <DatePicker.Input index={0} asChild>
>           <Input />
>         </DatePicker.Input>
>         <DatePicker.Input index={1} asChild>
>           <Input />
>         </DatePicker.Input>
>       </DatePicker.Control>
> ```

Amazing, thank you. My bad for not reading the example code correctly.
