### ISSUE TITLE
Setting user-select to none for <Slider.Label> when clicking Inside <Slider.Root>

### ISSUE THREAD

**Issue by nix6839** [chakra-ui/ark#2322]
### Description

I expected that the content of `<Slider.Label>` could be dragged and copied. However, `user-select: none` is forcefully set, preventing me from dragging.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/beautiful-wright-y3rdcf?file=%2Fsrc%2FApp.tsx

### Steps to Reproduce

1. Go to reproduction link
2. Drag text "Can't drag this label"
3. You can't drag that

### Ark UI Version

2.2.0

### Framework

- [X] React
- [X] Solid
- [ ] Vue

**Comment by segunadebayo** [comment]
This is an intentional design decision on our part. What's the use case for this scenario?

Here's how you can revert that:
`<Slider.Label style={{userSelect: "unset"}}>Can't drag this label</Slider.Label>`
