### ISSUE TITLE
SolidJS version of Dialog does not include a `defaultOpen` prop as the docs say

### ISSUE THREAD

**Issue by QWu4xYV** [chakra-ui/ark#2325]
### Description

When I tried to use `defaultOpen` on my Dialog in SolidJS, I expected it to be open by default. Instead, I got type errors and the dialog was not open by default.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/cool-river-cqgjkn?file=%2Fsrc%2FApp.tsx%3A1%2C1

### Steps to Reproduce

1. Open the provided link
2. See the type error on `defaultOpen`
3. See that the Dialog is not open

### Ark UI Version

2.2.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

### Browser

Google Chrome

### Additional Information

Thanks so much for making this library; it's been super useful!

If the props differ between frameworks, it would be great if the docs reflected that with tabs, similar to the sample code tabs.

(Also, repro links in different languages would be great! It's not difficult to just use the default SolidJS codesandbox template, but having something directly linked here would be even easier :) )

**Comment by cschroeter** [comment]
@QWu4xYV 

Thanks for taking your time to report this issue. This is fixed with 3ce73357522a63b40782f8de7b27aa83e3486c8e
