### ISSUE TITLE
Checkbox.Control not displaying properly in Solidjs (and React)

### ISSUE THREAD

**Issue by monlovesmango** [chakra-ui/ark#2326]
### Description

when I tested the basic check box example I expected to see a checkbox input with the label of "Checkbox", however I only see the label. When I inspect the elements the checkbox input exists, however it has a height and width of 1 px. It also has an absolute position which overlaps with the label when I try to adjust the height and width. I am using this incorrectly somehow?

seems to have the same issue in react. the reproduction link is using react.

here is the example I was testing:
```tsx
import { Checkbox } from '@ark-ui/solid'

const Basic = () => (
  <Checkbox.Root>
    <Checkbox.Control />
    <Checkbox.Label>Checkbox</Checkbox.Label>
  </Checkbox.Root>
)
```

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/young-paper-rh85g9?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu0kvl4000073b6fi2dbh76t%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu0kvl3z00023b6f7z1vqt6b%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu0kvl4000043b6fmw0es5i4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu0kvl4000063b6fz3h03akb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu0kvl3z00023b6f7z1vqt6b%2522%253A%257B%2522id%2522%253A%2522clu0kvl3z00023b6f7z1vqt6b%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu0kxqvf005n3b6f9dciu7hd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A7%252C%2522endLineNumber%2522%253A17%252C%2522endColumn%2522%253A19%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clu0kxqvf005n3b6f9dciu7hd%2522%257D%252C%2522clu0kvl4000063b6fz3h03akb%2522%253A%257B%2522id%2522%253A%2522clu0kvl4000063b6fz3h03akb%2522%252C%2522activeTabId%2522%253A%2522clu0l80s400cv3b6hey7adlo8%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu0kvl4000053b6fx8d8qy4y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clu0l80s400cv3b6hey7adlo8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clu0kvl4000043b6fmw0es5i4%2522%253A%257B%2522id%2522%253A%2522clu0kvl4000043b6fmw0es5i4%2522%252C%2522activeTabId%2522%253A%2522clu0l69uv00a63b6hfa66hh9y%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu0l69uv00a63b6hfa66hh9y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clu0l6ai0004bdbhr8t6z7oak%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to Reproduce

1. open link
2. "Welcome to Ark" page shows "Checkbox" label with no input

### Ark UI Version

2.2.3

### Framework

- [X] React
- [X] Solid
- [ ] Vue

### Browser

Chrome

**Comment by cschroeter** [comment]
@monlovesmango 

Thanks for taking your time to report this issue. Ark UI is a headless component library meaning we have no opinion how you style a checkbox. You could use the classic check icon with a square or sth completely different. That is the reason you have to style the `Checkbox.Control` 

In our CodeSandBox simply add a `app.css` import it and add the following styles:

```css
[data-scope="checkbox"][data-part="control"] {
  border: 2px solid;
  border-radius: 9999px;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 16px;
  height: 16px;
}

[data-scope="checkbox"][data-part="control"][data-state="checked"] {
  background: black;
  color: white;
}

[data-scope="checkbox"][data-part="control"][data-state="indeterminate"] {
  background: blue;
  color: white;
}
```

You can also bring in Icons etc. Feel free t o check a more visual example here: https://park-ui.com/docs/panda/components/checkbox

**Comment by monlovesmango** [comment]
wow that makes so much more sense! thank you!!
