### ISSUE TITLE
[Combobox][Vue] The combobox close animation is not working.

### ISSUE THREAD

**Issue by L-orz** [chakra-ui/ark#2329]
### Description

The `Combobox` close animation is not displaying correctly because `presenceProps` is not being passed to `Combobox.Content`.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/ark-vue-combobox-animation-rnymsm?file=%2Fsrc%2FApp.vue%3A6%2C34&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu23az6400073b6l5bqmbpc6%2522%252C%2522sizes%2522%253A%255B65.54848966613673%252C34.45151033386327%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu23az6400023b6lqbcovv9b%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu23az6400043b6ljpf7g4jd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu23az6400063b6l7d34gtm2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu23az6400023b6lqbcovv9b%2522%253A%257B%2522id%2522%253A%2522clu23az6400023b6lqbcovv9b%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu23j5a800023b6lyil92yey%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A34%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A34%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clu23j5a800023b6lyil92yey%2522%257D%252C%2522clu23az6400063b6l7d34gtm2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu23az6400053b6lptk44tsm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu23az6400063b6l7d34gtm2%2522%252C%2522activeTabId%2522%253A%2522clu23az6400053b6lptk44tsm%2522%257D%252C%2522clu23az6400043b6ljpf7g4jd%2522%253A%257B%2522id%2522%253A%2522clu23az6400043b6ljpf7g4jd%2522%252C%2522activeTabId%2522%253A%2522clu23az6400033b6l1u0gic2l%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu23az6400033b6l1u0gic2l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%252C%257B%2522id%2522%253A%2522clu23gnp500pl3b6lo93br702%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clu23gnzh009yd8hu61wjd3xk%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to Reproduce

1. Click `Combobox.Input`
2. Content is displayed based on the animation effect
3. Click on other areas
4. Content is hidden directly, the animation is lost

### Ark UI Version

@ark-ui/vue_0.11.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

Chrome

### Additional Information

In the `Vue` version, `presenceProps` are not passed to Combobox.Content
https://github.com/chakra-ui/ark/blob/b5e025723d71364a75d873a4af710c587d949348/packages/frameworks/vue/src/combobox/combobox-content.tsx#L17
https://github.com/chakra-ui/ark/blob/3ce73357522a63b40782f8de7b27aa83e3486c8e/packages/frameworks/react/src/combobox/combobox-content.tsx#L12

**Comment by carwack** [comment]
Thanks for spotting this!
I noticed this on other Vue components as well. Created a PR: #2332 to fix this.
