### ISSUE TITLE
Solid: 3.0

### ISSUE THREAD

**Issue by cschroeter** [chakra-ui/ark#2331]
## Progress

Add `Context` parts and short `TypeDefinitions`:

- [x] Accordion
- [x] Avatar
- [x] Carousel
- [x] Checkbox
- [x] Clipboard
- [x] Collapsible
- [x] Color Picker
- [x] Combobox
- [x] Date Picker
- [x] Dialog
- [x] Editable
- [x] File Upload
- [x] Format
- [x] Hover Card
- [x] Menu
- [x] Number Input
- [x] Pagination
- [x] Pin Input
- [x] Popover
- [x] Progress
- [x] Radio Group
- [x] Rating Group
- [x] Segment Group
- [x] Select
- [x] Slider
- [x] Splitter
- [x] Switch
- [x] Tabs
- [x] Tags Input
- [x] Toast
- [x] Toggle Group
- [x] Tooltip
- [x] Tree View

### Added

- Exposed component-related types to keep imports clean and orderly.

```tsx
import { Avatar } from '@ark-ui/solid';

export const Example = () => {
  // New: Use `Avatar` import to declare types.
  const handleLoadingStatusChange = (details: Avatar.StatusChangeDetails) => {
    console.log(details.status);
  };

  return (
    <Avatar.Root onLoadingStatusChange={handleLoadingStatusChange}>
      <Avatar.Fallback>PA</Avatar.Fallback>
      <Avatar.Image src="https://i.pravatar.cc/300" alt="avatar" />
    </Avatar.Root>
  );
};
```

- Added `Context` components to allow access to the internal machine API. Previously, it was only possible to access the internal API at the root level, which is manageable for small components but could lead to cumbersome composition in larger components. Additionally, this pattern clashed with the `asChild` (`as`) composition pattern we use.

```tsx
export const Basic = () => (
  <Popover.Root>
    <Popover.Trigger>Open</Popover.Trigger>
    <Popover.Positioner>
      <Popover.Context>
        {(api) => (
          <Popover.Content>
            <Popover.Title onClick={() => api().close()}>Title</Popover.Title>
            <Popover.Description>Description</Popover.Description>
          </Popover.Content>
        )}
      </Popover.Context>
    </Popover.Positioner>
  </Popover.Root>
);
```

### Changed

- Refined the current `as` prop implementation. The previous approach had several issues, mostly related to the merging of multiple types (e.g., ButtonProps + DialogTriggerProps + HTMLButtonElement), which resulted in a sluggish and, in some cases, malfunctioning implementation.

```tsx
// before
<Button as={Dialog.Trigger} variant="solid" size="sm">
  Open Dialog
</Button>

// after
<Dialog.Trigger asChild>
  {(props) => (
    <Button
      {...props({ onClick: () => console.log('merge events') })}
      variant="solid"
      size="md"
    >
      Open Dialog
    </Button>
  )}
</Dialog.Trigger>
```

### Removed

- **BREAKING**: Removed the option to access the internal API from various Root components. Use the new `Context` component instead. This change will help in streamlining the `asChild` composition pattern.

**Comment by gurkerl83** [comment]
Same as here https://github.com/chakra-ui/ark/issues/2330#issuecomment-2016607404

**Comment by cschroeter** [comment]
Release coming shortly. Closing
