### ISSUE TITLE
Select with open=true isn't positioned correctly

### ISSUE THREAD

**Issue by Newbie012** [chakra-ui/ark#2347]
### Description

When I try to pass `open={true`} to `<Select />`, the position of the content starts at the top left of the window:

![image](https://github.com/chakra-ui/ark/assets/10504365/6775a113-8d8d-4955-9332-7dee8dc5736c)

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/vitejs-vite-kkgfyk?file=src%2FApp.tsx,src%2Fmain.tsx&terminal=dev

### Steps to Reproduce

1. Go to reproduction link
2. See reproduction

### Ark UI Version

2.2.3

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome

**Comment by cschroeter** [comment]
@Newbie012 

Thanks for taking your time to create this issue. Unfortunately I could not reproduce this issue - not in Firefox nor in Chrome

<img width="294" alt="image" src="https://github.com/chakra-ui/ark/assets/1846056/801820a0-97d1-4403-ac28-01bec7859787">
<img width="299" alt="image" src="https://github.com/chakra-ui/ark/assets/1846056/3160e171-6503-4129-b9f6-1a7d0c628ff2">


Please feel free to create a new issue with another reproduction example.

**Comment by Newbie012** [comment]
@cschroeter thanks for helping out. I've tested it again and it seems more flaky than I thought. It happens more often when I'm stress-testing it with Chrome extensions. Here's a reproduction video:

https://github.com/chakra-ui/ark/assets/10504365/d89db89b-0278-426f-8578-70cc92d2aec6
