### ISSUE TITLE
[Carousel] Issue

### ISSUE THREAD

**Issue by tianchangNorth** [chakra-ui/ark#2351]
### Description

When I use controlled components in vue, the documentation is  
`v-model="index"`
But he's wrong. It should be
`v-model:index="index"`

### Link to Reproduction (or Detailed Explanation)

When I use controlled components in vue, the documentation is   `v-model="index"` But he's wrong. It should be `v-model:index="index"`

### Steps to Reproduce

1. use vue
2.  `<Carousel.Root v-model="index">`

### Ark UI Version

0.11.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

**Comment by cschroeter** [comment]
@tianchangNorth 

Thanks.
