### ISSUE TITLE
Huge bundle size in production build with Next.js

### ISSUE THREAD

**Issue by gurkerl83** [chakra-ui/ark#2353]
### Description

While Next.js does incorporate some optimization strategies, it's important for a library to be utilized in a standardized manner without depending on external optimization techniques. Using other bundlers, such as Vite or esbuild, in place of Next.js's default bundler (SWC), could lead to similar challenges. The core issue under discussion is the size of the bundle produced during a production build with Next.js.

### Link to Reproduction (or Detailed Explanation)

https://github.com/gurkerl83/ark-sandbox

### Steps to Reproduce

The problem can only be observed building the project locally.

Install project dependencies

```
pnpm install
```

Execute the build with bundle analyzer attached

```
pnpm analyze
```

A browser windows opens, next open the sidebar and select the page `app/test/ark/page`.

The in the first image you see other components of ark being included in the output bundle.

![Bundle Size - General Import](https://github.com/chakra-ui/ark/assets/301689/adc82efb-95af-4376-b038-75fcd5b8d632)

Go into the file `app/test/ark/page.tsx` and change the following import declaration of Accordion.

from `import { Accordion } from '@ark-ui/react';`
to `import { Accordion } from '@ark-ui/react/accordion';`

The second image shows only the Accordion component present in the bundle.

![Bundle Size - Specific Import](https://github.com/chakra-ui/ark/assets/301689/fec91831-da66-41ea-b12a-6cbfaf86aeb2)

```

/**
 * Optimizing Bundle Size for `@ark-ui/react` Imports
 *
 * When integrating `@ark-ui/react` components into your project, it's essential
 * to consider the impact on the final bundle size. Below are two different
 * import variants, with their effects on the bundle size:
 *
 * 1. General Import: Using a general import statement like `import { Accordion
 *    } from '@ark-ui/react';` can inadvertently include all components from
 *    `@ark-ui/react` in your final bundle. Bundle analyzers have indicated that
 *    this approach leads to a larger overall size due to the inclusion of
 *    unused components.
 *
 *    Example:
 *    ```
 *    import { Accordion } from '@ark-ui/react'; // This imports all components, increasing bundle size.
 *    ```
 *
 * 2. Specific Import: For a more efficient bundle size, specifically import
 *    only the components you need. For example, `import { Accordion } from
 *    '@ark-ui/react/accordion';` ensures that only the Accordion component (and
 *    its dependencies) are included in your bundle. Bundle analyzers confirm
 *    this method significantly reduces the final bundle size by excluding
 *    unrelated components.
 *
 *    Example:
 *    ```
 *    import { Accordion } from '@ark-ui/react/accordion'; // Only the Accordion component is included.
 *    ```
 *
 * Recommendation: To optimize your application's performance and loading time,
 * prefer using specific imports wherever possible. This practice ensures you're
 * only bundling the components you use, thus minimizing the final bundle size.
 */
```

### Ark UI Version

2.2.3

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

latest

**Comment by cschroeter** [comment]
@gurkerl83 

Thank you for taking the time to create this issue. I'm glad you've identified this issue, but it's not a problem with Ark or the responsibility of other library maintainers. The issue lies with the RSC bundler from Next.js, which unfortunately lacks the capability for tree shaking.

If you move all your content from `test/ark/page.tsx` to a new file named `demo.tsx` and mark this file with `use client`, you will notice that the bundle size remains the same regardless of how you import it. In fact, the reason we use path imports, as you've done in your demo, is precisely because the RSC bundler is inadequate.

```tsx
// components/demo.tsx
'use client';
import { Accordion } from '@ark-ui/react';
import { Accordion } from '@ark-ui/react';
import ChevronDownIcon from 'lucide-react/dist/esm/icons/chevron-down';
import '../styles/ark/accordion-animation.css';
import { Switch } from '@components/ark';

// etc...
```

**Comment by gurkerl83** [comment]
@cschroeter I know this workaround separate file with use client… However the re-export like export * from … in the index.ts on the highest level is causing this. Please reopen.

Thx!

**Comment by cschroeter** [comment]
I am not sure what you mean. Even [Material UI](https://github.com/mui/material-ui/blob/next/packages%2Fmui-base%2Fsrc%2Findex.js) using * exports.

Feel free to open a PR and we will take it from there.

**Comment by gurkerl83** [comment]
@cschroeter 

Yes, Material-UI incorporates this approach. As a contributor who has been involved in a few, yet significant, discussion and design choices, I urge caution. Not every implementation may serve as a best practice. For example, Material-UI is set as the default for optimizing package imports in the Next.js repository at this location: <https://github.com/vercel/next.js/blob/7ebc4b701ce6e1fe1068c033deedd8010b70e5e0/packages/next/src/server/config.ts#L852>.

In my experiments with an alternate export strategy, I found a complete solution to the problem of increased bundle size, even when integrating directly into a RSC. Instead of using the conventional export statements in the root `index.ts` file:

```javascript
export * from './accordion'
export * from './collapsible'
```

Consider this method:

```javascript
export * as Accordion from './accordion'
export * as Collapsible from './collapsible'
```

For the `index.ts` within the accordion folder, do not repeat `export * as Accordion from './accordion'`. Replace the content of this `index.ts` with that of `accordion.ts`.

The same adjustment should be made for the collapsible component.

After building the project and inspecting the `dist` folder's `index.js` file, the output is as follows:

```javascript
import * as index from './accordion/index.js';
export { index as Accordion };
import * as index$1 from './collapsible/index.js';
export { index$1 as Collapsible };
```

This means, when you use `import { Accordion } from '@ark-ui/react';`, the bundler immediately locates the named export `Accordion` in the `index.js` file, avoiding the need to navigate through potentially complex dependency graphs created by indiscriminate exports using `*`. This strategy is effectively identical to using a direct import, such as `import { Accordion } from '@ark-ui/react/accordion';`, directing the bundler to bypass the base `index.js` and directly seek a named export `Accordion` at the specified `accordion` path.

Considering the practical benefits, I intend to propose a pull request for further evaluation in the upcoming days.

Thx!
