### ISSUE TITLE
Checkbox: Property 'Context' does not exist

### ISSUE THREAD

**Issue by KubaZachacz** [chakra-ui/ark#2355]
### Description

When I try to follow example from documentation:
https://ark-ui.com/docs/components/checkbox 
to use Checkbox component with Checkbox.Context
I receive error
`Property 'Context' does not exist on type 'typeof import(".../node_modules/@ark-ui/react/checkbox/checkbox")'.ts(2339)`

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/withered-water-jfqcs8?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clucexmtu0007356nkj1iuukz%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clucexmtu0002356nk3mxrnfy%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clucexmtu0004356nvb62qz4f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clucexmtu0006356nsji5jtaw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clucexmtu0002356nk3mxrnfy%2522%253A%257B%2522id%2522%253A%2522clucexmtu0002356nk3mxrnfy%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clucf14zf0035356ic9kejsel%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A21%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A21%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clucf14zf0035356ic9kejsel%2522%257D%252C%2522clucexmtu0006356nsji5jtaw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clucexmtu0005356nqyvhvcbm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clucexmtu0006356nsji5jtaw%2522%252C%2522activeTabId%2522%253A%2522clucexmtu0005356nqyvhvcbm%2522%257D%252C%2522clucexmtu0004356nvb62qz4f%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clucexmtu0003356nqowtpflj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clucexmtu0004356nvb62qz4f%2522%252C%2522activeTabId%2522%253A%2522clucexmtu0003356nqowtpflj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to Reproduce

Copy code from docs.

`import { Checkbox } from '@ark-ui/react'

const RenderProp = () => (
  <Checkbox.Root>
    <Checkbox.Context>
      {(context) => (
        <Checkbox.Control>
          {context.isChecked && <span>✓</span>}
          {context.isIndeterminate && <span>-</span>}
        </Checkbox.Control>
      )}
    </Checkbox.Context>
    <Checkbox.Label>Checkbox</Checkbox.Label>
  </Checkbox.Root>
)`

### Ark UI Version

2.2.3

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
@KubaZachacz 

Thanks for taking your time to create this issue. The docs already show the upcoming 3.x release. For now just stick to

```jsx
 <Checkbox.Root>
      {(context) => (
      <>
        <Checkbox.Control>
            {context.isChecked && <span>✓</span>}
            {context.isIndeterminate && <span>-</span>}
          </Checkbox.Control>
          <Checkbox.Label>Checkbox</Checkbox.Label>
        </>
      )}

  </Checkbox.Root>
