### ISSUE TITLE
[Date Picker] DatePicker.Context doesn't exist

### ISSUE THREAD

**Issue by h8570rg** [chakra-ui/ark#2357]
### Description

When implemented as shown in the example, DatePicker.Context does not exist.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/optimistic-cohen-xnw3gf?file=%2Fsrc%2FApp.tsx%3A9%2C52

### Steps to Reproduce

1. Go to the CodeSandbox

### Ark UI Version

2.2.3

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome

**Comment by cschroeter** [comment]
@h8570rg

Thanks for taking your time to create this issue. The docs already show the upcoming `v3` version of the `DatePicker`.
For now just fallback to render prop in the the `DatePicker.View` part.

```jsx
<DatePicker.View view="month">
        {(api) => ()}
</DatePickerView>
```

We will aim to release `v3` shortly and already have an idea to keep docs and development in sync.

**Comment by nekoprog** [comment]
Any progress with datepicker in v3?
