### ISSUE TITLE
[Menu] crossAxis offset ignored

### ISSUE THREAD

**Issue by nicompte** [chakra-ui/ark#2361]
### Description

The `crossAxis` property in `Menu` `positioning` seems to be ignored. Updating `mainAxis` has an effect though.
I might have misunderstood its usage, but I'd expect the floating element x coordinates to be updated.

I work with the solid package, but reproduced with react for the reproduction example.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/heuristic-fire-p5gt6k?file=%2Fsrc%2FApp.tsx

### Steps to Reproduce

1. Update the `crossAxis` property
2. Open the menu
3. Has no impact

### Ark UI Version

2.2.0

### Framework

- [X] React
- [X] Solid
- [ ] Vue

### Browser

Firefox 124

**Comment by cschroeter** [comment]
@nicompte 
Thanks for taking your time to report this issue and sorry for the late reply. We've focused on the new version of Ark UI in the last weeks.

Unfortunately I'm unable to start your reproduction example. If you can pick any from the Stackblitz provided at the [getting started](https://ark-ui.com/docs/overview/getting-started) page that would be great.

<img width="768" alt="image" src="https://github.com/chakra-ui/ark/assets/1846056/1044032f-8520-4571-bbac-d46723409418">
