### ISSUE TITLE
React version of Tooltip does not include a defaultOpen prop as the docs say

### ISSUE THREAD

**Issue by raja-OX** [chakra-ui/ark#2362]
### Description

In React version of tooltip defaultOpen props does not exit in root tooltip props

```ts
  <Tooltip.Root lazyMount unmountOnExit defaultOpen={false}>
    <Tooltip.Trigger>Hover Me</Tooltip.Trigger>
    <Tooltip.Positioner>
      <Tooltip.Content>I am a tooltip!</Tooltip.Content>
    </Tooltip.Positioner>
  </Tooltip.Root>
```

### Steps to Reproduce

```ts
  <Tooltip.Root lazyMount unmountOnExit defaultOpen={false}>
    <Tooltip.Trigger>Hover Me</Tooltip.Trigger>
    <Tooltip.Positioner>
      <Tooltip.Content>I am a tooltip!</Tooltip.Content>
    </Tooltip.Positioner>
  </Tooltip.Root>
```

Copy and page the code to get the error in react

### Ark UI Version

2.2.3

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
@raja-OX 

Thanks for taking your time to report this issue. I could not confirm this issue. Please use a code sandbox to help us pin down the potential issue.

<img width="765" alt="image" src="https://github.com/chakra-ui/ark/assets/1846056/013b5d3e-36f4-4d59-a62a-a37ef747a19c">

**Comment by RajaARK99** [comment]
@cschroeter Thanks for the replay i attach the code sandbox link below 


if the code sandbox opened in brave browser i will get error. If i open it in Firefox i didn't also it not work in local development i get error.

<img width="577" alt="Screenshot 2024-04-04 231145" src="https://github.com/chakra-ui/ark/assets/123263663/353752fe-398a-4efd-b36c-8c6afb7b1050">


[Codesandbox lint](https://codesandbox.io/p/devbox/pedantic-babbage-d42dc4?file=%2Fsrc%2FApp.tsx%3A11%2C22&workspaceId=560dc4be-82cd-4a92-bc0c-3bf608cc8f13)

**Comment by segunadebayo** [comment]
@cschroeter I recently added this to the Tooltip component, but it’s not yet released.

I believe it should be part of v3
