### ISSUE TITLE
 @ark-ui/solid 3.0.0-0 npm package no content

### ISSUE THREAD

**Issue by FlatMapIO** [chakra-ui/ark#2373]
### Description

I tested installation using pnpm and bun separately, and after downloading, the package only contains a package.json file.

<img width="438" alt="image" src="https://github.com/chakra-ui/ark/assets/1720349/a1588d37-3699-4b1c-9f44-c2a5aa72181d">

### Link to Reproduction (or Detailed Explanation)

NO

### Steps to Reproduce

NO

### Ark UI Version

3.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
@FlatMapIO 

Thanks for taking your time to report this issue. Fixed in [3.0.0-1](https://github.com/chakra-ui/ark/releases/tag/%40ark-ui%2Fsolid%403.0.0-1)
