### ISSUE TITLE
Pagination context is not exported from the Pagination file

### ISSUE THREAD

**Issue by Pherwerz** [chakra-ui/ark#2404]
### Description

when i copy the example from the docs i expected it to work fine without any issue, but then i notice Pagination.context is not exported from the pagination file

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/sandbox/beautiful-night-wk9fdz

### Steps to Reproduce

just check the codesandbox

### Ark UI Version

2.2.3

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by Reverier-Xu** [comment]
I also met this problem, how do you solve this?

**Comment by efitzkiwi** [comment]
> I also met this problem, how do you solve it?

You can do like so:
`import {
    Pagination as ArkPagination, PaginationContext
} from "@ark-ui/react";`

**Comment by efitzkiwi** [comment]
But technically the pagination context provider is included in the root element, maybe the docs need updating
```
import {
    Pagination as ArkPagination
} from "@ark-ui/react";


// example usage of wrapping root with a forward ref nav component
const Pagination = React.forwardRef<
    React.ElementRef<typeof ArkPagination.Root>,
    React.ComponentPropsWithoutRef<typeof ArkPagination.Root>
>(({ className, children, ...props }, ref) => (
    <ArkPagination.Root ref={ref} {...props} asChild>
      {(ctx) => (
        <nav
            role="navigation"
            aria-label="pagination"
            className={cMerge("mx-auto flex w-full justify-center", className)}
        >
          {typeof children === "function" ? children(ctx) : children}
        </nav>
      )

      }
    </ArkPagination.Root>
));
Pagination.displayName = "Pagination";

```

**Comment by Reverier-Xu** [comment]
thanks!

**Comment by Pherwerz** [comment]
> I also met this problem, how do you solve it?

i updated the package to version 3

**Comment by cschroeter** [comment]
Yes the docs show the latest version of Ark. Please use v3 or v1 respectively. We plan to release a new version shortly.
