### ISSUE TITLE
[Toast] Impossible to update a toast programmatically

### ISSUE THREAD

**Issue by fseglard** [chakra-ui/ark#2408]
### Description

Hi!

When using the programmatic control to dynamically update a toast (`toast.update`, `toast.upsert`, etc.), it simply does not work.

I've tried to do the same thing on Zag, and it's working fine.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/pedantic-hodgkin-97ws5c?file=%2Fsrc%2FApp.tsx%3A23%2C5

### Steps to Reproduce

1. Create a new toast by clicking the "create new toast" button
2. While the new toast is displayed, click on the "update latest" button
3. The current toast's title should be updated but it is not 

### Ark UI Version

2.2.3 and 3.0.0-0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome 123

**Comment by fseglard** [comment]
Ah thanks @cschroeter!

Sorry for this false-positive, I should have checked directly on the main branch...

Anyway, thanks for the quick reply and awesome work :heart:

**Comment by cschroeter** [comment]
It was just added today so no worries :D
