### ISSUE TITLE
[Toast] Issue - Story not available

### ISSUE THREAD

**Issue by Manviel** [chakra-ui/ark#2411]
### Description

When I try to run the example, I expected the Toast to be displayed, but instead I get an error.

```
 SyntaxError: The requested module '/node_modules/.vite/deps/@ark-ui_react.js?t=1713537708271&v=d7e29ef0' does not provide an export named 'Toaster'
 ```

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/dawn-shape-rx2y37?file=%2Fsrc%2FApp.tsx

### Steps to Reproduce

1. Go to https://ark-ui.com/docs/components/toast
2. Copy paste example.
3. Compile it.

### Ark UI Version

2.2.0

### Framework

- [X] React
- [X] Solid
- [ ] Vue

### Browser

Chrome 124

### Additional Information

Looks like the Docs is outdated.

**Comment by cschroeter** [comment]
@Manviel 

Thanks mate. We re-wrote the toast api - docs will follow shortly. in the meantime check the code https://github.com/chakra-ui/ark/blob/main/frameworks/react/src/components/toast/examples/basic.tsx
