### ISSUE TITLE
[Docs][Carousel] Typo in the example section

### ISSUE THREAD

**Issue by Theo-Rige** [chakra-ui/ark#2421]
### Description

There is a typo in the Examples section :
"Learn how to use the _**Caorusel**_ component in your project. Let’s take a look at the most basic example:"
should be
"Learn how to use the _**Carousel**_ component in your project. Let’s take a look at the most basic example:",
the "o" and the "r" are inverted.

### Link to Reproduction (or Detailed Explanation)

https://ark-ui.com/docs/components/carousel

### Steps to Reproduce

1. Go to https://ark-ui.com/docs/components/carousel
2. Scroll to the **Examples** section

### Ark UI Version

3.0.0

### Framework

- [X] React
- [X] Solid
- [X] Vue

### Browser

All

**Comment by carwack** [comment]
Thanks for noticing: I created a PR to fix this: #2424
