### ISSUE TITLE
`Select` component `defaultValue` prop doesn't work

### ISSUE THREAD

**Issue by shirshendubhowmick** [chakra-ui/ark#2431]
### Description

While passing the `defaultValue` prop to `Select.Root` doesn't work as expected and also result in a type error.

```
Property 'defaultValue' does not exist on type 'IntrinsicAttributes & SelectRootProps<{ value: string; label: string; }>'.
```

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/sandbox/solid-counter-forked-6prcnt?file=%2Findex.tsx%3A36%2C1

### Steps to Reproduce

Use any example of `Select` component (Solid JS) given in the doc and try to use the `defaultValue` prop as suggested in the document.

### Ark UI Version

2.2.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

### Browser

Google Chrome

**Comment by cschroeter** [comment]
@shirshendubhowmick 

Thanks for taking your time to report this issue. There was an issue with our scripts that parses the type docs.

Please note that Solid.js don't require a defaultValue. You simply can use the `<Select value={["foo"]} />`
