### ISSUE TITLE
solid/treeview example does not work

### ISSUE THREAD

**Issue by georgfaust** [chakra-ui/ark#2441]
### Description

The treeview for solid does nothing.

I did

```
npx degit solidjs/templates/js solid-ark-treeview-issue
solid-ark-treeview-issue$ npm install @ark-ui/solid
# paste solid-example from here: https://ark-ui.com/docs/components/tree-view
npm run dev
```

clicking on a node does **not** expand the tree.

### Link to Reproduction (or Detailed Explanation)

https://github.com/georgfaust/solid-ark-treeview-issue

### Steps to Reproduce

1. clone repo, npm i, npm run dev
2. click on a node

### Ark UI Version

2.2.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

### Browser

chrome, firefox

**Comment by cschroeter** [comment]
@georgfaust 

Thanks for taking your time to report this issue. The docs show the code snippets for the latest release.  (3.0.0-2)
I've added an example for you to look at here: https://stackblitz.com/github/chakra-ui/ark/tree/main/templates/solid/solid-start?file=src/components/tree-view.tsx

**Comment by ahsf** [comment]
thanks for the pointer.

getting started guide says to do

```
npm install @ark-ui/solid
```

which installs

```
"node_modules/@ark-ui/solid": {
    "version": "2.2.0",
```

so this is a little misleading.

**Comment by cschroeter** [comment]
Yes indeed. But it is pretty much stable and we plan to release the new major shortly.
