### ISSUE TITLE
[Combobox] [React] The value is not set to the input when the value changes outside the element

### ISSUE THREAD

**Issue by Trufflesmld** [chakra-ui/ark#2454]
### Description

When i set combobox value outside element, input does not display new value

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/sandbox/mystifying-neumann-cxkqr7

### Steps to Reproduce

1.Click on button "set value to "Solid" outside"
value is updated, but display old value

### Ark UI Version

2.2.3

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome

**Comment by cschroeter** [comment]
@Trufflesmld 

Thanks for taking your time to report this issue. Unfortunately the Sandbox is not available to me. If you have some time you could use our latest [Stackblitz (Next.js)](https://stackblitz.com/github/chakra-ui/ark/tree/main/templates/react/next-js) for a reproduction.

Thanks for your help

<img width="760" alt="image" src="https://github.com/chakra-ui/ark/assets/1846056/47873fcd-603d-43d3-8629-e1bdd9afdbbe">

**Comment by Trufflesmld** [comment]
Sorry, here is the correct link
https://codesandbox.io/p/devbox/mystifying-neumann-cxkqr7?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clw1zas5p0007356l7jctu318%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clw1zas5p0002356l14kpqvbv%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clw1zas5p0004356llvb35l55%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clw1zas5p0006356ld9tdn47r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clw1zas5p0002356l14kpqvbv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw1zas5o0001356lh0ktfusa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clw1zas5p0002356l14kpqvbv%2522%252C%2522activeTabId%2522%253A%2522clw1zas5o0001356lh0ktfusa%2522%257D%252C%2522clw1zas5p0006356ld9tdn47r%2522%253A%257B%2522id%2522%253A%2522clw1zas5p0006356ld9tdn47r%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw1zas5p0005356lv5ltj69b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clw1zas5p0005356lv5ltj69b%2522%257D%252C%2522clw1zas5p0004356llvb35l55%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw1zas5p0003356lgovgsk62%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clw1zas5p0004356llvb35l55%2522%252C%2522activeTabId%2522%253A%2522clw1zas5p0003356lgovgsk62%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by cschroeter** [comment]
@Trufflesmld 

To achieve this behavior you have to sync the Combobox Input with the value

```jsx
  <Combobox.Input value={value} />
  ```
