### ISSUE TITLE
There is no license and contribution file.

### ISSUE THREAD

**Issue by cosmoart** [chakra-ui/ark#2455]
### Description

License and contribution files do not exist. The links in the README direct to a 404 error page.

![image](https://github.com/chakra-ui/ark/assets/81999801/7baf2759-3036-4252-8a74-39d02634d5b1)
![image](https://github.com/chakra-ui/ark/assets/81999801/053d93f2-0e89-40db-b3c1-942c2ef7eac9)
![image](https://github.com/chakra-ui/ark/assets/81999801/893c1cc1-f11d-4b6f-b5bb-d404acb23de1)

### Link to Reproduction (or Detailed Explanation)

Go to the README footer and check the links in the contribution and license section.

### Steps to Reproduce

- Go to the README footer
- Go to the links provided in the contribution and license section

### Ark UI Version

1

### Framework

- [ ] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
@cosmoart 

Thanks
