### ISSUE TITLE
bug: datepicker format prop not working as expected

### ISSUE THREAD

**Issue by LuckySharma014** [chakra-ui/ark#2466]
### Description

We wanted to change the input format for the date picker to `dd/mm/yyyy`. we used the `format` prop to change the display format on the input. It works as expected until we choose a date between 1 - 12 of any month, it automatically swap's the date with month.

Example -
27/05/2024 -> 27/05/2024 (As expected)
03/05/2024 -> 05/03/2024 (Swap month and date)

I tried this in multiple PCs and browsers but same results. The behavior I want is to show the date in different format not necessarily in `dd/mm/yyyy` but it could be a string like `Tue 14 May 2024`, etc.

Attached below link is for the storybook docs where you can see it in action. Try choosing the dates in the example. If you want to see the implementation you can check it out
- [rafty/ui](https://github.com/rhinobase/raftyui) Repo
- [Storybook](https://github.com/rhinobase/raftyui/blob/merge/packages/ui/src/date-picker/date-picker.stories.tsx) file
- [DatePicker](https://github.com/rhinobase/raftyui/blob/merge/packages/ui/src/date-picker/DatePicker.tsx) file

### Link to Reproduction (or Detailed Explanation)

https://raftyui-storybook-git-merge-rhinobase.vercel.app/?path=/story/form-datepicker--default

### Steps to Reproduce

Here is the basic implementation in the storybook -

```tsx
<DatePicker format={(date) => `${date.day}/${date.month}/${date.year}`} />
```

### Ark UI Version

3.0.0-1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

All browsers

**Comment by segunadebayo** [comment]
The `format` prop has been deprecated in favor of controlling it via the `LocaleProvider`. We'll add some docs to show this shortly.

I recommend not using an input for this use case and only the date picker's trigger and content. That way you can format what you show within the button.

**Comment by obedm503** [comment]
@segunadebayo What if I need to parse/format dates in some arbitrary way regardless of the locale?

In my case, we let users determine their date format. I need some way to hook into the parsing/formatting process without messing with the locale.
