### ISSUE TITLE
[Combobox] [React] The value is not set to the input when the value changes outside the element 

### ISSUE THREAD

**Issue by Trufflesmld** [chakra-ui/ark#2468]
### Description

When i set combobox value outside element, input does not display new value

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/github-vhxgul?file=src%2Fcomponents%2Favatar.tsx

### Steps to Reproduce

1.Click on button "set value to "Solid" outside"
value is updated, but display old value

### Ark UI Version

3.0.0-1

### Framework

- [x] React
- [ ] Solid
- [ ] Vue

**Comment by segunadebayo** [comment]
Good catch @Trufflesmld.

This has been fixed in Zag.js. In the next release of Ark, it should be fixed.
