### ISSUE TITLE
Menu closes on its own without clicking outside

### ISSUE THREAD

**Issue by wyllen** [chakra-ui/ark#2471]
### Description

When using the menu component with nested menus, sometimes it closes on its own without clicking outside.
![menu-close-itself](https://github.com/chakra-ui/ark/assets/2247589/54647d06-1548-4ffa-af8d-67241e204e5d)

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/goofy-aj-kjrd6m

### Steps to Reproduce

Open the menu and quickly move from bottom to top across the various menu items.

### Ark UI Version

2.2.3

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome

**Comment by cschroeter** [comment]
@wyllen 

Thanks for taking your time to create the issue. Please use `@ark-ui/react@3.0.0-2`  we will release 3.0 soon. This should be  the final RC

**Comment by wyllen** [comment]
@cschroeter  Same thing with 3.0 ☹️

**Comment by cschroeter** [comment]
@wyllen  You may want to dbl check with our storybook examples

Uploading Bildschirmaufnahme 2024-05-16 um 23.04.23.mov…
