### ISSUE TITLE
Can't press space while typing in Input inside Select.Content

### ISSUE THREAD

**Issue by Newbie012** [chakra-ui/ark#2478]
### Description

I have a `Select` component with the option to search for`Select.Item`s inside the `Select.Content` (unlike `Combobox` which is the opposite UX):

<img width="264" alt="image" src="https://github.com/chakra-ui/ark/assets/10504365/7d1fbb99-b293-4928-b11b-99490ac59b9d">

The issue is that I'm unable press Space while I'm typing (since the event is superseded by the `Select.Content` for selecting a highlighted value). I tried to `stopPropagation` and `preventDefault` on change, but no success.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/throbbing-star-qdywyc?file=%2Fsrc%2FApp.tsx%3A6%2C11

### Steps to Reproduce

1. Click on the "Select a Fruit" button
2. Type in the input field with space
3. See issue

### Ark UI Version

3.0.0-2

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome

### Additional Information

The reason why I'm not using a Combobox is because I don't want the search to be the default interaction. In fact, in my code the search is displayed conditionally.

The reason why I'm not using a simple popover is because I still need most of the Select's API.

---

PS - Building UI components with Ark is a breeze. The attention to details is very noticeable. Thanks for such an awesome library!

**Comment by cschroeter** [comment]
@Newbie012 

You need to use disable `composite` here.

https://ark-ui.com/docs/react/components/select#api-reference

We will add more examples later down the road.

**Comment by Newbie012** [comment]
Thanks for the quick response.

Even after I passed `composit={false}` on `Select.Root` it didn't fix it. After doing some digging, I found out that my `onChange` callback was superseded by zag's `onKeyDown`:

https://github.com/chakra-ui/zag/blob/24e5fada5c63d8cbe85cefa733fe67f2b560d2e5/packages/machines/select/src/select.connect.ts#L167-L171

Passing `onKeyDown={e => e.stopPropagation()}` did the trick.
