### ISSUE TITLE
@ark-ui/solid does not work on Firefox

### ISSUE THREAD

**Issue by helgardferreira** [chakra-ui/ark#2482]
### Description

When I install @ark-ui/solid and run my Solid app, I expected the application to render in Firefox but it currently doesn't.

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/github/chakra-ui/ark/tree/main/templates/solid/solid-start

### Steps to Reproduce

1. Go to the linked stackblitz on Firefox (the same stackblitz from the docs for Solid Start)
2. Wait for the application to initialise and note that the UI does not render.
<img width="1171" alt="image" src="https://github.com/chakra-ui/ark/assets/39649820/f74a8240-bec5-4f42-a107-b251d6879194">

### Ark UI Version

3.0.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

### Browser

Firefox

**Comment by segunadebayo** [comment]
Thanks for reporting this @helgardferreira

I've commented out all the Ark-specific code, and the app still doesn't render.

This appears to be a Solid Start + Firefox issue. This isn't an Ark issue, kindly file an issue in the Solid Start repo

**Comment by helgardferreira** [comment]
Hi @segunadebayo, this is definitely a problem with either @ark-ui/solid or a dependency of @ark-ui/solid. I see stackblitz is on the fritz but if you create a brand new Solid project and install @ark-ui/solid you'll see the issue locally on your machine as well 😐

**Comment by cschroeter** [comment]
<img width="433" alt="image" src="https://github.com/chakra-ui/ark/assets/1846056/0729bc6c-d7f6-4e3d-8810-34f0e6d00bbe">

Looks like something with Stackblitz. Works locally.
