### ISSUE TITLE
Date picker is not working correctly when datePicker.clearValue() is triggered

### ISSUE THREAD

**Issue by AbdallahMezo** [chakra-ui/ark#2491]
### Description

When I try to control date picker selected value based on a prop, it doesn't work as expected. 

Navigating between months, views are not working if clearValue is triggered

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/sandbox/ark-date-picker-bug-8j9xzf

### Steps to Reproduce

Switch the state to be false

Try to navigate between months

### Ark UI Version

latest

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
@AbdallahMezo 

After you have cleared the value, you need to reset `value`. Otherwise you will always clear the value. You can verify this by adding a log line be fore

```jsx
console.log("clearing value")
 datePicker.clearValue()
 ```
