### ISSUE TITLE
Arrow up and down not working on Menu and Select

### ISSUE THREAD

**Issue by rin-yato** [chakra-ui/ark#2494]
### Description

When I was trying out menu and select, I expected the arrow up and down to navigate through the item, but nothing happened and it scrolled the page down instead

### Link to Reproduction (or Detailed Explanation)

https://ark-ui.com/react/docs/components/menu

### Steps to Reproduce

1. Go to menu or select component in the ark doc
2. Try to open the menu
3. Try to use arrow up and down to navigate

### Ark UI Version

3.0.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Arc

**Comment by cschroeter** [comment]
@rin-yato 

Thank you for reporting this issue. A fix is available in `@ark-ui/react@3.0.2`.
