### ISSUE TITLE
📌 Contribute to Ark UI: Components Ready for Implementation

### ISSUE THREAD

**Issue by cschroeter** [chakra-ui/ark#2497]
## Welcome Contributors!

Thank you for your interest in contributing to Ark UI! Below is a list of components that are available for implementation. If you're looking to make a meaningful contribution, this is a great place to start.

### Available Components

| Component      | Link                                                                                          | Status       | PR/Contributor |
| -------------- | --------------------------------------------------------------------------------------------- | ------------ | -------------- |
| Floating Panel | [Floating Panel](https://github.com/chakra-ui/zag/tree/main/packages/machines/floating-panel) | In Progress  | @mverissimo    |
| Signature Pad  | [Signature Pad](https://github.com/chakra-ui/zag/tree/main/packages/machines/signature-pad)   | ✅ Completed | @jeferson-sb   |
| Steps          | [Steps](https://github.com/chakra-ui/zag/tree/main/packages/machines/steps)                   | ✅ Completed | @segunadebayo  |
| Time Picker    | [Time Picker](https://github.com/chakra-ui/zag/tree/main/packages/machines/time-picker)       | ✅ Completed | @colinlienard  |
| Timer          | [Timer](https://github.com/chakra-ui/zag/tree/main/packages/machines/timer)                   | In Progress  | @jeferson-sb   |

### How to Get Started

1. **Check the Component's Status**: Ensure the component you want to work on is marked as "Not Started."
2. **Comment Below**: Express your interest in implementing the component by leaving a comment.
3. **Fork the Repository**: Make a fork of the Ark UI repository to start working on your component.
4. **Implement the Component**: Look up existing components in the repository and follow their blueprint to maintain consistency.
5. **Submit a Pull Request**: Once done, submit a pull request for review.

**Happy coding! 🚀**

**Comment by jeferson-sb** [comment]
I would like to take a shot on the Signature Pad

**Comment by jeferson-sb** [comment]
hey can I work on the Timer as well?

**Comment by colinlienard** [comment]
Hey, I would like to continue my work on the time picker here

**Comment by segunadebayo** [comment]
Thanks to everyone who contributed so far. We'll focus on getting the draft PRs in the next weeks.
