### ISSUE TITLE
[Solid][DatePicker] Range date picker auto close

### ISSUE THREAD

**Issue by hngngn** [chakra-ui/ark#2509]
### Description

When using the DatePicker in "range" mode, if I select the first date and then hover over other dates very quickly, the content automatically closes. This doesn't happen when I hover slowly.

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/github-9peyjg?file=src%2Froutes%2Findex.tsx

### Steps to Reproduce

1. Open Range Date Picker
2. Click once
3. Hover slowly or fast around other dates

### Ark UI Version

3.0.2

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

### Browser

Ark Browser

### Additional Information

https://github.com/chakra-ui/ark/assets/97839073/42a810e6-401a-4bf1-8ede-d7fed329bffe

**Comment by cschroeter** [comment]
@hngngn 

Thanks for reporting the issue. The issue should be fixed in `3.1`
