### ISSUE TITLE
Bug: Multiple choice combobox input is empty even if there are selected values

### ISSUE THREAD

**Issue by arekmaz** [chakra-ui/ark#2535]
### Description

When I follow the [Advanced Customisation example](https://ark-ui.com/react/docs/components/combobox#:~:text=%3E%0A%20%20\)%0A%7D-,Advanced%20Customization,-Extended%20example%20that) the input is empty after choosing any options.

The single combobox input works fine, the context has the correct value, so the only issue is displaying multiple values in the input by default.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/sandbox/hidden-mountain-8nrnmc?file=%2Fsrc%2FRepro.tsx%3A14%2C7

### Steps to Reproduce

1. go to https://codesandbox.io/p/sandbox/hidden-mountain-8nrnmc?file=%2Fsrc%2FRepro.tsx%3A11%2C1-12%2C1
2. click on the "Bug repro ..." combobox "open" button
3. select some options
4. the input is empty, and should show chosen options

### Ark UI Version

3.2.0 and 3.2.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

google chrome 125 macos

**Comment by aguilera51284** [comment]
i have de same problem :/
