### ISSUE TITLE
Class 'toast__root' not applied to Toast.Root in Solid

### ISSUE THREAD

**Issue by spaaacetoast** [chakra-ui/ark#2551]
### Description

The solid version of the toast component doesn't apply the toast__root class to its root. I've made a repo where you can check it out including a changed root that does work!

Main difference is changing div to ark.div and merging the incoming props
original:
```
export const ToastRoot = (props: ToastRootProps) => {
  const toast = useToastContext()
  return (
    <div {...toast().getRootProps()}>
      <div {...toast().getGhostBeforeProps()} />
      {props.children}
      <div {...toast().getGhostAfterProps()} />
    </div>
  )
}
```

fixed:
```
const RootFixed = (props: RootFixedProps) => {
  const toast = useToastContext();
  const mergedProps = mergeProps(() => toast().getRootProps(), props);

  return (
    <ark.div {...mergedProps}>
      <ark.div {...toast().getGhostBeforeProps()} />
      {props.children}
      <ark.div {...toast().getGhostAfterProps()} />
    </ark.div>
  );
};
```

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/github/spaaacetoast/ark-toast/main?import=true&embed=1&file=%2Fsrc%2Fcomponents%2Ftoast-fixed.tsx

### Steps to Reproduce

Click add toast and than click add fixed toast and see the difference

### Ark UI Version

3.2.1

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

**Comment by segunadebayo** [comment]
Good catch @spaaacetoast

The main fix was merging the incoming props. We intentionally don't use `ark.div` here due to the fact that it has the ghost (before and after) built-in, which will mess up the `asChild` prop.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by spaaacetoast** [comment]
That makes sense with the ghost elements! Thanks for the quick response and fix :))
