### ISSUE TITLE
Menu opening and closing issues (focus related)

### ISSUE THREAD

**Issue by arekrgw** [chakra-ui/ark#2554]
### Description

I have two Menu components next to each other, when I open first the click the trigger of the second one, both closes. 

It happens only with touch devices on mobile see the example.

https://github.com/chakra-ui/ark/assets/34128433/1688e337-0619-468f-bfaa-5422db63915d

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/g54m63?migrateFrom=pzq4mr

### Steps to Reproduce

1. Go to reproduction link
2. Switch to mobile view like on the video
3. Open first menu
4. Click on trigger of second menu
5. Both menu closes with flash of second menu

### Ark UI Version

3.2.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome

**Comment by segunadebayo** [comment]
Thanks for reporting this @arekrgw,

I pushed a fix for this in [Zag.js](https://github.com/chakra-ui/zag/commit/5c1ff93c2039d81f9ae7b321701bd52163c26867).

We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
