### ISSUE TITLE
[Dialog] [React] Backdrop presence not being inherited from root prop

### ISSUE THREAD

**Issue by carloitaben** [chakra-ui/ark#2555]
### Description

I encountered an inconsistency while using Framer Motion's `AnimatePresence` with the `Dialog` component. I'm new to the library, so I'm unsure if this behavior is intentional. I'm reporting it just in case 🙂

The `presence` prop functions as expected for every `Dialog` component except `Backdrop`. 

While `Dialog.Positioner` and `Dialog.Content` handle it [like this](https://github.com/chakra-ui/ark/blob/main/packages/react/src/components/dialog/dialog-content.tsx#L10-L16):

```tsx
const dialog = useDialogContext()
const presence = usePresenceContext()
const mergedProps = mergeProps(dialog.getContentProps(), presence.getPresenceProps(ref), props)

if (presence.unmounted) {
  return null
}
```

`Dialog.Backdrop` handles it [differently](https://github.com/chakra-ui/ark/blob/main/packages/react/src/components/dialog/dialog-backdrop.tsx#L11-L18):

```tsx
const dialog = useDialogContext()
const renderStrategyProps = useRenderStrategyPropsContext()
const presence = usePresence({ ...renderStrategyProps, present: dialog.open })
const mergedProps = mergeProps(dialog.getBackdropProps(), presence.getPresenceProps(ref), props)

if (presence.unmounted) {
  return null
}
```

The issue here is that, while the first components read `presence` from the `Dialog.Root` `PresenceProvider`, `Dialog.Backdrop` doesn't.

When changing the `Dialog.Backdrop` code to behave like `Dialog.Positioner` and `Dialog.Content`, everything seems to work perfectly. I've opened https://github.com/chakra-ui/ark/pull/2556 with this change in case you want to check it out 👀

In the reproduction I'm wrapping the `Dialog.Positioner` with `Dialog.Backdrop` as that's how I do it with Radix. Note that the issue persist even when rendering the `Dialog.Positioner` and `Dialog.Backdrop` as siblings.

PS: I really love all of your projects! Kudos to the Chakra team!

### Link to Reproduction (or Detailed Explanation)

[See Reproduction](https://codesandbox.io/p/devbox/focused-almeida-86xd8z?workspaceId=07066b7d-91c0-4e1c-98c1-6831a1723b49&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxca6u9z00053b6jy9omt0he%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxca6u9z00023b6j9u2i8wul%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxca6u9z00033b6jtusd79nc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxca6u9z00043b6jdnldy20e%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxca6u9z00023b6j9u2i8wul%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxca6u9y00013b6jraw7zp58%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxca87oa004o3b6j3jca1zw0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A23%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A24%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxca6u9z00023b6j9u2i8wul%2522%252C%2522activeTabId%2522%253A%2522clxca87oa004o3b6j3jca1zw0%2522%257D%252C%2522clxca6u9z00043b6jdnldy20e%2522%253A%257B%2522id%2522%253A%2522clxca6u9z00043b6jdnldy20e%2522%252C%2522activeTabId%2522%253A%2522clxcaebc0007j3b6imwi03fs9%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clxcaebc0007j3b6imwi03fs9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clxca6u9z00033b6jtusd79nc%2522%253A%257B%2522id%2522%253A%2522clxca6u9z00033b6jtusd79nc%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clxca77et002u3b6jv55leh2y%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxca77et002u3b6jv55leh2y%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to Reproduce

1. Open the Dialog without Backdrop
2. The opening animation should play
3. Close the Dialog without Backdrop
4. The closing animation should play
5. Open the dialog with Backdrop
6. The opening animation should play
7. Close the Dialog with Backdrop
8. The Dialog unmounts before Framer Motion gets to animate it

### Ark UI Version

3.3.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome, Version 125.0.6422.142 (Official Build) (arm64)

### Additional Information

Here's a video of the issue 🙂

https://github.com/chakra-ui/ark/assets/48155434/d6e2deae-f665-4c2a-b164-32e93395b523

**Comment by segunadebayo** [comment]
We designed it this way to allow for animating the backdrop with a different timeline compared to the content.

When composing with framer-motion, I'd recommend skipping the backdrop entirely and rendering your custom version. These components were built to be animated with CSS animations.

```jsx
const DialogWithBackdrop = () => {
  const [open, setOpen] = useState(false);
  return (
    <Dialog.Root
      lazyMount
      present
      open={open}
      onOpenChange={(event) => setOpen(event.open)}
    >
      <Dialog.Trigger>Open dialog with backdrop (broken)</Dialog.Trigger>

      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 1.5 }}
          />
        )}
      </AnimatePresence>

      <AnimatePresence initial={false}>
        {open && (
          <Dialog.Positioner asChild>
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              exit={{ scale: 0 }}
              transition={{ duration: 2 }}
            >
              <Dialog.Content>
                <Dialog.Title>Dialog Title</Dialog.Title>
              </Dialog.Content>
            </motion.div>
          </Dialog.Positioner>
        )}
      </AnimatePresence>
    </Dialog.Root>
  );
};
```

https://codesandbox.io/p/devbox/ark-framer-composition-4c3mmd?file=%2Fsrc%2FApp.tsx%3A13%2C6
