### ISSUE TITLE
`asChild` is not working for inputs

### ISSUE THREAD

**Issue by Andrewnt219** [chakra-ui/ark#2559]
### Description

Hi team, I have a problem with using `asChild` for `<PinInput.Input />` in `@ark-ui/vue`.

The same problem can be found for `NumberInput.Input`.

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/vitejs-vite-12ccu7?file=src%2FApp.vue

### Steps to Reproduce

1. Copy the first example of PinInput from https://ark-ui.com/react/docs/components/pin-input
2. Use native `<input />` + `asChild` for `<PinInput.Input />` or `<PinInput.HiddenInput />`

Expect: input to be rendered.
Actual: nothing is rendered

### Ark UI Version

3.4.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

Chrome v125

**Comment by Andrewnt219** [comment]
Tested with `<ark.input />`. Seem like we need to specify a slot inside PinInput.Input.

**Comment by Andrewnt219** [comment]
Hi @cschroeter, do you want me to raise a PR for this? It seems like just adding a slot here would do the trick.
https://github.com/chakra-ui/ark/blob/45265f386eba777117b14f357d4192c5b4d7aed0/packages/vue/src/components/pin-input/pin-input-input.vue#L24

**Comment by segunadebayo** [comment]
@Andrewnt219 Feel free to open a PR

**Comment by cschroeter** [comment]
@segunadebayo @Andrewnt219 

Thanks for taking your time to report the issue. I could reproduce the issue. A fix will be in the next release.
