### ISSUE TITLE
signature-pad package dependency missing from ark's solid package.json

### ISSUE THREAD

**Issue by ownw** [chakra-ui/ark#2564]
### Description

Hi, I'm using yarn with pnp (strict option), if a transitive dependency is not specified in a package.json I get an error (build fails).

[solid's package.json](https://github.com/chakra-ui/ark/blob/main/packages/solid/package.json) is missing the `@zag-js/signature-pad` dependency

```sh
[ERROR] [vite] x Build failed in 7.43s
[vite]: Rollup failed to resolve import "@zag-js/signature-pad" from "/home/user/code/project/.yarn/__virtual__/@ark-ui-solid-virtual-54296489ec/0/cache/@ark-ui-solid-npm-3.3.0-3c88a6e1ec-335446c5e6.zip/node_modules/@ark-ui/solid/dist/source/components/signature-pad/use-signature-pad.js".
This is most likely unintended because it can break your application at runtime.
```
 

### Link to Reproduction (or Detailed Explanation)

¯\_(ツ)_/¯ 

### Steps to Reproduce

just use ark ui as usual
I would think pnpm also doesn't auto resolve missing transitive dependencies, but for yarn:
```sh
#install yarn
yarn set version berry
```
```yaml
#in .yarnrc.yml
nodeLinker: pnp
pnpFallbackMode: dependencies-only
pnpMode: strict
```

```sh
yarn add solid-js @ark-ui/anatomy @ark-ui/solid
#build your project
```

### Ark UI Version

3.3.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

**Comment by segunadebayo** [comment]
Good catch @ownw.

Pushed a fix for this. We'll release an update shortly.
