### ISSUE TITLE
Property 'ValueSwatch' of ColorPicker component does not exist (Outdated doc ??)

### ISSUE THREAD

**Issue by Piglow19** [chakra-ui/ark#2588]
### Description

It appears that there was a recent update or documentation error regarding the ValueSwatch component in the Ark UI Color Picker. As of now, ValueSwatch is not listed as an available component in the latest version of the library.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/goofy-shamir-56tr8f?file=%2Fsrc%2FApp.tsx%3A16%2C22

### Steps to Reproduce

Simply check for ts error line 16 in App.tsx file 

### Ark UI Version

3.3.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Opera

**Comment by cschroeter** [comment]
Thanks for pointing this out. I'll release a new version shortly. Use `@ark-ui/react": "3.4.0-1" if you eager`
