### ISSUE TITLE
Circular Progress does not work in solidjs

### ISSUE THREAD

**Issue by promethyttrium** [chakra-ui/ark#2589]
### Description

```
export const CircularProgressComponent: Component = () => {
  return (
      <Progress.Root>
        <Progress.Label>Label</Progress.Label>
        <Progress.ValueText />
        <Progress.Circle>
          <Progress.CircleTrack />
          <Progress.CircleRange />
        </Progress.Circle>
      </Progress.Root>
  );
};
```
The very unhelpful error of: 
![image](https://github.com/chakra-ui/ark/assets/3183017/d0d690d6-e7f5-4a00-afb5-5bc9e6fffa71)

### Link to Reproduction (or Detailed Explanation)

That codesandbox template assumes react, i'm using solidjs.  The code snippet above should suffice.

### Steps to Reproduce

Just trying to render that component shows that error. 

### Ark UI Version

^3.3.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
@promethyttrium Thanks for taking your time to report this issue. Should be fixed https://github.com/chakra-ui/zag/commit/e4c54c170020a7aacf06e06b24cb111da77fa12d and available in the next release.
