### ISSUE TITLE
Integration with React hook form 

### ISSUE THREAD

**Issue by chertik77** [chakra-ui/ark#2591]
### Description

How i suppose to integrate date picker with react hook form? 

```typescript
 render={({ field, formState: { errors, dirtyFields } }) => (
        <DatePicker.Root
          value={[field.value?.toString()]}
          onValueChange={({ valueAsString }) =>
            field.onChange(valueAsString[0])
          }
```

Why value is type of string[] if i have a selection mode single, it's useless

### Link to Reproduction (or Detailed Explanation)

.

### Steps to Reproduce

.

### Ark UI Version

3.3.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

Please follow the issue template, as we're not able to act on issues that lack important information.
