### ISSUE TITLE
Combobox throws error when `items` prop value is reactive

### ISSUE THREAD

**Issue by asterikx** [chakra-ui/ark#2605]
### Description

When I pass a reactive value to the `items` prop of the Combobox component, I expect it to not throw an error and just work as if the value wasn't reactive.

Instead I get the error
```
TypeError: Cannot set property items of #<Object> which has only a getter
```

This breaks using the Combobox component in Solidjs for any dynamic options (fetched from a database).

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/github-kfmqvq?file=src%2Fcomponents%2Fcombobox.tsx,src%2Froutes%2Findex.tsx

### Steps to Reproduce

1. Run Stackblitz and see immediate error

### Ark UI Version

3.4.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

### Browser

Any

**Comment by cschroeter** [comment]
@asterikx 

Thanks a fix will be available in `v3.4.1`
