### ISSUE TITLE
Controlled checkbox does not call onCheckedState

### ISSUE THREAD

**Issue by Mottoweb** [chakra-ui/ark#2608]
### Description

After changing checkbox state externally via control, clicking on checkbox onCheckedChange is not called after that

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/ark-ui-checkbox-issue-j29z6r?file=%2Fsrc%2FApp.tsx

### Steps to Reproduce

Go to: https://codesandbox.io/p/devbox/ark-ui-checkbox-issue-j29z6r?file=%2Fsrc%2FApp.tsx
Click on checkbox label: Checkbox toggles
Click on control button: Checkbox toggles
Click on checkbox label: Checkbox DOES NOT toggle for a few click Expected: Checkbox toggles

### Ark UI Version

3.4.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by segunadebayo** [comment]
Good catch @Mottoweb

I fixed this in a recent commit in Zag.js. We'll do a new release shortly.

If issue persist afterward, we'll reopen

**Comment by Mottoweb** [comment]
@segunadebayo perfect, thanks
