### ISSUE TITLE
closeOnInteractOutside not working

### ISSUE THREAD

**Issue by rijvanmohd** [chakra-ui/ark#2614]
### Description

while implementing Dialog, i came across that if i have `modal={false}` the dialog will always close on outside click even if i add `closeOnInteractOutside={false}` and if i have `modal={true}`, it won't close on outside click. maybe i am doing something wrong here

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/sandbox/arkui-dialog-g7dkdg?file=%2Fsrc%2FModal.tsx%3A4%2C66

### Steps to Reproduce

1. click on Open Modal
2. click outside should close the modal

### Ark UI Version

3.4.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by segunadebayo** [comment]
Hey @rijvanmohd,

Based on the docs, what they do:

- modal:  Whether to prevent pointer interaction outside the element and hide all content below it
- closeOnInteractionOutside: Whether to listen for outside interaction and close the dialog

Think of the modal as a "focus trap + block scroll + hide content outside." It's not connected to closing on interaction outside.

> Please attach a valid reproduction to dig in further.

**Comment by rijvanmohd** [comment]
Thanks for the explaination @segunadebayo. i have replaced the reproduction link or check here https://codesandbox.io/p/sandbox/arkui-dialog-g7dkdg
