### ISSUE TITLE
[TreeView] [Vue] TreeView example don't work on Nuxt 3

### ISSUE THREAD

**Issue by Theo-Rige** [chakra-ui/ark#2616]
### Description

The TreeView component example don't work on Nuxt 3. I got this error 500 : `Tree or branch root not found`

### Link to Reproduction (or Detailed Explanation)

https://github.com/Theo-Rige/issue-ark-treeview-nuxt

### Steps to Reproduce

1. Create a fresh Nuxt 3 app
2. Create a new component and paste the TreeView example for Vue from : https://ark-ui.com/vue/docs/components/tree-view
3. Call this component in `app.vue`
4. Launch the dev server

### Ark UI Version

3.5.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

Edge

### Additional Information

The component work on the Stackblizt quickstart : https://stackblitz.com/github/chakra-ui/ark/tree/main/templates/vue/nuxt
but the error appears when you add a Nuxt module.

**Comment by segunadebayo** [comment]
Hi @Theo-Rige,

When using Nuxt, we recommend providing a static id for reliable SSR. The solution would be to pass `id` to the `Tree.Root` component.

Please be aware of a known issue with Nuxt's `useId` hook. For more context see this discussion: https://github.com/chakra-ui/ark/discussions/2585
