### ISSUE TITLE
[solid] Combobox doesn't update the Input on selection

### ISSUE THREAD

**Issue by dannylin108** [chakra-ui/ark#2623]
### Description

Choosing an item from drop-down list doesn't update the input.
 

https://github.com/chakra-ui/ark/assets/72641467/52ef0b67-6113-4e41-86b7-02cdb3cfee15

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/github/dannylin108/parkui-bug-report/main

### Steps to Reproduce

1. Choose an item from drop-down list
2. First time the input is updated
3. Choose another item from drop-down list
4. Input remained the same, but should be updated.

### Ark UI Version

3.5.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

**Comment by Jonas-C** [comment]
This is reproducible in all frameworks, btw.

**Comment by segunadebayo** [comment]
This is now fixed in Zag.js. We’ll publish a new versions shortly
