### ISSUE TITLE
Code Tabs text display on top of the navbar

### ISSUE THREAD

**Issue by alexwhitmore** [chakra-ui/ark#2625]
### Description

In every page with a code block that has `code-tabs`, the text within the tabs will display over the navbar as opposed to under, considering it's a fixed header.

Dark mode:

<img width="773" alt="Screenshot 2024-07-02 at 5 15 47 PM" src="https://github.com/chakra-ui/ark/assets/57722812/f98d7e8f-e0cd-4f86-9e12-21b909a10ef4">

Light mode:

<img width="818" alt="Screenshot 2024-07-02 at 5 15 54 PM" src="https://github.com/chakra-ui/ark/assets/57722812/e762ec29-7599-4002-8a28-d0d2daf8f521">

### Link to Reproduction (or Detailed Explanation)

N/A

### Steps to Reproduce

No reproduction required, this is default behavior on the ArkUI documentation site.

### Ark UI Version

Lateset

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome & Safari

### Additional Information

I assume this is not expected behavior of the code tabs. I have cloned the project locally, and tested out a fix as I am willing to submit a pull request!

**Comment by carwack** [comment]
Thanks for noticing. 
Looked like the z-index for both components was set to '1' which seems to create this bug. 
Created a PR to fix this. #2676
