### ISSUE TITLE
Error when using an async component as a child in Menu.Item with asChild prop

### ISSUE THREAD

**Issue by nonoakij** [chakra-ui/ark#2628]
### Description

When I use an async component as a child in Menu.Item with the asChild prop, I expected it to render properly but an error occurred instead. This error does not occur when the asChild prop is not used. The error occurs at [this line](https://github.com/chakra-ui/ark/blob/d31ad551f3c035ab0e50b70600e3a231c17bdb8d/packages/react/src/components/factory.ts#L47) in the factory.ts file.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/modest-ganguly-fkjp9p

### Steps to Reproduce

1. Visit CodeSandbox to check Preview

### Ark UI Version

3.5.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome: 128.0.6559.0（Official Build）dev （arm64）

## screenshots
![スクリーンショット 2024-07-04 0 23 39](https://github.com/chakra-ui/ark/assets/45055030/f40217a6-da88-417a-ba2c-be40696f1714)

## reproduce repo
https://github.com/nonoakij/reproduce-ark-rsc-as-child

**Comment by segunadebayo** [comment]
This is design constraint. Server components render to HTML strings not React elements making them incompatible with asChild (which uses cloneElement)

If you really need to use asChild, I recommend to wrap it around a react element
