### ISSUE TITLE
[Select]: `data-placeholder-shown` does not exist on trigger

### ISSUE THREAD

**Issue by daalfox** [chakra-ui/ark#2671]
### Description

I checked inspector for my select component and there is no `data-placeholder-shown` attribute on trigger

### Link to Reproduction (or Detailed Explanation)

It's pretty simple you just need a select control

### Steps to Reproduce

1. create a select component
2. check attributes for `trigger` data part

### Ark UI Version

3.5.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

### Browser

firefox 128.0

**Comment by segunadebayo** [comment]
The `data-placeholder-shown` attribute only shows up when the value is empty.

If you have a reproduction, please provide it and we'll look further
