### ISSUE TITLE
Pin input auto focus broken in React

### ISSUE THREAD

**Issue by Reilley64** [chakra-ui/ark#2702]
### Description

When I auto focus a PinInput, I expect when I type in the first input it will focus the following inputs as I type but instead it keeps focus on the first input until a manually focus another input.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/recursing-engelbart-47skv2

### Steps to Reproduce

1. Start inputting in first input after the autoFocus
2. See that it doesn't continue to next input

### Ark UI Version

3.5.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome

**Comment by segunadebayo** [comment]
Please apply `autoFocus` on the `PinInput.Root` instead of the `PinInput.Input` and it should work correctly.

**Comment by Reilley64** [comment]
I've updated the codesandbox to have the autoFocus on the PinInput.Root and it still does the same thing

**Comment by cschroeter** [comment]
https://github.com/user-attachments/assets/b4c03f65-b8ba-467f-a050-439b0961fd41

Works for me. Maybe the version was not correctly updated or is an issue with sandbox
