### ISSUE TITLE
`EnvironmentProvider` not working for `Dialog` portalled into shadow DOM

### ISSUE THREAD

**Issue by ivancuric** [chakra-ui/ark#2714]
### Description

Trying to use the same approach as https://github.com/chakra-ui/ark/issues/2699#issuecomment-2248134675 results in the following error:
```
[@zag-js/dismissable] node is `null` or `undefined`
```

```tsx
export const App = () => {
  let portalNode!: HTMLDivElement;
  return (
    <Dialog.Root defaultOpen>
      <Dialog.Trigger>Open Dialog</Dialog.Trigger>
      <Portal ref={portalNode} useShadow={USE_SHADOW}>
        <EnvironmentProvider value={() => portalNode?.shadowRoot ?? document}>
          <Dialog.Backdrop />
          <Dialog.Positioner>
            <Dialog.Content>
              <Dialog.Title>This dialog isn't focused</Dialog.Title>
              <Dialog.Description>
                <p>Focus trap doesn't work here, if we're using shadow DOM</p>
                <p>Neither does click outside or any other interaction</p>
              </Dialog.Description>
              <Dialog.CloseTrigger>Close</Dialog.CloseTrigger>Ω
              <button>hello</button>
            </Dialog.Content>
          </Dialog.Positioner>
        </EnvironmentProvider>
      </Portal>
    </Dialog.Root>
  );
};

```

In this case, the focus trap doesn't work in the dialog, nor does other functionality.

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/ark-dialog-shadow?file=src%2FApp.tsx

### Steps to Reproduce

On the repro, try the usage with, and without shadow roots (`USE_SHADOW`).

I expected both behaviours to be the same, however the focus handling and click outside handlers (among other things) don't work when shadow roots are used.

### Ark UI Version

^3.5.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

### Browser

Chrome 126.0.6478.183

**Comment by segunadebayo** [comment]
To make this work the EnvironmentProvider needs to sit above the Dialog.Root.

The dialog or select root reads from the environment provider context so that element locators (querySelectorAll, querySelector) 

Notice that the previous select example had the environment provider above the select root

**Comment by ivancuric** [comment]
Ah! I thought that it was in relation to the Portal, not the Root.

Thanks again for the help! I believe that the docs could be a bit more elaborate on these things.

**Comment by ivancuric** [comment]
That's a step in the right direction! Thanks!

One followup question: If the `EnvironmentProvider` is above `Dialog.Root`, the dialog just opens and closes, as it loses focus. Is there any way to refocus it?

**Comment by ivancuric** [comment]
> To make this work the EnvironmentProvider needs to sit above the Dialog.Root.
> 
> The dialog or select root reads from the environment provider context so that element locators (querySelectorAll, querySelector)
> 
> Notice that the previous select example had the environment provider above the select root

This ends up being an impossible case: 

https://ark-ui.com/solid/docs/utilities/environment#usage-in-shadow-dom

1. The `Portal` needs to be inside `Dialog.Root`
2. The `Dialog.Root` needs to  be inside `EnvironmentProvider`
3. The `EnvironmentProvider` needs to be inside `Portal`
