### ISSUE TITLE
Clicking on the label of the select box automatically scrolls

### ISSUE THREAD

**Issue by togana** [chakra-ui/ark#2741]
### Description

When I clicked on the select box label, I expected the select box to be selected, but instead the screen scrolled.

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/~/github.com/togana/sample-ark-ui-select?file=src/App.tsx

### Steps to Reproduce

1. Prepare a div with a height of 500px and set overflow to auto.
2. Use example select box. (https://ark-ui.com/react/docs/components/select#examples)
3. Place a large number of select boxes in that div.
4. Click on the bottom select box label.
5. The screen will scroll.

https://github.com/user-attachments/assets/53c8df95-4267-4c32-80c1-44a1cbec3efb

### Ark UI Version

3.6.2

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome 127.0.6533.89

### Additional Information

What I am concerned about is that HiddenSelect exists in an invisible position, and when it is selected, it seems to be in a strange position.

**Comment by segunadebayo** [comment]
Please apply position relative to the select root element to prevent this.

`<Select.Root items={items} style={{ position: "relative" }}>`

The hidden select has `position: absolute` on it to visually hide in an accessible way.

**Comment by togana** [comment]
thank you! solved!
