### ISSUE TITLE
[React][Ark UI Plus][Combobox with TagsInput] Selecting new tag re-adds previously removed tags

### ISSUE THREAD

**Issue by c-butler-edacious** [chakra-ui/ark#2742]
### Description

Hello Ark UI team! Thank you for looking into this and please let me know if any additional information is needed!
- After adding and then removing tags, selecting a new tag re-adds previously removed tags instead.
- After adding and removal, search does not work until input is blurred and re-focussed. 

### Link to Reproduction (or Detailed Explanation)

https://ark-ui.com/react/examples/combobox-with-tags-input

### Steps to Reproduce

1. Go to https://ark-ui.com/react/examples/combobox-with-tags-input
2. Type "za," and select "Zambia." Then select "Canada" and "United States."
3. Remove all three tags using the "x"
4. Keeping the input focussed, type any characters or press the down arrow key — no results appear.
5. Click outside, then re-focus the input. Type "za," and select "Zambia."
6. "Canada" and "United States" are added ("Zambia" is not).

### Ark UI Version

^3.6.2

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome

**Comment by c-butler-edacious** [comment]
Setting the `value` prop on `Combobox.Root` to `value={value}` seems to solve the issue of the Combobox being out of sync with the TagInput.

**Comment by segunadebayo** [comment]
That's great to hear. We'll update the code as needed.

Thanks
