### ISSUE TITLE
vue range slider example from the docs crashes

### ISSUE THREAD

**Issue by stefanprobst** [chakra-ui/ark#2751]
### Description

The [vue range slider example from the docs](https://ark-ui.com/react/docs/components/slider#range-slider) crashed with the following error:

```
Cannot read properties of undefined (reading 'max')

at Proxy. (./node_modules/.pnpm/@ark-ui+vue@3.7.2_vue@3.4.37/node_modules/@ark-ui/vue/dist/components/slider/slider-thumb.js.js:18:80)
```

the only difference to [the react example](https://ark-ui.com/react/docs/components/slider#range-slider) is the missing `defaultValue`. note that the react example also crashes when i remove the `defaultValue` prop.

### Link to Reproduction (or Detailed Explanation)

https://github.com/stefanprobst/issue-ark-ui-slider

### Steps to Reproduce

- clone repro
- `pnpm install && pnpm run dev`
- open http://localhost:3000/

### Ark UI Version

3.7.2

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

firefox 128

**Comment by segunadebayo** [comment]
This is a docs/example issue. The default value or value is required when using a range slider.

**Comment by segunadebayo** [comment]
I'm update the docs accordingly
