### ISSUE TITLE
[ColorPicker] The "pick a color" button just not work in Firefox

### ISSUE THREAD

**Issue by rasc-br** [chakra-ui/ark#2764]
### Description

Just open: https://ark-ui.com/vue/docs/components/color-picker in Firefox and click in the "pick a color" button: 
![image](https://github.com/user-attachments/assets/f6bcfdce-2d2d-4f4d-a91c-61ee61076538)

Nothing happens, not even an error or warning.

### Link to Reproduction (or Detailed Explanation)

https://ark-ui.com/vue/docs/components/color-picker

### Steps to Reproduce

1. Open https://ark-ui.com/vue/docs/components/color-picker in Firefox
2. Click the "pick a color" button

### Ark UI Version

3.7.2

### Framework

- [X] React
- [X] Solid
- [X] Vue

### Browser

Firefox

**Comment by segunadebayo** [comment]
That’s because the EyeDropper API isn’t supported in Firefox just yet.

https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper
