### ISSUE TITLE
[Combobox] Using `onInputValueChange` with `value` doesn't work

### ISSUE THREAD

**Issue by MTG2000** [chakra-ui/ark#2769]
### Description

In the latest version of ArkUI, if I use both `onInputValueChange` to filter the items, and the `value` property, the component doesn't work properly.
The list doesn't filter, & the input value keeps resetting. (It's like the full component is unmounting then remounting)
This was working fine with an earlier version, but it's not now.

I've created a simple reproduction below, try to type the text of one of the items to see that it's not being filtered & the input is resetting after each key stroke.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/loving-sky-22q7nv

### Steps to Reproduce

- Click on the input 
- Type 'One'
- See issue

### Ark UI Version

3.7.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome

**Comment by segunadebayo** [comment]
To fix this I recommend memoizing the `value`

```tsx
<Combobox.Root
      items={items}
      multiple
      onInputValueChange={handleInputChange}
      onOpenChange={handleOpenChange}
      value={useMemo(
        () => selectedItems.map((item) => item.value),
        [selectedItems]
      )}
      onValueChange={({ items }) => setSelectedItems(items)}
  />
```

**Comment by MTG2000** [comment]
Yeah, it's working now!
Thanks @segunadebayo 
Didn't know it needed to be wrapped with `useMemo`
