### ISSUE TITLE
[Nuxt] Problem with internal import from `@zag-js/utils` since 3.8.0

### ISSUE THREAD

**Issue by YaredFall** [chakra-ui/ark#2792]
### Description

When I try to import ArkUI components, such as `Dialog` or `Avatar` inside my Nuxt3 projects, i face the following error:
```
The requested module '../../node_modules/@zag-js/utils/dist/index.js' does not provide an export named 'omit'
```
It's seems that issue started occuring since `@ark-ui/vue@3.8.0`, as version `3.7.2` and prior working fine.

### Link to Reproduction (or Detailed Explanation)

https://github.com/YaredFall/ark-zag-utils-import-issue-repro

### Steps to Reproduce

1. clone the [reproduction repo](https://github.com/YaredFall/ark-zag-utils-import-issue-repro)
2. open reproduction project
3. run `pnpm i`
4. run `pnpm dev` and visit `http://localhost:3000/`
5. you now shoul see the error **`500`** `The requested module '../../node_modules/@zag-js/utils/dist/index.js' does not provide an export named 'omit'`
6. if you go to `app.vue` and remove the line `import { Dialog } from "@ark-ui/vue";` the error will be gone

### Ark UI Version

3.9.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

Google Chorme v127, Firefox v129

### Additional Information

The error occurs in Nuxt projects, but does not seem to occur in Vite + Vue projects.
I've also tested it with different package managers (`npm`, `pnpm` and `bun`) to ensure that it is not a bundler issue

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
