### ISSUE TITLE
Dialog unexpectedly closes on a touch device

### ISSUE THREAD

**Issue by dannylin108** [chakra-ui/ark#2816]
### Description

If some complex component (e.g. DatePicker) are placed inside Dialog/Drawer, it unexpectedly closes on touch devices

https://github.com/user-attachments/assets/5295df32-6a4b-489f-a8bc-6a086a54957f

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/~/github.com/dannylin108/parkui-bug-report

### Steps to Reproduce

1. Open the page on a touch device (Chrome emulation also works)
2. Open the drawer
3. Choose a date in the date picker
4. The drawer unexpectedly closes, but should remain open showing the chosen date.

### Ark UI Version

3.9.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

**Comment by segunadebayo** [comment]
I just pushed a fix for this in Zag.js. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by dannylin108** [comment]
Still present at  `"@ark-ui/solid": "3.12.0"`

repo updated

**Comment by Liinkiing** [comment]
Same here, I still reproduce the behaviour and retested on the stackblitz provided by @dannylin108. 

I've tried to check into the commits of zagjs to understand why it is happening, was this commit that should have fixed this issue @segunadebayo : https://github.com/chakra-ui/zag/commit/611ab978e0b27bf68c118a39cf39faec7cd7a333?

Again thank you for providing Ark+Panda, it is really a great combo! ✨

**Comment by cschroeter** [comment]
@Liinkiing This will be fixed with the next release

**Comment by mariodukoskiinfinum** [comment]
> @Liinkiing This will be fixed with the next release

@cschroeter Thank you for the update. Do you have an estimated timeline for the next release? I'm in the process of upgrading Ark UI to v4, but this issue is currently a blocker for us.
