### ISSUE TITLE
Dialog not returning focus if trigger and dialog are in different shadow roots

### ISSUE THREAD

**Issue by ivancuric** [chakra-ui/ark#2820]
### Description

When no shadow roots are used, focus is correctly returned after closing a modal. If shadow roots are used, the next tab will focus the address bar instead.

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/ark-dialog-shadow-1f7p1n?file=src%2FApp.tsx

### Steps to Reproduce

1. Visit https://stackblitz.com/edit/ark-dialog-shadow-1f7p1n?file=src%2FApp.tsx
2. Try opening and closing the dialog with the keyboard
3. Observe changes in behaviour if `USE_SHADOW` is set to `false`

### Ark UI Version

3.6.2

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

### Browser

Chrome

**Comment by segunadebayo** [comment]
We don't support rendering the trigger and content in different shadow roots.

Instead, I recommend controlling the open state programmatically and rendering the entire dialog in a single shadow root.
