### ISSUE TITLE
`aria-hidden=true` should never be applied to the `body` element

### ISSUE THREAD

**Issue by ivancuric** [chakra-ui/ark#2844]
### Description

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden

> Using `aria-hidden="false"` will not re-expose the element to assistive technology if any of its parents specify `aria-hidden="true"`.

Chrome will also log an error message:
> Blocked aria-hidden on a <button> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.

![image](https://github.com/user-attachments/assets/a8a4d7ae-3fc9-4210-bbdc-157a32f097b1)

### Link to Reproduction (or Detailed Explanation)

https://ark-ui.com/react/docs/components/dialog

### Steps to Reproduce

1. Go to https://ark-ui.com/react/docs/components/dialog
2. Open dialog

### Ark UI Version

3.10.0

### Framework

- [X] React
- [X] Solid
- [X] Vue

### Browser

Firefox

### Additional Information

Discussion on Twitter:
https://x.com/_baxuz/status/1831617287406670291

Chrome a11y tree showing it's ignored:
![image](https://github.com/user-attachments/assets/8cd3ee19-5040-48f5-a7fa-60cc312ad873)

I have already reported this bug once and it has been turned to a discussion for some reason:
https://github.com/chakra-ui/ark/discussions/2717

**Comment by segunadebayo** [comment]
I just pushed a fix for this in Zag.js. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
