### ISSUE TITLE
Adding `boundary` to components that utilise Float UI doesn't work

### ISSUE THREAD

**Issue by dvlden** [chakra-ui/ark#2845]
### Description

When we add `:positioning="{ boundary: boundaryElement }"` to `<Popover.Root />`, it fails with `RangeError: Maximum call stack size exceeded`

This is a must for me and if I can get some guidance on how to fix it or if someone else can jump in and fix it, I'd highly appreciate the time and effort.

Setting custom boundary should work, as Float UI allows us to modify it, so that calculations are within the boundary and not window/viewport. 

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/vitejs-vite-c964zf?file=src%2FApp.vue

### Steps to Reproduce

1. Click the `Open Popover` trigger
2. Check where the `PopoverPositioner` has moved the content
3. Check the console for the callstack error

<img width="326" alt="Screenshot 2024-09-05 at 12 38 24" src="https://github.com/user-attachments/assets/1ea21585-9432-48f4-9f1c-a9aed5a0ac3f">

### Ark UI Version

3.7.2 on sandbox, 3.10.0 in my real app

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

All browsers and all versions

**Comment by dvlden** [comment]
New discovery. It works fine if `boundary: () => boundaryElement` is used as a function.

**Comment by segunadebayo** [comment]
Yes, it needs to be a function to work correctly. We'll update the types in Zag.js to match this.

**Comment by segunadebayo** [comment]
Done. We'll release an update shortly.
