### ISSUE TITLE
[React][Toast] Can't pass ReactNode to title or description

### ISSUE THREAD

**Issue by lebretont** [chakra-ui/ark#2875]
### Description

When I try to add a ReactNode to _title_ or _description_ of a toast, the app crashes and I get the error 

> proxy set handler returned false for property '"validated"'

 on the browser console.

### Link to Reproduction (or Detailed Explanation)

https://github.com/lebretont/ark/tree/bug/toast

### Steps to Reproduce

Clone the reproduction
Navigate to the packages/react folder
Execute `bun vitest ./src/components/toast/tests/toast.test.tsx`
Test fails

### Ark UI Version

3.10.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Firefox, Arc

### Additional Information

At first sight the error comes from the _jsxFactory_ method inside factory.ts but I have not been able to correctly identify the cause or correct the problem.

**Comment by segunadebayo** [comment]
This has been fixed in Zag.js. We'll release an update shortly.
