### ISSUE TITLE
[DatePicker] YearSelect doesn't respect min and max

### ISSUE THREAD

**Issue by eduardocque** [chakra-ui/ark#2882]
### Description

noticed that yearSelect component is not working properly the ranges due that `from / to` are not depending on `min / max` of the datepicker

![image](https://github.com/user-attachments/assets/ff9ccac1-3337-47e5-826f-69a03a7d5458)

so i was trying to make my own select, but that one crash as well

```js
<DatePickerArk.YearSelect asChild={false}>
	<DatePickerYearSelect />
</DatePickerArk.YearSelect>
```

![image](https://github.com/user-attachments/assets/dae6f72a-aa57-4c1b-93c5-9cb831be33bd)
![image](https://github.com/user-attachments/assets/bca1b060-3975-404b-914e-8739237360f8)

so, what can i do in this case ?

### Link to Reproduction (or Detailed Explanation)

not provided

### Steps to Reproduce

there are 2 issues

Composition Issue
- add a datepicker and try to override yearSelect slot and should crash

Year Range issue
- add a datepicker with min/max and add the slot yearSelect, and is ignoring it

### Ark UI Version

3.10.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome

### Additional Information

File Affected https://github.com/chakra-ui/ark/blob/main/packages/react/src/components/date-picker/date-picker-year-select.tsx

**Comment by eduardocque** [comment]
@segunadebayo if at least i can make my own component using `asChild` i can continue but for the moment that one crash as well

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by eduardocque** [comment]
@segunadebayo thank you for the support mate

**Comment by eduardocque** [comment]
@segunadebayo i would like to ask when is the release of this, thank you
