### ISSUE TITLE
`Menu` closes unexpectedly if it's inside a `Dialog` that is triggered by another `Menu`

### ISSUE THREAD

**Issue by Xelson** [chakra-ui/ark#2883]
### Description

The menu opens, but as soon as the pointer goes beyond the trigger (whether it was clicked or not), the menu closes. Also, `onOpenChange` event is not triggered, although if you set the controller to `open`, the menu does not close.
Portals do not affect this behavior

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/still-http-sz5zs9

### Steps to Reproduce

1. Go to reproduction sandbox
2. Open the first menu, then the dialog inside. The menu inside the dialog will be broken

### Ark UI Version

3.12.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome 128

**Comment by segunadebayo** [comment]
This is more about how the Menu and Dialog are composed.

[Here's a sandbox with a fix](https://codesandbox.io/p/devbox/goofy-shamir-782nsv?workspaceId=04ba4adf-e1ad-4d70-a496-84132e7a1eb4)

I recommend the following:
- Renders a single dialog to manage all the menu items.
- If there are menu items that can trigger a dialog, listen to the `onSelect` of the menu and react to that.
- Lift up the selected menu item to the dialog and render the correct content or component
