### ISSUE TITLE
@ark-ui/vue@4.0.1 isn't compatible with Nuxt 3

### ISSUE THREAD

**Issue by ItsRyanWu** [chakra-ui/ark#2927]
### Description

It doesn't work in Nuxt but works in pure Vue project

![CleanShot 2024-09-27 at 13 18 33](https://github.com/user-attachments/assets/9c65363e-840a-40e3-98f9-9c622d6d150f)

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/live/7d8d37ad-2413-4a19-9b7e-d6827bd1ba2a

### Steps to Reproduce

Open the codesandbox

### Ark UI Version

@ark-ui/vue@4.0.1

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

**Comment by cschroeter** [comment]
@ItsRyanWu @hex-ci 

Thanks for reporting the issue. I could reproduce the issue and it now fixed with `v4.0.2`

**Comment by ItsRyanWu** [comment]
Awesome, you are so fast! @cschroeter and thanks for your findings @hex-ci
