### ISSUE TITLE
Switch - Toggle not working with "Enter" key

### ISSUE THREAD

**Issue by thevipinmishra** [chakra-ui/ark#2946]
### Description

According to the docs, "Switch" toggles on both the "Space" and "Enter" keys.

However, it only works with "Space" and not the other one.

I confirmed it with ark-ui's own Switch component.

### Link to Reproduction (or Detailed Explanation)

https://ark-ui.com/react/docs/components/switch

### Steps to Reproduce

1. Vist the "Switch" component [page](https://ark-ui.com/react/docs/components/switch).

2. Focus on the preview component.

3. Try toggling it with "Enter" key.

### Ark UI Version

4.1.0

### Framework

- [X] React
- [X] Vue
- [X] Solid

### Browser

Google Chrome Dev

**Comment by segunadebayo** [comment]
This is by design. The switch is built on top of the checkbox component which only toggles with the space key or pointer click.

The enter key is reserved for form submissions.

**Comment by thevipinmishra** [comment]
> The enter key is reserved for form submissions.

Thanks for the quick response @segunadebayo!

I only mentioned it because it was mentioned in the docs. I think we can remove it then!?

![image](https://github.com/user-attachments/assets/0c7d205e-d784-4465-9ef3-477fddba681a)
