### ISSUE TITLE
Does not provide an export named 'createListCollection' after update to vue/4.1.0

### ISSUE THREAD

**Issue by maxmckenzie** [chakra-ui/ark#2963]
### Description

I was updating to the new version of Ark. Cool that theres a new createListCollection feature.

I expected to use the new createListCollection feature, But i get the following error.

```
The requested module '/_nuxt/node_modules/.cache/vite/client/deps/@ark-ui_vue.js?v=667655d9' does not provide an export named 'createListCollection'
```

I've updated the Select
```vue
<Select.Root
  v-model="model"
  :collection="collection"
  :multiple="props.multiple"
  :close-on-select="true"
>
```

and imported it and hooked it up

```vue
import { Select, Field, createListCollection } from '@ark-ui/vue'

const items = props.options.map(option => ({
  label: option.name,
  value: option.id
}))

const collection = createListCollection(items)
```

i checked the docs but there only seems to guides for react even with vue as the switch 

<img width="472" alt="image" src="https://github.com/user-attachments/assets/dd9d974a-9639-47a3-aa56-0e1ae264e5a3">

### Link to Reproduction (or Detailed Explanation)

this is just for react do you have a starter for vue?

### Steps to Reproduce

1. Create a Field based controlled component as per the docs here https://ark-ui.com/vue/docs/guides/collection
2. See that the import is not found

### Ark UI Version

4.1.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

Google Chrome

**Comment by cschroeter** [comment]
@maxmckenzie Thanks for taking your time to create this issue. Not sure why you get this error.The example below should work. If the issue persist please create a new issue with a reproduction example

<img width="1118" alt="image" src="https://github.com/user-attachments/assets/9ce4a315-d4aa-495a-a0f9-aa091afdb653">

**Comment by maxmckenzie** [comment]
Thanks so much

For anyone else that my find this, My issue was in two parts.

I was trying to import from the whole lib
```
import { Field, Select, createListCollection } from '@ark-ui/vue'
```
It should be imported as below
```
import { Select, createListCollection } from '@ark-ui/vue/select'
import { Field } from '@ark-ui/vue/field'
```

and i was trying to directly pass in the array `createListCollection(myArray)` but it should be nested in an items key `createListCollection({ items: myArray })`
