### ISSUE TITLE
[Bug] - Toast dismiss does close drawers

### ISSUE THREAD

**Issue by xeinebiu** [chakra-ui/ark#2974]
### Description

As seen on the video below, when I dismiss a toast for the second time (first time it works as expected always, first time after page loaded), but then when I call dismiss it also closes the Drawer. Even If I do not use the CloseTrigger of Toast but call globalToast.dismiss(id);

https://github.com/user-attachments/assets/01cdfebe-7f7e-4541-9dfe-00db2c531595

### Link to Reproduction (or Detailed Explanation)

provided example below

### Steps to Reproduce

````tsx
export const globalToast = Toast.createToaster({
  placement: 'bottom-end',
  overlap: true,
  gap: 16,
  duration: 60000,
});

export const GlobalToastProvider: FC = () => {
  return (
    <Toast.Toaster toaster={globalToast}>
      {(toast) => (
        <Toast.Root key={toast.id}>
          <Toast.Title>{toast.title}</Toast.Title>
          <Toast.Description>{toast.description}</Toast.Description>
          <Toast.CloseTrigger asChild>
            <IconButton size="sm" variant="link">
              <FontAwesomeIcon icon={faXmark} />
            </IconButton>
          </Toast.CloseTrigger>
        </Toast.Root>
      )}
    </Toast.Toaster>
  );
};

````

Consuming part
````tsx
      globalToast.create({
        title: 'TITLE TEST',
        description: 'DESCRIPTION TEST',
        type: 'success',
      });
````

### Ark UI Version

4.1.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome, Firefox

**Comment by xeinebiu** [comment]
Figured out the issue. 

````tsx
        <Drawer.Root
          closeOnInteractOutside={false}  // <-- If this is "true" then closing a toast is registered as "interact outside" event
         ....
        >
````

Now the question might be, do we want to count interacting with a "toast" as outside part 🤔

**Comment by cschroeter** [comment]
Thank you for reporting this issue. To help us investigate, please provide a minimal reproduction of the problem. You can use one of the following templates as a starting point:

- **React:** [StackBlitz React Template](https://stackblitz.com/github/chakra-ui/ark/tree/main/templates/react/next-js)
- **Solid:** [StackBlitz Solid Template](https://stackblitz.com/github/chakra-ui/ark/tree/main/templates/solid/solid-start)
- **Vue:** [StackBlitz Vue Template](https://stackblitz.com/github/chakra-ui/ark/tree/main/templates/vue/nuxt)

We’ll close this issue for now, but feel free to reopen it once a reproduction is available.

**Comment by xeinebiu** [comment]
> Thank you for reporting this issue. To help us investigate, please provide a minimal reproduction of the problem. You can use one of the following templates as a starting point:
> 
>     * **React:** [StackBlitz React Template](https://stackblitz.com/github/chakra-ui/ark/tree/main/templates/react/next-js)
> 
>     * **Solid:** [StackBlitz Solid Template](https://stackblitz.com/github/chakra-ui/ark/tree/main/templates/solid/solid-start)
> 
>     * **Vue:** [StackBlitz Vue Template](https://stackblitz.com/github/chakra-ui/ark/tree/main/templates/vue/nuxt)
> 
> 
> We’ll close this issue for now, but feel free to reopen it once a reproduction is available.

I'll do it when I get some free time, but from what I saw, the StackBlitz project is pretty empty. At least add the components to make it easier for people reporting issues to just write samples, instead of having to set up the whole Panda, Ark, and ParkUI CSS.

**Comment by xeinebiu** [comment]
@cschroeter 

Thanks for helping with this. I've attached the sample project below. Just run `npm i && npm start`.

The code isn't very organized, but you can find it in `apps/portal -> main.tsx`. In `main.tsx`, you'll see the `globalToaster` and the `modal`.

[drawer_issue_xeinebiu.zip](https://github.com/user-attachments/files/17347050/drawer_issue_xeinebiu.zip)

https://github.com/user-attachments/assets/1d6c20cb-6684-478a-9056-8ec3ff7945c6

**Comment by pavlo-sodtrack** [comment]
@cschroeter can you reopen this issue. The bug still persists.
