### ISSUE TITLE
dialog,select: Keyboard accessibility doesnt work in select inside dialog

### ISSUE THREAD

**Issue by althafdemiandra** [chakra-ui/ark#2979]
### Description

I tried to create select inside dialog
looks like browser cant focus into `SelectContent` if it is rendered inside Dialog, so keyboard accessibility doesnt work

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/sandbox/hc6s77

### Steps to Reproduce

1. Crreate select inside dialog
2. Try to navigate around with `arrow up/down`/`enter` inside content, it cant
3. Content not focused while rendered inside dialog

### Ark UI Version

4.1.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chromium (Brave Browser)

**Comment by segunadebayo** [comment]
When nesting the select or popover is used in a dialog (that is portalled), here are the things you can do:

- Don’t portal the select
- Set the target ref of portal to the dialog content
