### ISSUE TITLE
Frame - Missing client directive in React

### ISSUE THREAD

**Issue by carloitaben** [chakra-ui/ark#2999]
### Description

I noticed that the React `Frame` component is missing the `"use client"` directive, while all other components have it
![image](https://github.com/user-attachments/assets/52a8eea4-e216-4d4f-97e2-d2b5de420269)

### Link to Reproduction (or Detailed Explanation)

See above description

### Steps to Reproduce

Render the `Frame` component in a React Server Component. It should show the following error:
> ModuleDependencyError: export 'useState' (imported as 'useState') was not found in 'react' (possible exports: Children, Fragment, Profiler, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, __SECRET_SERVER_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cache, cloneElement, createElement, createRef, forwardRef, isValidElement, lazy, memo, startTransition, use, useCallback, useDebugValue, useId, useMemo, version)

### Ark UI Version

4.1.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
@carloitaben 

Thanks for your time creating the issue. A fix will be available in the next release
