### ISSUE TITLE
[Bug][SolidJS] `FileUpload.ItemPreviewImage` does not display preview image

### ISSUE THREAD

**Issue by eyemono-moe** [chakra-ui/ark#3023]
### Description

While using the FileUpload component with SolidJS, I encountered an issue where the `FileUpload.ItemPreviewImage` does not display a preview image as expected.
It seems that the `src` of `FileUpload.ItemPreviewImage` is empty.
This issue persists even when providing valid image files.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/boring-david-vrd8wl

### Steps to Reproduce

1. Go to https://codesandbox.io/p/devbox/boring-david-vrd8wl
2. Click "Choose file(s)" button (`FileUpload.Trigger`)
3. Select an image file
4. Image file name and file size are displayed, but not the preview image

### Ark UI Version

4.3.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

### Browser

Google Chrome (130.0.6723.92), FireFox (132.0)

### Additional Information

reproduction screenshot in GoogleChrome
![image](https://github.com/user-attachments/assets/8f056e5d-d0fb-4305-85ef-d46629467a76)

**Comment by eyemono-moe** [comment]
https://github.com/chakra-ui/ark/blob/17cac56a1b3a008417539de2296813747a1ee931/packages/solid/src/components/file-upload/file-upload-item-preview-image.tsx#L22-L25

The url property is set using `mergeProps`, which is outside the tracked scope. As a result, changes to the `url` signal appear to be ignored.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
