### ISSUE TITLE
NumberInput render issue

### ISSUE THREAD

**Issue by rollercodester** [chakra-ui/ark#3066]
### Description

When the NumberInput is rendered, the resulting UI is in disarray. 

### Link to Reproduction (or Detailed Explanation)

https://ark-ui.com/react/docs/components/number-input

### Steps to Reproduce

Got to NumberInput in Ark component gallery and you should immediately see the issue.

### Ark UI Version

4.4.4

### Framework

- [X] React
- [X] Solid
- [X] Vue

### Browser

Google Chrome

**Comment by cschroeter** [comment]
@rollercodester Thanks for taking your time to report the issue. I could fix it. Cheers
