### ISSUE TITLE
Modal prop of Datepicker does not work

### ISSUE THREAD

**Issue by kg-and-digital** [chakra-ui/ark#3106]
### Description

When I add `modal` prop to <DatePicker.Root> I expect focus to be trapped within the calendar and not be able to access any elements outside.

### Link to Reproduction (or Detailed Explanation)

See steps to reproduce

### Steps to Reproduce

- Ensure you pass `modal` prop to <DatePicker.Root> element
- Trigger the calendar to open
- Using keyboard press tab to advance focus
- You will end up leaving the calendar and focussing on another element or browser element.

### Ark UI Version

4.4.0 

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome

**Comment by segunadebayo** [comment]
This prop was unimplemented in Zag.js. I've gone ahead to remove it for now.

Please consider using react-focus-trap or similar for now. We intend to implement a FocusTrap component pretty soon.
