### ISSUE TITLE
Dialog closed due to selection in internal date picker

### ISSUE THREAD

**Issue by onepercman** [chakra-ui/ark#3107]
### Description

Dialog closed due to selection in internal date picker

### Link to Reproduction (or Detailed Explanation)

_

### Steps to Reproduce

date picker inside dialog

### Ark UI Version

4.4.4

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome

**Comment by segunadebayo** [comment]
Please attach a reproduction to re-open this.

Consider the following approaches to fix this:
- Don't wrap the date picker content within a portal
- Use Portal in the date picker and set the portal container to the dialog content
