### ISSUE TITLE
Docs: it's not possible to close search modal

### ISSUE THREAD

**Issue by babakfp** [chakra-ui/ark#3109]
### Description

https://github.com/user-attachments/assets/e63f8590-e2bb-4d9f-a6c3-3f6351e66e10

In this video, I'm clicking outside the modal, but doing so doesn't close it.

### Browser

Chrome

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
