### ISSUE TITLE
`Select` component does not have `onInput` event

### ISSUE THREAD

**Issue by Reverier-Xu** [chakra-ui/ark#3111]
### Description

When i trying to use `Select` component, I found that `onInput` prop have no effect.

Additional: the `onChange` works well, and we do get the value from the change event, but the form library `modularforms` [only monitoring changes of the component by `onInput` event](https://github.com/fabian-hiller/modular-forms/blob/b8dd18b8487c9d41e7fe4aa67aa2e736f1d1fd37/packages/solid/src/components/Field.tsx#L163). Since the `onInput` event is a [standard event that emits by `<select>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#see_also), i think it is a bug that related to Ark.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/sandbox/solid-select-forked-n3qrt5

### Steps to Reproduce

1. choose some option in ark's select;
2. option does not sync to the signal with `onInput`;
3. choose some option in native select;
4. option sync-ed to the signal as expected.

### Ark UI Version

4.5.1

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

### Browser

ALL

**Comment by segunadebayo** [comment]
Select will not emit `onInput` since it is not modified directly by user interaction but by a JS script.
https://developer.mozilla.org/en-US/docs/Web/API/Element/input_event

I recommend setting up your modular-form integration similar to this
https://codesandbox.io/p/sandbox/solid-select-forked-dk26hw?file=%2Findex.tsx%3A11%2C5&workspaceId=ws_artqKPGn6LvzkzDZRu6yq

The major code to focus on

```tsx
<Field name="value">
  {(field, props) => (
    <Select.Root
      collection={frameworks}
      value={[field.value]}
      name={field.name}
      onValueChange={(e) => {
        setValue(formStore, field.name, e.value[0])
      }}
    >
      <Select.Control>
        <Select.Trigger>
          <Select.ValueText placeholder="Select a Framework" />
        </Select.Trigger>
        <Select.ClearTrigger>Clear</Select.ClearTrigger>
      </Select.Control>
      <Portal>
        <Select.Positioner>
          <Select.Content>
            <Select.ItemGroup>
              <Select.ItemGroupLabel>Frameworks</Select.ItemGroupLabel>
              <Index each={frameworks.items}>
                {(item) => (
                  <Select.Item item={item()}>
                    <Select.ItemText>{item().label}</Select.ItemText>
                    <Select.ItemIndicator>✓</Select.ItemIndicator>
                  </Select.Item>
                )}
              </Index>
            </Select.ItemGroup>
          </Select.Content>
        </Select.Positioner>
      </Portal>
      <Select.HiddenSelect {...props} />
    </Select.Root>
  )}
</Field>
```

**Comment by Reverier-Xu** [comment]
Since `Field` item is an dynamically-constructed component from `createForm`, we can't integrate it into an custom component. Maybe we can expose the `onChange` as a component prop to solve this problem, but hand-writing every action of select component is anoying. Finally i implement it by some ugly code to map `onChange` to `onInput`...

```diff
    <Select.Root>
      <Show when={selectProps.label}>
        <Select.Label class="label">{selectProps.label}</Select.Label>
      </Show>
      <Select.HiddenSelect
        {...selectProps.inputProps}
+       onChange={(e) => {
+         if (selectProps.inputProps?.onInput && typeof selectProps.inputProps.onInput === "function")
+           e.target.dispatchEvent(new Event("input", { bubbles: true, cancelable: true }));
+         if (selectProps.inputProps?.onChange && typeof selectProps.inputProps.onChange === "function")
+           selectProps.inputProps.onChange(e);
+       }}
      />
      <Select.Control>
        <Select.Trigger
        >
          <Select.Indicator>
            <span class="icon-[fluent--chevron-double-down-20-regular] w-5 h-5" />
          </Select.Indicator>
          <Select.ClearTrigger>
            <span class="icon-[fluent--dismiss-circle-20-regular] w-5 h-5" />
          </Select.ClearTrigger>
        </Select.Trigger>
      </Select.Control>
      <Portal>
        <Select.Positioner>
          <Select.Content class="card w-full popover">
            ...
          </Select.Content>
        </Select.Positioner>
      </Portal>
    </Select.Root>
```
