### ISSUE TITLE
Scroll Restoration in Overflowing Select Menus

### ISSUE THREAD

**Issue by thevipinmishra** [chakra-ui/ark#3136]
### Description

I had a select component which was working fine prior to 4.5.0.

Issues are there with keyboard navigation and scrolling to selected item.

I also confirmed with the official Select examples on ark-ui

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/vitejs-vite-fpkbyy?file=src%2FApp.tsx

### Steps to Reproduce

1. Open the repro link, select any item after the scroll and re-open it.
2. Click the select trigger and try to navigate the items using keyboard.

### Ark UI Version

4.5.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome Dev

**Comment by ivancuric** [comment]
Repro sample is down

**Comment by cschroeter** [comment]
@thevipinmishra 

Thanks for taking your time to report this issue. I could reproduce this in your Stackblitz and our Storybook setup.

**Comment by segunadebayo** [comment]
This regression was introduced by https://github.com/chakra-ui/ark/pull/3081

I just pushed a fix for this. We'll release an update shortly to see if it fixes the issue.
