### ISSUE TITLE
[Dialog] `closeOnInteractOutside` and `closeOnEscape` don't work with `unmountOnExit` and `lazyMount` in Next.js

### ISSUE THREAD

**Issue by livyk** [chakra-ui/ark#3175]
### Description

The dialog can't be closed by clicking outside or pressing the "Escape" button when it has `unmountOnExit` and `lazyMount`  in Next.js.  It works fine in React, the problem is reproducible only in Next.js (I tried 14.x).

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/github-ewhx9rcv

### Steps to Reproduce

1. Click "Open Dialog"
2. Press "Escape" key or click outside of the dialog component

**Expected behavior**

The dialog is closed.

**Actual behavior**

The dialog is opened, but the focus is returned to the trigger.

### Ark UI Version

4.5.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome

### Additional Information

Zag throws the warning

> [@zag-js/dismissable] node is `null` or `undefined`

I assume that zag tries to query the content  DOM element before it's rendered

![image](https://github.com/user-attachments/assets/81470aae-25e7-4d5e-801c-d66f61285da1)

**Comment by segunadebayo** [comment]
This regression was introduced by https://github.com/chakra-ui/ark/pull/3081

This has been fixed. We'll release an update shortly to see if it fixes the issue.
