### ISSUE TITLE
Select (or other) positioner is not stable on v4.5, It still works in v4.4.3

### ISSUE THREAD

**Issue by onepercman** [chakra-ui/ark#3181]
### Description

overlay loses coordinates after first trigger (applies with/without portal)

### Link to Reproduction (or Detailed Explanation)

...

### Steps to Reproduce

Just create your select component

### Ark UI Version

4.5.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

chrome

**Comment by segunadebayo** [comment]
This regression was introduced by https://github.com/chakra-ui/ark/pull/3081

It has been fixed. We'll release an update shortly to see if it fixes the issue.
