### ISSUE TITLE
docs: can't scroll sidebar

### ISSUE THREAD

**Issue by damienroche** [chakra-ui/ark#690]
We can't scroll lateral menu.
The docs sidebar has an `overflow-y_auto` class but it's not present in builded css. 
It's maybe an issue with `pandacss`

<img width="1492" alt="Capture d’écran 2023-03-28 à 20 47 41" src="https://user-images.githubusercontent.com/1529058/228337920-da2e0c91-67ae-4dc6-b0c0-e5b7a4d2ce3a.png">

**Comment by 0xATHERIS** [comment]
@anubra266 It's possible to scroll all the way to the right on the home page. This overflow issue is probably causing this issue too as the carousel doesn't seem to have an overflow set. Looks like overflow hasn't been configured in pandacss.

**Comment by cschroeter** [comment]
There was an issue in panda that now has been solved. Thanks for reporting the issue.
