### ISSUE TITLE
Docs: Clicking the Framework select causes the page to scroll to the bottom.

### ISSUE THREAD

**Issue by 0xATHERIS** [chakra-ui/ark#693]
As the title says.
Clicking this Select scrolls the current page to the bottom.
<img width="474" alt="Screenshot 2023-03-28 at 20 26 13" src="https://user-images.githubusercontent.com/112592168/228346242-41aafab6-d29f-4ba0-b2c1-2041e9a30b47.png">

**Comment by ChanhyukPark-Tech** [comment]
I can not reproducible I think select component is not affect entire page's scroll.. ! can't you upload video ?


https://user-images.githubusercontent.com/69495129/232831151-8d82d710-1bd5-48a8-b4b2-333023ea45e0.mov

**Comment by anubra266** [comment]
@ChanhyukPark-Tech 


https://user-images.githubusercontent.com/30869823/232833133-32f9b662-b7ba-40ec-b27e-bd8073bac29b.mp4
