### ISSUE TITLE
Module '"@ark-ui/solid"' has no exported member 'Dialog'

### ISSUE THREAD

**Issue by mattwells19** [chakra-ui/ark#720]
Hi friends! Sorry if it's too early for stuff like this, but I'm not able to import any components for the Dialog. When looking at intellisense there's actually only a handful of things that I can import.

![image](https://user-images.githubusercontent.com/36650048/229646552-9e099466-8524-4a97-9515-d8479a0f3ee1.png)

`@ark-ui/solid` version: "^0.0.0-rc-20221106094212"
`solid-js` version: 1.6.8

If there's anything else I can do to help let me know! Thanks!

**Comment by ShumRain** [comment]
I looked `@ark-ui/solid@0.0.0-rc-20221106094212` dist file, but is no `Dialog` related code, you can upgrade the version to `0.0.0-rc-20230403193437`

**Comment by ahhshm** [comment]
@ShumRain `0.0.0-rc-20221106094212` is the latest version according to [npm](https://www.npmjs.com/package/@ark-ui/solid). How can I upgrade it?

**Comment by ahhshm** [comment]
> @ahhshm @mattwells19 you can do this in your package.json until Ark is in v1 `"@ark-ui/solid": "rc",` Rerun `pnpm i`
> 
> Let me know if that works

Yes, it works. Thank you

**Comment by lvl-mattwells** [comment]
> @ahhshm @mattwells19 you can do this in your package.json until Ark is in v1 `"@ark-ui/solid": "rc",` Rerun `pnpm i`
> 
> Let me know if that works

That worked for me as well. Thanks!
