### ISSUE TITLE
Nuxt 3 / SSR support

### ISSUE THREAD

**Issue by lewebsimple** [chakra-ui/ark#727]
Hello, great project !!

I'm trying this out in a Nuxt 3 project and it seems that some components only work on the client-side (Dialog for example). The error is `ReferenceError: Element is not defined`

I'm not sure if this is preventable or not.

**Comment by Shyrro** [comment]
Hey @lewebsimple , thanks for reporting this issue 🙏 

It should now be fixed in the latest rc : `yarn add @ark-ui/vue@rc`. 

Let us know if you notice another issue, thanks !

**Comment by lewebsimple** [comment]
Stupendous, it works like a charm !

Any plans for including a nuxt 3 module ?
