### ISSUE TITLE
Latest NPM version out-of-date

### ISSUE THREAD

**Issue by SpencerDuball** [chakra-ui/ark#734]
After installing I noticed that some components I wanted to use did not exist in the exports, after investigating it appears that the "latest" version on NPM points to a release in 2022. See the captured screenshot from NPM (and also a link to the versions page). Suggested fix is to just point to the latest RC release:
![Screenshot 2023-04-07 at 10 21 18 AM](https://user-images.githubusercontent.com/22606045/230634229-04bc5cae-dd70-46b3-91b1-cfb08c97b18b.png)
https://www.npmjs.com/package/@ark-ui/react?activeTab=versions

**Comment by anubra266** [comment]
Until Ark is in a stable version, use 
```
"@ark-ui/react": "rc"
```
