### ISSUE TITLE
feat: Add Visual Testing Playgrounds

### ISSUE THREAD

**Issue by TylerAPfledderer** [chakra-ui/ark#762]
Currently, Ark uses the [PreviewJS](https://previewjs.com/docs) extension to preview component stories in all the frameworks.

Now with the release of [Storybook v7](https://storybook.js.org/docs/react/get-started/install/), we would like to use this tool instead to provide more reliable and robust support in visual testing.

Primary points to consider:
- Storybook has to be initialized within each individual framework, and not at the root. (This is recommended by the SB core team)
- Look at doing the setup in the React package first as the baseline, then mirror with Vue, then SolidJS.
  - Investigate if there is still added configs needed for Solid (It looks like there is a pending PR to [add Solid docs to SB](https://github.com/storybookjs/storybook/pull/21207) for reference)
- Use [Storybook Vite Builder](https://storybook.js.org/docs/react/builders/vite) since the packages are set up with this bundler.

_Edit: The React package has been given Storybook, but ran into issues for Vue. This will be incremental in trying to improve visual testing for all the packages._

- [X] Add Storybook for React - https://github.com/chakra-ui/ark/pull/768
- [ ] Add Histoire or Vite Playground for Vue
- [ ] Add Storybook or Other Option for SolidJS

**Comment by cschroeter** [comment]
I would love if we can find the same "storybook-like" solution for all supported frameworks.
As far as I remember there is no support for Svelte in [Storybook](https://storybook.js.org/docs/react/configure/frameworks-feature-support). 

Please also bear in mind that the examples in `*.stories.tsx` files are used in the docs. So changes there may need to be addressed in the docs

**Comment by TylerAPfledderer** [comment]
Hey @cschroeter ! 

To clarify for you, I had a discussion with @segunadebayo yesterday regarding the potential to get Storybook added, now that v7 is released, hence getting this issue up for any additional thoughts and feedback. 
Thank you for your feedback! 🙏

The [Intro to Storybook](https://storybook.js.org/tutorials/intro-to-storybook/svelte/en/get-started/) has a version for Svelte. 😀

And it is showing as a community option in the link you provided. The table mentions missing support for only controls and graphql, but the tutorial I linked is able to provide code snippets for the controls addon. 

I'm planning on being very incremental here, and asking for further feedback through this issue if I run into any snag regarding the docs or any unexpected issues in implementation by framework.

**Comment by TylerAPfledderer** [comment]
- https://github.com/chakra-ui/ark/pull/768 is merged to add Storybook to cover only React for now.

There was potential roadblocks with Vue against the generating of code snippets for the docs. Histoire is possibly being considered instead, else a Vite playground.

SolidJS could still have Storybook (barring any unexpected issues), but can consider a different option here!
