### ISSUE TITLE
Error: Failed to resolve entry for package "@ark-ui/vue".

### ISSUE THREAD

**Issue by toniengelhardt** [chakra-ui/ark#764]
Getting errors with Nuxt:

![Screenshot 2023-04-15 at 19 52 11](https://user-images.githubusercontent.com/2703233/232249173-b37e9098-6ec7-4ddd-b957-83ab698e5428.png)

Component:

```ts
<script setup lang="ts">
import {
  Tooltip,
  TooltipContent,
  TooltipPositioner,
  TooltipTrigger,
} from '@ark-ui/vue'

defineProps<{
  icon: string
  label: string
  description?: string
}>()
</script>

<template>
  <Tooltip flex items-center text-label text-xs>
    <TooltipTrigger>
      <Icon :name="icon" label-icon mr-1 /> {{ label }}
    </TooltipTrigger>
    <TooltipPositioner>
      <TooltipContent>{{ description }}</TooltipContent>
    </TooltipPositioner>
  </Tooltip>
</template>
```

**Comment by cschroeter** [comment]
Thanks for reporting the issue. What version do you use? Can you provide a sandbox?

**Comment by toniengelhardt** [comment]
`Nuxt 3.4.1`
`@ark-ui/vue 0.0.0-rc-20221106094212`

Here's a simple Stackblitz with the error: 
https://stackblitz.com/edit/nuxt-ark-ui-failed-to-resolve

**Comment by cschroeter** [comment]
There was an issue in this old version from 2022. Please use the latest version: https://stackblitz.com/edit/nuxt-ark-ui-failed-to-resolve-ifmdwq

**Comment by toniengelhardt** [comment]
Thanks, works 🙏🏽

The one from my repro was the one I got with `pnpm i @ark-ui/vue`. Would be great to publish that working one maybe.

**Comment by cschroeter** [comment]
We filed a 0.1.0 release today. :)

**Comment by toniengelhardt** [comment]
Amazing!
