### ISSUE TITLE
Expose {component}SplitProps 

### ISSUE THREAD

**Issue by astahmer** [chakra-ui/ark#807]
hey ! when wrapping components with ark-ui, I'd love to have some "splitProps" utils that would automatically split between my component props & the ones that can be passed to the ark-ui component

current implementation (props taken from the source [here](https://github.com/chakra-ui/ark/blob/7cabc3a1dc8e1cd90e19c60856a022958f20448c/packages/react/src/checkbox/checkbox.tsx#L19-L41)):
![image](https://user-images.githubusercontent.com/47224540/234071560-45a2ab6a-e692-4533-a57e-4be5f086a0fb.png)

wanted:
![image](https://user-images.githubusercontent.com/47224540/234071645-8881d82d-b9f8-4b44-89c7-bf436d33e707.png)

**Comment by cschroeter** [comment]
That's actually a nice idea.

**Comment by jiblett1000** [comment]
I'm using Vue, but this would be awesome.

**Comment by mikirejf** [comment]
@cschroeter 

Hey! I'd like to work on this (all of the instances). Is there a communication channel where I can reach you to quickly go over the naming and where to put the code? Or should I just open a PR with one changed instance and we go from there? Thanks!

**Comment by cschroeter** [comment]
Hey @mikirejf 👋 

I think a good approach would be you just take one of the components and then ping me.

Just as you proposed ;)

**Comment by cschroeter** [comment]
Thanks for all your inputs. For now we've decided not to export this internal utility function.
