### ISSUE TITLE
[NumberInput] [Vue]: v-model decimal error

### ISSUE THREAD

**Issue by jiblett1000** [chakra-ui/ark#814]
# 🐛 Bug report

When using v-model with the number input, any decimal point gets formatted away on input.

## 💥 Steps to reproduce

1. Enter number in input.
2. Try adding decimal point.
3. See value get reformatted without decimal and logged in the array below.

## 💻 Link to reproduction

I tried for the life of me to get any number of codesandboxes working, but they all just seem to hang indefinitely. Anyhow, created a stackblitz instead.

https://stackblitz.com/edit/nuxt-starter-frcagp?file=package.json,nuxt.config.ts,app.vue

## 🧐 Expected behavior

I expect to be able to use v-model and also be able to enter a decimal point in the field.

## 🧭 Possible Solution

No idea.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Ark Version      |            | 0.1
| Browser          |   Chromium         | 112.0.5615.165
| Operating System |   Fedora         | 38

**Comment by jiblett1000** [comment]
@anubra266 Just a heads up. I just redid this on Ark-ui as well.

**Comment by anubra266** [comment]
@jiblett1000 You're in Ark right now 😁

**Comment by jiblett1000** [comment]
@anubra266 My browser tabs are getting mixed up, lol

**Comment by TylerAPfledderer** [comment]
Hey @jiblett1000!

This behavior is very strange. We've been using `PreviewJS` for our visual testing, and I'm not seeing the issue through that.

However, both with the repro you provided and spinning up a local Vue environment yield the issue.

To reiterate what you have stated: essentially, if the max value were set at `50` and I type `14.`, say... once I try to type another number after the period, the text jumps to `50`.

@Shyrro I worked a little bit on adding Histoire to the package for better visual testing and tried the story example we have to see this. And it's working as expected. 🤔

**Comment by jiblett1000** [comment]
@TylerAPfledderer Thanks for looking into it :)

It doesn't seem to be doing it exactly as you describe on my end. Rather; if I type a number and then type a decimal point, it immediately removes the decimal from the value. If you see the log of the value I created below the input in the stackblitz, you will see the value with the decimal is added briefly and then followed immediately with whatever value was entered before that (without the decimal). For example, If I try to type 14 and a decimal after it, this is the log of the value.

```ts
1
14
14.  // tried typing decimal
14   // decimal automatically removed
14.
14   // same here
```

**Comment by jiblett1000** [comment]
@TylerAPfledderer Wow, so the plot thickens. While creating a repo for a separate bug report I will post shortly, I noticed something odd. The number input in this example didn't have the decimal point issue. I'm using a computed getter / setter in conjunction with a separate ref and altering it slightly somehow made the difference. Like so:

Doesn't work:

```ts
const currencyRef = ref('');

const currencyValue = computed({
  get() {
    return currencyRef.value;
  },
  set(value) {
    currencyRef.value = value
  },
});
```

Works: 

```ts
const currencyRef = ref('');

const currencyValue = computed({
  get() {
    return currencyRef.value;
  },
  set(value) {
    currencyRef.value = `${parseFloat(value)}`
  },
});
```

In the repo, I have a rounding function I'm using as well, but the key bit seems to be parsing the value to a float within a template literal from within the setter. I'm at a loss :open_mouth: 

Here's the new repo. Hope it helps somehow:

https://stackblitz.com/edit/nuxt-starter-rpkhqh?file=app.vue,components%2FCustomNumberInput.vue
