### ISSUE TITLE
[NumberInput] [Vue]: v-model decimal error

### ISSUE THREAD

**Issue by jiblett1000** [chakra-ui/ark#815]
When using v-model with the number input, any decimal point gets formatted away on input.

## Steps to Reproduce

1. Enter number in input.
2. Try adding decimal point.
3. See value get reformatted without decimal and logged in the array below.

## Reproduction

https://stackblitz.com/edit/nuxt-starter-frcagp?file=package.json,nuxt.config.ts,app.vue

## Versions

Ark v1.0
Browser | Chromium v112.0.5615.165
OS | Fedora 38

**Comment by anubra266** [comment]
@jiblett1000 I already transferred your issue from Zagjs to #814
