### ISSUE TITLE
[Select] [Vue] [Feature]: Custom data structure

### ISSUE THREAD

**Issue by jiblett1000** [chakra-ui/ark#827]
Hello,

This is related to https://github.com/chakra-ui/ark/issues/826. It would be great to be able to use a custom data structure for the `Select` component. This would make it possible to use any data source without having to translate it into `{ label: "", value: "" }`.

Use case:

Consider this scenario; currently, I'm trying to implement this with a list of currencies. The currency object structure is:

```ts
{
  code: "USD",
  decimal_digits: 2,
  name: "US Dollar",
  name_plural: "US dollars",
  rounding: 0,
  symbol:  "$",
  symbol_native:  "$",
}
```

It would be great to use this data structure directly within the default slot of `SelectOption` and subsequently sync it with my state management without additional fuss. At the very least, being able to pass it in addition to the `label` and `value` keys would be potentially sufficient. For example:

```ts
{
  label: "US Dollar",
  value: "",
  customData: {
    code: "USD",
    decimal_digits: 2,
    name: "US Dollar",
    name_plural: "US dollars",
    rounding: 0,
    symbol:  "$",
    symbol_native:  "$",
}
}
```

Currently any additional data is stripped from the selected option.

I'm not sure if changing this would affect accessibility adversely, but just throwing it out there as I think it would greatly increase the flexibility of the component.

**Comment by anubra266** [comment]
@jiblett1000 I think this would cause unnecessary overhead and complexity in the underlying logic. With the current approach, you can just check your array of objects with Array.find once it's time to use the value for something.

```js
const ccurrencyObj = currencies.find(c => c.code === selectedOption)
```

**Comment by jiblett1000** [comment]
@anubra266 As always, thanks for the response! Unfortunate to hear, but I can appreciate how it might complicate things on your end. I am currently using a solution similar to yours above (as well as mapping the options on the other side of things). I hope you will at least keep it in mind going forward :pray: , but if it never makes it in, also not the end of the world. Either way, I appreciate all the great work :smile:

**Comment by segunadebayo** [comment]
I did want to refactor the select machine to support that request. Downshift has one of the best APIs for select components, and we could take some ideas from it.

We also need to reduce the DOM queries we’re currently doing to find items in the dom. The current API struggles to handle virtualized selects (with large option data).

We'll improve this over time, but let's use the suggested approach from @anubra266.

**Comment by martinpengellyphillips** [comment]
fyi I just encountered this also and would have found it _much_ more ergnomic to be able to pass data along. In particular, the current approach makes `context.selectedOption` questionnable in its usefulness. For example, if I want to render a custom icon in the trigger button, I can't use context because I can't pass that information there. Instead I have to track outside of ark and lookup.
