### ISSUE TITLE
Investigate rounding issue in `NumberInput`

### ISSUE THREAD

**Issue by jiblett1000** [chakra-ui/ark#833]
Hello,

Another odd thing happening with `NumberInput`. I'm using the component for a currency input. I'm using a rounding function to round to the nearest 5 cents (0.05). I call the function within the setter of a computed ref to round the value, which sets it to another string ref and then I return that ref in the getter. Nothing too crazy. However, something is happening within `NumberInput` that will round the number up but not down. I've included a separate ref and associated watcher which rounds the number using the same rounding function and shows the correct value. For example:

If I enter 14.42, it should round to 14.4. Instead it stays at 14.42

If I enter 14.43, it should round to 14.5. It does as expected.

If I enter 14.46, it should round to 14.45. It does as expected. This is odd because now it's rounding down.

If I enter 14.48, it should round to 14.5. It does as expected

It's entirely possible there's a better way to handle this within `NumberInput`, however, this behavior is still inconsistent and so it seemed worth reporting. Here is the repo to see what I'm referring to.

https://stackblitz.com/edit/nuxt-starter-rpkhqh?file=app.vue,components%2FCustomNumberInput.vue

**Comment by Shyrro** [comment]
Hey @jiblett1000 , 

Thanks for opening this ! If you want to format the value, you can use the `format` prop that takes a callback. It goes like this : 

```vue
<script lang="ts" setup>
import { ref } from 'vue'
import {
  NumberInput,
  NumberInputControl,
  NumberInputDecrementTrigger,
  NumberInputField,
  NumberInputIncrementTrigger,
  NumberInputLabel,
  NumberInputScrubber,
} from '@ark-ui/vue'
const roundCurrency = (val: string, rounding: number) => {
  if (rounding === 0) {
    return val;
  }
  if (val?.split('.')?.[1] !== undefined) {
    const value = parseFloat(val)

    const round = 1 / rounding;
    return Math.round(value * round) / round;
  }
};
const value = ref('14.4')
</script>
<template>
  <span>Input value : {{ value }}</span>
  <NumberInput v-model="value" :min="-50" :max="50" :format="(value) => roundCurrency(value, 0.05)">
    <NumberInputScrubber />
    <NumberInputLabel>Label</NumberInputLabel>
    <NumberInputField />
    <NumberInputControl>
      <NumberInputDecrementTrigger>
        <button>-1</button>
      </NumberInputDecrementTrigger>
      <NumberInputIncrementTrigger>
        <button>+1</button>
      </NumberInputIncrementTrigger>
    </NumberInputControl>
  </NumberInput>
</template>
```

Be mindful that this changes directly your input value. I also added a condition so that the parse doesn't work if you pass in `14.` otherwise it will format the value as `14.0`. 

Let me know if that solves you issue

**Comment by jiblett1000** [comment]
@Shyrro Thanks! That created a new issue however where the user has to press `.` twice to enter a decimal point. The rounding does seem to work though.

Oddly, upgrading ark/vue in my reproduction to 0.2 causes my getter/setter to not reflect in the input at all. Or more accurately; the setter is working (and rounding correctly) as you can see in the `currencyRef` I added to in the template below the input, however the updated value is not getting updated to the input through the getter.

https://stackblitz.com/edit/nuxt-starter-rpkhqh?file=components%2FCustomNumberInput.vue,package.json,app.vue

**Comment by cschroeter** [comment]
`NumberInput` has been revised and none of the mentioned issues could be reproduced.

**Comment by jiblett1000** [comment]
@cschroeter Awesome! Thanks for sorting it out :)
