### ISSUE TITLE
[Select] [Vue] Missing ID prop

### ISSUE THREAD

**Issue by jiblett1000** [chakra-ui/ark#841]
### Description

Title pretty much sums it up. The id prop is missing from the Select component to be able to pass a UID to the machine.

### Link to Reproduction

https://stackblitz.com/edit/nuxt-starter-dhrjds?file=nuxt.config.ts,components%2FCustomNumberInput.vue,package.json,components%2FCustomSelectInput.vue,app.vue

### Steps to reproduce

Doesn't seem like a reproduction is really necessary for this, but it you go to the reproduction:

1. Click on "Open in new Tab" on the top right.
2. Open the browser developer console.
3. See the logged error(s) `extraneous non-props attributes (id) were passed to component...` as the id prop isn't available on the select component.

### Ark UI Version

0.0.0-rc-20230428162935

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

Chromium 112.0.5615.165

**Comment by cschroeter** [comment]
Closing in favour of https://github.com/chakra-ui/ark/issues/825
