### ISSUE TITLE
[Vue] Inconsistent component wrapper

### ISSUE THREAD

**Issue by jiblett1000** [chakra-ui/ark#842]
### Description

I noticed that the layout of the components I am creating were behaving differently and realized this was due to one (`NumberInput`) automatically rendering a wrapper div while the other (`Select`) did not render any wrapper. This leads to inconsistent layout behavior. 

I haven't checked any of the other components yet, but it seems like they should maybe all be wrapped the same (or at least similarly) or not wrapped at all. The reproduction shows the two inputs side by side in a flex container and the effects of having one wrapped while the other isn't.

I know this is easily remedied by just adding a wrapper around the Select component, but again, personally I would opt for consistency right off-the-bat.

### Link to Reproduction

https://nuxtstarterdhrjds-oyrs--3000--d830b1a2.local-credentialless.webcontainer.io/

### Steps to reproduce

1. Go to repro.
2. See the wonky layout.

### Ark UI Version

0.0.0-rc-20230428162935

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

Chromium 112.0.5615.165

**Comment by cschroeter** [comment]
Thanks for taking the time and reporting this issue.

There is a difference between a "portalled" component like a`Select` or a `Combobox` and a `NumberInput` or `PinInput`. Therefore its in user hands to ensure a consistent look and behaviour across all components.
