### ISSUE TITLE
Homepage: Cannot click on checkbox items in menu example 

### ISSUE THREAD

**Issue by pheianox** [chakra-ui/ark#844]
### Description

When I open this menu and use arrow keys to navigate through items in the menu I expect all items clickable e.g. radio group items are all clickable but checkbox group items are not

![image](https://user-images.githubusercontent.com/77569421/235288076-1d750fa3-6b1c-42f8-8f58-7e0a83064b61.png)

### Link to Reproduction

https://ark-ui.com/

### Steps to reproduce

-

### Ark UI Version

Current

### Framework

- [ ] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome 112.0.5615.165 (Official Build) (64-bit)

**Comment by cschroeter** [comment]
Thanks for reporting the issue. Should be fixed by now

**Comment by pheianox** [comment]
Thank you!
