### ISSUE TITLE
Cannot import Splitter (solid-js)

### ISSUE THREAD

**Issue by pheianox** [chakra-ui/ark#848]
### Description

```ts
import { Splitter } from '@ark-ui/solid'
```

> Module '"@ark-ui/solid"' has no exported member 'Splitter'.

### Link to Reproduction

-

### Steps to reproduce

-

### Ark UI Version

0.1.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

### Browser

Chrome 112.0.5615.165 (Official Build) (64-bit)

### Additional Information

-

**Comment by cschroeter** [comment]
Is fixed in 0.20

**Comment by pheianox** [comment]
Happy to help!
