### ISSUE TITLE
[Tabs] [Vue]: focused slot prop

### ISSUE THREAD

**Issue by jiblett1000** [chakra-ui/ark#867]
### Description

I know it's possible to use the `@change` event to accomplish the same thing, but it would be for DX to also have the selected tab (and focused tab) exposed as a slot props.

### Proposed Solution or API

```html
<Tabs v-slot="{ selectedTab, FocusedTab }">
```

**Comment by codebender828** [comment]
What value would you like to be returned in the `FocusedTab` slot?

**Comment by jiblett1000** [comment]
@codebender828 Just the string value of the currently selected tab so I can do a comparison in my templates for styling, etc. I can elaborate further if need be.

**Comment by codebender828** [comment]
Interesting use case. Opened PR for this #868 . Does the example satisfy your use case?

**Comment by jiblett1000** [comment]
Thanks! @codebender828. I'm switching over from headlessui https://headlessui.com/vue/tabs#using-slots. It's pretty common in that library to expose various state through slot props. Gives a nice developer experience.

And actually, after looking at their tabs example again, it would be even more ideal to expose them as booleans on the TabTrigger component. Your PR would work fine I think, but doing it the way they do it is even more concise I think.

```vue
<Tabs>
    <TabTrigger 
        v-slot="{ isSelected }" 
        :class="[isSelected && 'someClass']"
    >
        {{ blah blah }}
    </TabTrigger>
</Tabs
```
Perhaps the focused state is actually unnecessary here as the focus pseudo selector can be used for styling :thinking:
