### ISSUE TITLE
[Vue]: Add 'as' prop to all components

### ISSUE THREAD

**Issue by jiblett1000** [chakra-ui/ark#874]
### Description

This is somewhat related to https://github.com/chakra-ui/ark/issues/842

In general, it would be great if all the Vue components accepted the `as` prop which allows rendering them as a particular element.

In reference to the above issue, it would allow using the `Select` component as a wrapper itself (or none if omitted) rather than adding a separate one around it.

But, in general I think it would allow greater customization across the library as  whole.

### Proposed Solution or API

A couple examples:

```vue
<Select as="div">
    <SelectContent as="div">
        <SelectOption as="div" />
    </SelectContent>
</Select
```
Chances are you wouldn't want to change `SelectContent` and `SelectOption` from their default `ul` and `li` tags. This is purely to illustrate the idea.

```vue
<Tabs as="section">
    <TabTrigger as="button" />
    <TabContent as="article" />
</Tabs>
```
Again; not sure this would make sense semantically speaking. Just illustrating.

**Comment by Shyrro** [comment]
Hey @jiblett1000 

Thanks for opening this. 

I think that you can already do it, it's just not declared as a prop, but is treated like an attribute. So you don't have autocomplete.

If you notice any components where it's not working, feel free to open it as a bug.
We can also declare it as a prop to improve typing if necessary.

Also, as a small note, beware when using the as prop to not change or break the accessibility/semantic of your component.

**Comment by jiblett1000** [comment]
@Shyrro So, here's an example of where it would be nice to be able to pass the `as` prop and have the component optionally render a certain tag.

Currently:
```vue
<DialogCloseTrigger>
    <button
       class="text-primary-light dark:text-primary-dark p-3 font-medium"
    >
        Cancel
     </button>
</DialogCloseTrigger>
```

Would be nice:
```vue
<DialogCloseTrigger 
    as="button"
    class="text-primary-light dark:text-primary-dark p-3 font-medium"
>
   Cancel
</DialogCloseTrigger>
```

I know it's a small thing, but it can help reduce visual clutter. I can of course create an issue for this. Just wanted to continue the discussion here as well.
