### ISSUE TITLE
[Dialog] [Vue]: open prop not working as expected

### ISSUE THREAD

**Issue by jiblett1000** [chakra-ui/ark#890]
### Description

Here's my daily bug report :stuck_out_tongue_winking_eye: 

I am currently trying to create a couple different generic dialog components and found the `open` prop to not be working as I expected. I need to be able to control the state of the dialog from the parent and so I was hoping to be able to pass the `open` prop through my custom dialog component and bind it to `Dialog`, however nothing happens...the dialog does not open.

The only way I've found is to either include the dialog trigger component within my custom dialog component (which essentially eliminates reusability) or pass in the trigger component through a slot which is not always ideal either. 

Being able to trigger the dialog through a reactive variable in the parent or some global state is sometimes ideal, for example, If I have multiple different buttons throughout my app that activate the same dialog...

P.S. I've also swapped out the `DialogCloseTrigger` component within the custom dialog to illustrate the same effect (or lack thereof), not because I have a particular use-case for not using the close trigger component.

### Link to Reproduction

https://stackblitz.com/edit/nuxt-starter-3jzcrb?file=app.vue,components%2FCustomDialog.vue

### Steps to reproduce

1. Click on "Open dialog" button.
2. See the state of the `dialogIsOpen` ref above the button (but dialog not open).
3. Change the initial ref value to true.
4. Try closing the dialog.
5. See the state of the `dialogIsOpen` ref above the button (but dialog not close).

### Ark UI Version

0.2

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

113.0.5672.63

**Comment by TylerAPfledderer** [comment]
Hey @jiblett1000! Thank you for your time in providing your observations. It is greatly appreciated. 😄 

This might be a good case for two-way binding. I'll be checking this one out to make an improvement.

**Comment by jiblett1000** [comment]
@TylerAPfledderer Happy to! Likewise, thanks for the great work.

I think two-way binding here would be awesome :smile:

**Comment by TylerAPfledderer** [comment]
@jiblett1000 this is now available @ `@ark-ui/vue@0.0.0-rc-20230507021911` to test out!

**Comment by jiblett1000** [comment]
Thanks @TylerAPfledderer ! Will do shortly.

**Comment by jiblett1000** [comment]
@TylerAPfledderer Seems to be working great :+1: 

I've noticed another improvement to be made while working on a reproduction to test it however. I will post it in a sec.

**Comment by jiblett1000** [comment]
@TylerAPfledderer And said bug report https://github.com/chakra-ui/ark/issues/901

**Comment by jiblett1000** [comment]
@TylerAPfledderer This isn't crucial, but I've noticed something else... more of a question really.

In this repo: https://stackblitz.com/edit/nuxt-starter-izqp4z?file=package.json,app.vue,components%2FChildDialog.vue,components%2FParentDialog.vue

If you:

1. Open the parent dialog.
2. Click the "x" to open the confirm close (child) dialog.
3. In the child dialog, click the "x" in the corner (which is using the `CloseDialogTrigger` component) to close the child dialog.

Shouldn't this still update the two-way bind value and update the `isOpen` ref or are these entirely separate ways of interacting with the component?

P.S. You'll notice the commented out button below the `DialogCloseTrigger` which is fine and makes everything work as expected.

**Comment by TylerAPfledderer** [comment]
@jiblett1000 
This looks to be a separate. With your example, you would have to add a watcher in the parent for `childDialog` to trigger the readout of the reactivity.

```ts
watch(
  () => childDialog.value,
  (value) => {
    childDialog.value = value;
  }
);
```

**Comment by jiblett1000** [comment]
@TylerAPfledderer Fair enough. No biggie. I can use the other button. Thanks for the insight!

I'm now running into the oddest problem. It's most likely user error, but for the life of me, I can't seem to figure out what's going on. The weirdest thing is that I wasn't able to reproduce it in stackblitz. However, it is happening locally. I created a local reproduction to try and nail it down, but it's happening there as well. If you have a sec, I would greatly appreciate you taking a look. It could be a bug as well.

https://github.com/jiblett1000/Ark-Dialog

Essentially, what's happening is that when you open the  fullscreen dialog and then click on the "x", it pops up the confirm close dialog. If you click the "discard" button, everything works as expected (the child and parent dialogs close; all the refs update accordingly). However, if you click the "cancel" button, only the child dialog should close, but instead it closes the parent dialog as well but doesn't update the parent dialog refs and prevents it from being opened again as well.

For reference, this is the stackblitz with it working as expected:

https://stackblitz.com/edit/nuxt-starter-izqp4z?file=components%2FChildDialog.vue,components%2FParentDialog.vue,app.vue,components%2FCustomDialog.vue,package.json,package-lock.json

I hope it's something I just keep glazing over, but I'm at a loss....

**Comment by jiblett1000** [comment]
@TylerAPfledderer You can ignore that last message. I realized I had to set `:close-on-outside-click="false"` on the parent dialog, since the child dialog was being teleported to the body, it was being treated as an outside click and thus closing the parent.
