### ISSUE TITLE
[Dialog] [Vue]: add "unmount" prop

### ISSUE THREAD

**Issue by jiblett1000** [chakra-ui/ark#901]
### Description

Hello again,

While working on a reproduction to test https://github.com/chakra-ui/ark/pull/898, I encountered another opportunity for an improvement.

In the reproduction I have a nested dialog within another dialog. In the parent dialog I use the child dialog and pass two "action" buttons into the child dialogs' `actions` slot. This is the "correct" code, or rather it works as I intend it to.

Working code:
```vue
<template #actions>
  <div class="flex gap-5">
      <button
          @click="childDialog = false"
      >
          Cancel
      </button>

       <button
           childDialog = false;
           @click="$emit('close')"
       >
           Close parent
        </button>
  </div>
</template>
```

"Incorrect" code:
```vue
<template #actions>
  <div class="flex gap-5">
      <button
          @click="childDialog = false"
      >
          Cancel
      </button>

       <button
           @click="$emit('close')"
       >
           Close parent
        </button>
  </div>
</template>
```

Notice the omitted `childDialog = false` on the second button. This caused the childDialog ref to remain true when I tried to reopen the parent dialog and thus the child dialog would not open.

This is a long-winded way of pointing out that if the parent dialog were allowed to unmount completely, the childDialog ref would have reset and the "incorrect" code above would've still worked.

There are of course other instances where it might be desirable to unmount a component entirely and there might be other Ark components where an added `:unmount` prop would come in handy too (not sure which off the top of my head).

### Proposed Solution or API

Add an `:unmount` prop to allow a component to unmount completely. In regards to Vue, this would essentially be the equivalent of `v-if` vs `v-show`.

**Comment by Shyrro** [comment]
Hey @jiblett1000 

I'm actually wondering, what would be the benefit of adding an `unmount` prop, vs the consumer adding a `v-if` himself to the component he wants unmounted at a given moment?

**Comment by jiblett1000** [comment]
@Shyrro My initial thought was just that of maintaining a consistent way of interacting with the dialog component state through the `open` prop. 

For example:

```
<Dialog :open="someRef" :unmount="false">
```
Rather than this:

```
<Dialog v-if="someRef" :open="true">
```

Definitely not the end of the world to do it the 2nd way. I don't know. It just feels more consistent to me doing it the first way.

Probably a better rationale for adding the prop however, is to keep the functionality of the `Dialog`s' events. Consider this reproduction:

https://stackblitz.com/edit/nuxt-starter-jq9zuv?file=app.vue

If using a v-if on the `Dialog` component such as the second code example above, anything relying on the state of the open prop doesn't trigger (such as the open/close events).

Using an unmount prop, I'm assuming could allow the unmounting of the dialog component while also keeping the functionality of those events (and anything else internally relying on the open props' state).

On a somewhat related note. I'm not sure how using vue `Transition` components are going to be handled in Ark since I believe they do rely on a `v-if` or `v-show` being the child element. But maybe that could be handled internally with an unmount prop as well. 

So far my attempts to use the Transition component with Ark have been unsuccessful, but I haven't tried in a while so perhaps that has changed.

Anyhow, sorry for the mind dump. It's late here so my brain is shutting down. :sleeping:

**Comment by Shyrro** [comment]
Thanks for your answer @jiblett1000 ! 

We will later add a way to lazy mount components, we'd have to work it out to be fitting to all three frameworks in Ark. We have an idea on how to do it. 

For the moment, you'll have to do the `v-if` yourself and wrap it in your Transition component.

**Comment by jiblett1000** [comment]
Thanks @Shyrro. I will use `v-if` in the meantime then. I'm going to post a reproduction with the Transition errors I'm getting soon as well.

**Comment by cschroeter** [comment]
Closing in favour of #1362
