### ISSUE TITLE
[Tabs] [Vue]: defaultValue name

### ISSUE THREAD

**Issue by jiblett1000** [chakra-ui/ark#915]
### Description

I know this is super nitpicking, but nonetheless; While looking at the `Tabs` docs just now, I noticed the use of the `defaultValue` being used in the "control the selected tab" section. Functionally I know this isn't an issue, but semantically speaking, using that name for this seems odd. You would only really set a default once, not repeatedly.

I propose either:

1. Keeping `defaultValue` for (you guessed it) setting the default value and adding a second `selectedTab` (or `selectedTab`, etc) to control the active tab. I guess you would just have to deal with the scenario where both are set and have initial values and which would win out.

2. Just rename `defaultValue` to `selectedTab` (or whatever) and then just use the initial state of the ref as the default value. Like so:

```
<Tabs :selectedTab="selectedTab">...</Tabs>

const selectedTab = ref('initial-value')
```

Just my two cents. Cheers!

### Link to Reproduction

N/A

### Steps to reproduce

N/A

### Ark UI Version

0.2

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

**Comment by jiblett1000** [comment]
Just as a comparison; the `Select` component has a `selectedOption` prop but no `defaultOption` prop.

**Comment by segunadebayo** [comment]
Interesting thoughts @jiblett1000.

We’re going to keep it as defaultValue. Ideally, we should update the docs to showcase/support both `value` and `defaultValue`

- `defaultValue` : sets the initially selected tab that matches the value
- `value` :  set the selected tab (in controlled mode) to be programmatically changed.

cc: @Shyrro

**Comment by renatodeleao** [comment]
@segunadebayo 👋 wouldn't it be better to use `modelValue` + `update:modelValue`, allowing to use default `v-model` when in controlled mode? 

Cheers!

**Comment by cschroeter** [comment]
I agree @renatodeleao 

I've revised the tabs component and created a couple of different stories and I can basically cover everything 
https://github.com/chakra-ui/ark/blob/main/packages/vue/src/tabs/tabs.story.vue
