### ISSUE TITLE
[Checkbox]: Need to click twice to see checkbox state change

### ISSUE THREAD

**Issue by nassimbenkirane** [chakra-ui/ark#941]
### Description

When I toggle the checkbox component on the [ark-ui docs website](https://ark-ui.com/docs/react/components/checkbox)
I expect it to change state at each click, but it only changes state after two clicks.

Bug is present in React Solid and Vue

### Link to Reproduction

https://ark-ui.com/docs/react/components/checkbox

### Steps to reproduce

1. Go to  https://ark-ui.com/docs/react/components/checkbox
2. Click on the checkbox  (clicked once)
3. Click on the checkbox again  (clicked twice)
4. See error : checkbox doesn't change state
5. Click on the checkbox again (clicked three times)
6. See that it does changes the state after two clicks

### Ark UI Version

@ark-ui/react@0.3.0

### Framework

- [X] React
- [X] Solid
- [X] Vue

### Browser

113.0.5672.92

### Additional Information

Screen capture here :
![Enregistrement_de_l’écran_2023-05-12_à_11_35_40_AdobeExpress (1)](https://github.com/chakra-ui/ark/assets/1640952/432f47b1-881b-4190-851f-69f92a230a01)

**Comment by cschroeter** [comment]
Thanks for taking time to report this issue. Fix will be in the next release.
