### ISSUE TITLE
[Pressable][React]: onLongPress doesn't work when triggered by keyboard space key(also Enter key).

### ISSUE THREAD

**Issue by ryuhangyeong** [chakra-ui/ark#949]
### Description

<img width="508" alt="image" src="https://github.com/chakra-ui/ark/assets/27342882/a0b3a530-f13a-4108-936c-e772a89dbe6b">

`onLongPress` doesn't work when triggered by keyboard space key(also Enter key).

### Link to Reproduction

https://ark-ui.com/docs/react/components/pressable

### Steps to reproduce

1. Go to [Link](https://ark-ui.com/docs/react/components/pressable)

### Ark UI Version

recent

### Framework

- [X] React
- [X] Solid
- [X] Vue

### Browser

Google Chrome 112.0.5615.138

**Comment by segunadebayo** [comment]
Hi @ryuhangyeong,

This is by design. Long press events only relate to pointer (touch, mouse) interactions, not the keyboard.

**Comment by ryuhangyeong** [comment]
@segunadebayo Thanks~!
