### ISSUE TITLE
Integration of ark with Macaron.js: Is it Possible to Use Them Together?

### ISSUE THREAD

**Issue by Yvictor** [chakra-ui/ark#972]
### Description

I would like to know if it's possible to integrate ark with Macaron.js.

### Proposed Solution or API

https://macaron.js.org/docs/styling

### Additional Information

I am immensely grateful for your efforts in creating ark.

**Comment by anubra266** [comment]
@Yvictor you can style with anything. It's headless. Macaron example here
https://codesandbox.io/p/sandbox/ark-marcaron-vite-react-35eh2z?file=%2Fsrc%2FApp.tsx%3A49%2C16
