### ISSUE TITLE
Element with id "checkbox:1:input" not found.

### ISSUE THREAD

**Issue by jiblett1000** [chakra-ui/ark#981]
### Description

Having an issue with the checkbox component where it can't seem to find the element in the dom or some such case. You should be able to see the error upon loading the repoduction.

### Link to Reproduction

https://stackblitz.com/edit/nuxt-starter-yyjnfg?file=package.json,package-lock.json,components%2FCustomCheckbox.vue,pages%2Findex.vue,pages%2Fpage-2.vue,app.vue,nuxt.config.ts,tsconfig.json

### Steps to reproduce

Open reproduction

### Ark UI Version

0.0.0-rc-20230520173736

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

**Comment by Shyrro** [comment]
Hey @jiblett1000 

Thanks for reporting this. This might be an SSR issue. 

I will look into it, in the meantime, you can add a custom id as a workaround.

**Comment by cschroeter** [comment]
We've applied a lot of changes. Please re-test and open a new issue if the problem persist.
