### ISSUE TITLE
[Vue] [Tabs]: unmount prop

### ISSUE THREAD

**Issue by jiblett1000** [chakra-ui/ark#996]
### Description

I've run across a couple issues while using the tabs component which essentially boiled down to the fact that all of the `TabContent` components are mounted initially but are set to `display: none`.

 I have various components in the tabs where I'm getting widths of elements in the `onMounted` hook and then using those values. However, for the tabs that aren't active when the `Tabs` component first mounts, those values come out to 0 because the tab is set to `display: none`.
 
 My workaround is actually really easy. Just adding a `v-if` to each `TabContent` solves the issue. Like so:
 
 `<TabContent v-if="activeTab === 'TabName'" value="TabName">`
 
 So, while this is not an urgent need, it could be beneficial to the developer experience to include this as a prop on the `Tabs` component once rather than littering the template with a bunch of if statements.

### Proposed Solution or API

I'm thinking just having a prop such as `Tabs :unmount="true"` or something similar. This would mount/unmount each tab on change or keep the current behavior if set to false or if ommitted.

**Comment by Shyrro** [comment]
Same answer as this : https://github.com/chakra-ui/ark/issues/901#issuecomment-1567138626

**Comment by cschroeter** [comment]
Closing in favour of #1362
