### ISSUE TITLE
[Vue][Toast]: Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by jiblett1000** [chakra-ui/ark#998]
### Description

Throws error `Cannot read properties of undefined (reading 'value')` when trying to add a toast. Perhaps I'm missing something in the docs :thinking: 

### Link to Reproduction

https://stackblitz.com/edit/nuxt-starter-2jvls7?file=app.vue,components%2Fapp-toast-provider.vue

### Steps to reproduce

Click "Add toast" button. See console error.

### Ark UI Version

0.4

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

**Comment by anubra266** [comment]
@jiblett1000 The issue is your app.vue example is not wrapped by the toast provider, so it doesn't have the toast context.

**Comment by jiblett1000** [comment]
Thanks @anubra266 :smile: . I see that section under the React docs now. However, it seems to be missing from the Vue docs currently.

**Comment by anubra266** [comment]
> Thanks @anubra266 :smile: . I see that section under the React docs now. However, it seems to be missing from the Vue docs currently.

Yeah we'll add it to the vue docs soon.
